### ISSUE TITLE
UnsatisfiedLinkError NativeMemoryChunk x86_64

### ISSUE THREAD

**Issue by robert-wallis** [facebook/fresco#192] opened 2015-04-24 00:42 UTC
We're getting the following error on x86_64 devices only.  Including the Google Play Services x86_64 emulator image, Galaxy S6, and Galaxy S6 Edge.

We tried adding the proguard rules mentioned in #171 but without success.

Any Ideas?

Thanks!

```
04-23 20:36:51.902  22309-23567/com.example.dev E/AndroidRuntime﹕ FATAL EXCEPTION: pool-3-thread-2
    Process: com.example.dev, PID: 22309
    java.lang.UnsatisfiedLinkError: com.facebook.imagepipeline.memory.NativeMemoryChunk
            at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
            at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
            at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:264)
            at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
            at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:36)
            at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(NativePooledByteBufferFactory.java:131)
            at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(NativePooledByteBufferFactory.java:26)
            at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:97)
            at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(NetworkFetchProducer.java:36)
            at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:73)
            at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher$1.run(HttpUrlConnectionNetworkFetcher.java:58)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)```

**Comment by DHuckaby** [comment] 2015-04-24 00:51
Possible duplicate of #120? If so a fix is in progress with #121

**Comment by robert-wallis** [comment] 2015-04-24 03:15
Unfortunately I also get the crash after building with the code in #121 and #176.

**Comment by robert-wallis** [comment] 2015-04-24 19:33
Update: this exact same error happens on the HTC M9.

**Comment by tyronen** [comment] 2015-06-04 10:06
Can you try again and see if this is still happening in v0.5.1?

**Comment by tyronen** [comment] 2015-09-22 10:24
I'll take it that's a no.

**Closed** 2015-09-22 10:24 UTC
Labels: build, needs-details

**Comment by JackPeel** [comment] 2017-02-24 02:49
I hava a problem that’s " java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[...] couldn't find "libmemchunk.so"",how to solve ？

**Comment by wudongjiang333** [comment] 2017-07-31 06:24
this is still happening in v1.4.0 .How to fix it?
