### ISSUE TITLE
Adapter Android 10

### ISSUE THREAD

**Issue by liwentuo** [facebook/fresco#2550] opened 2020-10-21 06:47 UTC
Android 10 Open the album and the video cover is blank

**Comment by defHLT** [comment] 2020-11-01 20:32
Seems to be a duplicate of #2549

**Closed** 2020-11-01 20:32 UTC
Labels: duplicate

**Comment by stven0king** [comment] 2021-08-17 02:19
May need to upgrade to a new version [#2593](https://github.com/facebook/fresco/issues/2593)
