### ISSUE TITLE
Bad Performance In ListView & RecyclerView When Scroll Fast

### ISSUE THREAD

**Issue by demonbibi** [facebook/fresco#1893] opened 2017-09-06 03:51 UTC
1. Open the "Profile GPU rendering -> On Screen as bars" in Developer options.
2. Open the "showcase" App you provided.
3. Scroll fast in RecyclerView, the bars on screen is light green and deep green, and it represents the measure and layout processes is costing a lot.
4. About phone: CPU 2.45GHz, RAM 3.00GB, Android version 6.0.1.
5. the bad performance is also appears in ListView, I just use the default SimpleDraweeView.

**Comment by lambdapioneer** [comment] 2017-09-06 10:45
Hey @demonbibi, these kind of regressions can be caused by very verbose logs (like they are the default in the showcase app). Try to set `FLog.setMinimumLoggingLevel(FLog.ERROR);`

On my emulator with `VERBOSE` (default):

![screen shot 2017-09-06 at 11 42 20 am](https://user-images.githubusercontent.com/908387/30108043-a302630a-92f8-11e7-8a02-8a0b3e15db88.png)

On my emulator with `ERROR`:

![screen shot 2017-09-06 at 11 42 51 am](https://user-images.githubusercontent.com/908387/30108060-ae626e5c-92f8-11e7-8d05-8b6bb593559e.png)

Let me know if this solves the issue for you.

CC @oprisnik (do we maybe to change the default log level?)

**Comment by foghina** [comment] 2018-01-18 13:24
Just verified as well that turning off logging in the RecyclerView sample in our Showcase app greatly improves dropped frames. Closing the issue now.

**Closed by foghina** 2018-01-18 13:24 UTC
Labels: question
