### ISSUE TITLE
Samsung: NativePooledByteBuffer cannot be cast to PooledByteBuffer

### ISSUE THREAD

**Issue by droidwolf** [facebook/fresco#460] opened 2015-07-15 07:34 UTC
```
com.facebook.imagepipeline.memory.NativePooledByteBuffer cannot be cast to com.facebook.imagepipeline.memory.PooledByteBuffer
       at com.facebook.imagepipeline.cache.BufferedDiskCache$2.run(BufferedDiskCache.java:158)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)
```

**Comment by michalgr** [comment] 2015-07-15 17:10
Is this art specific ? Is this vendor specific ? NativePooledByteBuffer implements PooledByteBuffer interface: https://github.com/facebook/fresco/blob/96d74f385b297f364db1f719dd6ee61fc380d0d4/imagepipeline/src/main/java/com/facebook/imagepipeline/memory/NativePooledByteBuffer.java which indicates that the issue is not within the Fresco library. I don't think we can help with this one. Don't you see similar exceptions for other classes ?

**Comment by plamenko** [comment] 2015-08-05 12:12
This smells like a Samsung issue. @droidwolf, does this happen on several different devices?

**Comment by droidwolf** [comment] 2015-08-06 04:15
Yes, Samsung GT-S7898. Didn't find the other devices

**Comment by plamenko** [comment] 2015-08-07 15:24
Yeah, on my SGS5, Uber, GTalk, Strava and some other apps are consistently insta crashing with similar stack traces. Unfortunately we do not yet know the root cause of this.

**Comment by erikandre** [comment] 2017-07-11 16:02
Closing as this has not been updated for almost 2 years

**Closed by erikandre** 2017-07-11 16:02 UTC
Labels: build
