### ISSUE TITLE
ExifInterface: Invalid image.

### ISSUE THREAD

**Issue by hpdx** [facebook/fresco#1558] opened 2016-11-29 06:46 UTC
11-29 14:38:58.418 27599-27644/? W/ExifInterface: Invalid image.
                                                  java.io.IOException: Invalid marker: 89
                                                      at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1612)
                                                      at android.media.ExifInterface.loadAttributes(ExifInterface.java:1335)
                                                      at android.media.ExifInterface.<init>(ExifInterface.java:1053)
                                                      at com.facebook.imagepipeline.producers.LocalExifThumbnailProducer.getExifInterface(LocalExifThumbnailProducer.java:136)
                                                      at com.facebook.imagepipeline.producers.LocalExifThumbnailProducer$1.getResult(LocalExifThumbnailProducer.java:103)
                                                      at com.facebook.imagepipeline.producers.LocalExifThumbnailProducer$1.getResult(LocalExifThumbnailProducer.java:97)
                                                      at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:45)
                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                      at java.lang.Thread.run(Thread.java:818)

**Comment by massimocarli** [comment] 2016-11-29 11:16
Hi @hpdx ,
Can you provide us the image Url please?
Thanks

**Comment by ChenSiLiang** [comment] 2016-12-14 06:52
same issue.
@massimocarli It seems this native method return null
`nativeGetRawAttributesFromFileDescriptor()` in ExifInterface.class.
So `handleRawResult()` return false and it call `getJpegAttributes(in)`.

**Comment by lambdapioneer** [comment] 2016-12-14 10:53
@ChenSiLiang can you provide us with a sample image file that shows the described behavior? That would allow us to verify the fix and add unit tests to avoid regressing this.

**Comment by ChenSiLiang** [comment] 2016-12-15 02:10
sure, like this
![cat_185 1](https://cloud.githubusercontent.com/assets/9266250/21209342/ba57c484-c2ae-11e6-81c5-f5af619fafba.png)

**Comment by hzw1199** [comment] 2017-02-01 03:52
I find this to be solved in fresco 1.0.1

**Comment by erikandre** [comment] 2017-04-24 14:38
Closing issue as the problem is reported to be solved :)

**Comment by kirwan** [comment] 2017-05-17 08:38
I don't think this was actually solved as it's been reported again in #1760.

The key thing which I think was missed before is that the image is a PNG and EXIF data is only available in JPEGs.

**Closed** 2017-05-17 10:47 UTC
Labels: bug

**Comment by farwayer** [comment] 2017-06-13 17:37
@kirwan I just trapped into this issue with React Native in combination with CodePush. Is any chance new version with fix will be released soon?

**Comment by kirwan** [comment] 2017-07-17 12:53
This is now fixed in Fresco 1.4.0. @farwayer if this is causing a problem for you with React Native, we'll need to get that updated to use 1.4.0.
