### ISSUE TITLE
Images not loading when app is build with Android App Bundle

### ISSUE THREAD

**Issue by luizguilhermefr** [facebook/fresco#2274] opened 2019-01-19 13:35 UTC
### Description

When I build my app in debug mode or release mode APK, it works normally and images get loaded. Both in emulator and physical device.

When I build with [Android App Bundle](https://developer.android.com/platform/technology/app-bundle/), the images do not load, although the drawable placeholders do.

### Reproduction

I am using nothing too specific.

In my app's build.gradle:

```gradle
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
    debug {
        //
    }
}
```

Layout:

```xml
<com.facebook.drawee.view.SimpleDraweeView
  android:id="@+id/image_cover"
  android:layout_width="100dp"
  android:layout_height="100dp"
  android:layout_gravity="center"
  android:layout_margin="10dp"
  android:scaleType="fitCenter"
  fresco:placeholderImage="@drawable/ic_logo_focus"
  fresco:placeholderImageScaleType="fitCenter" />
```

To load an image:

```java
String url = "..."; // The image is not big
SimpleDraweeView cover = itemView.findViewById(R.id.image_cover);
cover.setImageURI(url);
```

### Additional Information

* Fresco version: `com.facebook.fresco:fresco:1.11.0`
* Platform version: No specific device, tested on Android Oreo

**Comment by oprisnik** [comment] 2019-01-21 16:10
Hey!

This seems to be a duplicate of #2253. Please take a look at that issue for the workaround.

**Closed by oprisnik** 2019-01-21 16:10 UTC
