### ISSUE TITLE
NullPointerException on Initialization

### ISSUE THREAD

**Issue by nbortolussi** [facebook/fresco#1515] opened 2016-10-27 14:32 UTC
Seems like I am getting a NullPointerException while initializing in my application class.

`Caused by java.lang.NullPointerException
       at android.app.ContextImpl.getAssets(ContextImpl.java:994)
       at android.content.ContextWrapper.getAssets(ContextWrapper.java:88)
       at com.facebook.imagepipeline.core.ProducerFactory.<init>(ProducerFactory.java:111)
       at com.facebook.imagepipeline.core.ImagePipelineFactory.getProducerFactory(ImagePipelineFactory.java:331)
       at com.facebook.imagepipeline.core.ImagePipelineFactory.getProducerSequenceFactory(ImagePipelineFactory.java:340)
       at com.facebook.imagepipeline.core.ImagePipelineFactory.getImagePipeline(ImagePipelineFactory.java:232)
       at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:48)
       at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:40)
       at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:34)
       at com.facebook.drawee.backends.pipeline.Fresco.initializeDrawee(Fresco.java:43)
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:33)
       at com.winering.wine.tools.WineRing.onCreate(WineRing.java:27)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
       at android.app.LoadedApk.makeApplication(LoadedApk.java:526)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2553)
       at android.app.ActivityThread.access$1800(ActivityThread.java:169)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5487)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)`

The crash was reported via Crashlytics on device SPH-L710T and Android version 4.4.2. My app is targeting SDK version 25 and is using Fresco 0.11.0.

**Comment by kirwan** [comment] 2016-11-01 13:03
This looks like a duplicate of of issue #434 so I suggest checking the suggestions there.

The exception is within `ContextImpl` in the Android framework, so looking at the cause of the exception there might also help. It seems [`getAssets()` only calls `getResources().getAssets()`](https://android.googlesource.com/platform/frameworks/base/+/android-4.4.2_r2/core/java/android/app/ContextImpl.java) so assuming you're initializing after calling the application's `super.onCreate()` I don't see why that should happen.

I can think of a work-around though, to lazily load the asset manager so we could look at including that in a future release.

**Closed by kirwan** 2016-11-01 13:03 UTC
