### ISSUE TITLE
In some case always get  "Problem decoding into existing bitmap"

### ISSUE THREAD

**Issue by martin90s** [facebook/fresco#1204] opened 2016-05-12 02:29 UTC
When i try to use SimpleDraweeView.setUri to set a local png file to view.
There's some probability that always get  Problem decoding into existing bitmap
it only occurs when two SimpleDrawwView load same file;
my version is 0.10
![e1578611-a9a6-4e88-85cb-1414571dfaa8](https://cloud.githubusercontent.com/assets/1409727/15202388/603a3c34-182c-11e6-8f73-925715cf5a80.png)

**Comment by plamenko** [comment] 2016-05-17 16:25
Instead of screenshot, can you please provide this log in a textual format? Can you also give us more context on what oyu have to do in order to reproduce this issue?

**Comment by Presleyzheng** [comment] 2017-06-20 01:36
@plamenko I get this error on version 1.3.0, and it's OK on version 0.14.1.
The log of **first time** to load the uri.
```java
06-20 09:33:16.218 31330-31330/com.llymobile.pt V/unknown:AbstractDraweeController: controller f58a443 null -> 22: initialize
06-20 09:33:16.218 31330-31330/com.llymobile.pt V/unknown:AbstractDraweeController: controller f58a443 22: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@99c8ac0
06-20 09:33:16.249 31330-31330/com.llymobile.pt V/unknown:AbstractDraweeController: controller f58a443 22 -> 23: initialize
06-20 09:33:16.249 31330-31330/com.llymobile.pt V/unknown:AbstractDraweeController: controller f58a443 23: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@99c8ac0
06-20 09:33:16.249 31330-31330/com.llymobile.pt V/unknown:AbstractDraweeController: controller f58a443 23: onAttach: request needs submit
06-20 09:33:16.249 31330-31330/com.llymobile.pt V/unknown:PipelineDraweeController: controller f58a443: getDataSource
06-20 09:33:16.249 31330-31330/com.llymobile.pt V/unknown:RequestLoggingListener: time 43533466: onRequestSubmit: {requestId: 18, callerContext: null, isPrefetch: false}
06-20 09:33:16.249 31330-31330/com.llymobile.pt V/unknown:RequestLoggingListener: time 43533466: onProducerStart: {requestId: 18, producer: BitmapMemoryCacheGetProducer}
06-20 09:33:16.249 31330-31330/com.llymobile.pt V/unknown:RequestLoggingListener: time 43533466: onProducerFinishWithSuccess: {requestId: 18, producer: BitmapMemoryCacheGetProducer, elapsedTime: 0 ms, extraMap: {cached_value_found=false}}
06-20 09:33:16.249 31330-31330/com.llymobile.pt V/unknown:RequestLoggingListener: time 43533466: onProducerStart: {requestId: 18, producer: BackgroundThreadHandoffProducer}
06-20 09:33:16.249 31330-31677/com.llymobile.pt V/unknown:RequestLoggingListener: time 43533466: onProducerFinishWithSuccess: {requestId: 18, producer: BackgroundThreadHandoffProducer, elapsedTime: 0 ms, extraMap: null}
06-20 09:33:16.250 31330-31330/com.llymobile.pt V/unknown:AbstractDraweeController: controller f58a443 23: submitRequest: dataSource: e087f3e
06-20 09:33:16.250 31330-31677/com.llymobile.pt V/unknown:RequestLoggingListener: time 43533466: onProducerStart: {requestId: 18, producer: BitmapMemoryCacheProducer}
06-20 09:33:16.250 31330-31677/com.llymobile.pt V/unknown:RequestLoggingListener: time 43533467: onProducerFinishWithSuccess: {requestId: 18, producer: BitmapMemoryCacheProducer, elapsedTime: 1 ms, extraMap: {cached_value_found=false}}
06-20 09:33:16.250 31330-31677/com.llymobile.pt V/unknown:RequestLoggingListener: time 43533467: onProducerStart: {requestId: 18, producer: EncodedMemoryCacheProducer}
06-20 09:33:16.251 31330-31677/com.llymobile.pt V/unknown:RequestLoggingListener: time 43533467: onProducerFinishWithSuccess: {requestId: 18, producer: EncodedMemoryCacheProducer, elapsedTime: 0 ms, extraMap: {cached_value_found=false}}
06-20 09:33:16.251 31330-31677/com.llymobile.pt V/unknown:RequestLoggingListener: time 43533468: onProducerStart: {requestId: 18, producer: DiskCacheProducer}
06-20 09:33:16.251 31330-31679/com.llymobile.pt V/unknown:BufferedDiskCache: Did not find image for https://oss/guidance/20170619/65977889560548038d83149118afb80e.png in staging area
06-20 09:33:16.252 31330-31679/com.llymobile.pt V/unknown:BufferedDiskCache: Disk cache read for https://oss/guidance/20170619/65977889560548038d83149118afb80e.png
06-20 09:33:16.252 31330-31679/com.llymobile.pt V/unknown:BufferedDiskCache: Disk cache miss for https://oss/guidance/20170619/65977889560548038d83149118afb80e.png
06-20 09:33:16.252 31330-31677/com.llymobile.pt V/unknown:RequestLoggingListener: time 43533469: onProducerFinishWithSuccess: {requestId: 18, producer: DiskCacheProducer, elapsedTime: 1 ms, extraMap: {cached_value_found=false}}
06-20 09:33:16.252 31330-31677/com.llymobile.pt V/unknown:RequestLoggingListener: time 43533469: onProducerStart: {requestId: 18, producer: NetworkFetchProducer}
06-20 09:33:16.254 31330-31330/com.llymobile.pt V/unknown:AbstractDraweeController: controller 1bda6b5 null -> 24: initialize
06-20 09:33:16.254 31330-31330/com.llymobile.pt V/unknown:AbstractDraweeController: controller 1bda6b5 24: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@b89514a
06-20 09:33:16.274 31330-31330/com.llymobile.pt V/unknown:AbstractDraweeController: controller 1bda6b5 24 -> 25: initialize
06-20 09:33:16.275 31330-31330/com.llymobile.pt V/unknown:AbstractDraweeController: controller 1bda6b5 25: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@b89514a
06-20 09:33:16.275 31330-31330/com.llymobile.pt V/unknown:AbstractDraweeController: controller 1bda6b5 25: onAttach: request needs submit
06-20 09:33:16.275 31330-31330/com.llymobile.pt V/unknown:PipelineDraweeController: controller 1bda6b5: getDataSource
06-20 09:33:16.275 31330-31330/com.llymobile.pt V/unknown:RequestLoggingListener: time 43533492: onRequestSubmit: {requestId: 19, callerContext: null, isPrefetch: false}
06-20 09:33:16.275 31330-31330/com.llymobile.pt V/unknown:RequestLoggingListener: time 43533492: onProducerStart: {requestId: 19, producer: BitmapMemoryCacheGetProducer}
06-20 09:33:16.275 31330-31330/com.llymobile.pt V/unknown:RequestLoggingListener: time 43533492: onProducerFinishWithSuccess: {requestId: 19, producer: BitmapMemoryCacheGetProducer, elapsedTime: 0 ms, extraMap: {cached_value_found=false}}
06-20 09:33:16.275 31330-31330/com.llymobile.pt V/unknown:RequestLoggingListener: time 43533492: onProducerStart: {requestId: 19, producer: BackgroundThreadHandoffProducer}
06-20 09:33:16.275 31330-31330/com.llymobile.pt V/unknown:AbstractDraweeController: controller 1bda6b5 25: submitRequest: dataSource: 97858bb
06-20 09:33:16.276 31330-31330/com.llymobile.pt V/unknown:AbstractDraweeController: controller 1bda6b5 25: onDetach
06-20 09:33:16.283 31330-31330/com.llymobile.pt V/unknown:RequestLoggingListener: time 43533500: onRequestCancellation: {requestId: 19, elapsedTime: 8 ms}
06-20 09:33:16.283 31330-31330/com.llymobile.pt V/unknown:RequestLoggingListener: time 43533500: onProducerFinishWithCancellation: {requestId: 19, stage: BackgroundThreadHandoffProducer, elapsedTime: 8 ms, extraMap: null}
06-20 09:33:17.233 31330-5998/com.llymobile.pt V/unknown:NativeMemoryChunkPool: Used = (14, 1927168); Free = (1, 1048576)
06-20 09:33:17.233 31330-5998/com.llymobile.pt V/unknown:NativeMemoryChunkPool: get (alloc) (object, size) = (c4a9d69, 262144)
06-20 09:33:17.234 31330-5998/com.llymobile.pt V/unknown:GenericByteArrayPool: Used = (1, 16384); Free = (4, 65536)
06-20 09:33:17.234 31330-5998/com.llymobile.pt V/unknown:GenericByteArrayPool: get (reuse) (object, size) = (2202e71, 16384)
06-20 09:33:17.234 31330-5998/com.llymobile.pt V/unknown:RequestLoggingListener: time 43534451: onProducerEvent: {requestId: 18, stage: NetworkFetchProducer, eventName: intermediate_result; elapsedTime: 982 ms}
06-20 09:33:17.236 31330-31714/com.llymobile.pt V/unknown:DownsampleUtil: Downsample - Specified size: 240x240, image size: 1080x1920 ratio: 0.2 x 0.1, ratio: 0.222 for https://oss/guidance/20170619/65977889560548038d83149118afb80e.png
06-20 09:33:17.236 31330-31714/com.llymobile.pt V/unknown:RequestLoggingListener: time 43534453: onProducerStart: {requestId: 18, producer: DecodeProducer}
06-20 09:33:17.237 31330-31714/com.llymobile.pt V/unknown:BitmapPool: Used = (11, 11889476); Free = (0, 0)
06-20 09:33:17.237 31330-31714/com.llymobile.pt V/unknown:BitmapPool: get (alloc) (object, size) = (f99d08f, 518400)
06-20 09:33:17.238 31330-31714/com.llymobile.pt V/unknown:BitmapPool: release (free) (object, size) = (f99d08f, 518400)
06-20 09:33:17.238 31330-31714/com.llymobile.pt V/unknown:BitmapPool: Used = (10, 11371076); Free = (0, 0)
06-20 09:33:17.239 31330-31714/com.llymobile.pt W/unknown:RequestLoggingListener: time 43534455: onProducerFinishWithFailure: {requestId: 18, stage: DecodeProducer, elapsedTime: 2 ms, extraMap: {sampleSize=4, hasGoodQuality=true, imageFormat=PNG, isFinal=false, encodedImageSize=1080x1920, queueTime=1, requestedImageSize=240x240}, throwable: java.lang.IllegalArgumentException: Problem decoding into existing bitmap}
06-20 09:33:17.239 31330-31714/com.llymobile.pt W/unknown:RequestLoggingListener: time 43534455: onRequestFailure: {requestId: 18, elapsedTime: 989 ms, throwable: java.lang.IllegalArgumentException: Problem decoding into existing bitmap}
06-20 09:33:17.239 31330-31330/com.llymobile.pt V/unknown:AbstractDraweeController: controller f58a443 23: final_failed @ onFailure: failure: java.lang.IllegalArgumentException: Problem decoding into existing bitmap
06-20 09:33:17.524 31330-5998/com.llymobile.pt V/unknown:RequestLoggingListener: time 43534741: onProducerEvent: {requestId: 18, stage: NetworkFetchProducer, eventName: intermediate_result; elapsedTime: 1272 ms}
06-20 09:33:17.526 31330-31715/com.llymobile.pt V/unknown:DownsampleUtil: Downsample - Specified size: 240x240, image size: 1080x1920 ratio: 0.2 x 0.1, ratio: 0.222 for https://oss/guidance/20170619/65977889560548038d83149118afb80e.png
06-20 09:33:17.707 31330-5998/com.llymobile.pt V/unknown:RequestLoggingListener: time 43534923: onProducerEvent: {requestId: 18, stage: NetworkFetchProducer, eventName: intermediate_result; elapsedTime: 1454 ms}
06-20 09:33:17.710 31330-31704/com.llymobile.pt V/unknown:DownsampleUtil: Downsample - Specified size: 240x240, image size: 1080x1920 ratio: 0.2 x 0.1, ratio: 0.222 for https://oss/guidance/20170619/65977889560548038d83149118afb80e.png
06-20 09:33:17.808 31330-5998/com.llymobile.pt V/unknown:RequestLoggingListener: time 43535025: onProducerEvent: {requestId: 18, stage: NetworkFetchProducer, eventName: intermediate_result; elapsedTime: 1556 ms}
06-20 09:33:17.810 31330-31703/com.llymobile.pt V/unknown:DownsampleUtil: Downsample - Specified size: 240x240, image size: 1080x1920 ratio: 0.2 x 0.1, ratio: 0.222 for https://oss/guidance/20170619/65977889560548038d83149118afb80e.png
06-20 09:33:17.810 31330-5998/com.llymobile.pt V/unknown:RequestLoggingListener: time 43535027: onProducerFinishWithSuccess: {requestId: 18, producer: NetworkFetchProducer, elapsedTime: 1558 ms, extraMap: {fetch_time=578, queue_time=980, image_size=168863, total_time=1558}}
06-20 09:33:17.811 31330-5998/com.llymobile.pt V/unknown:RequestLoggingListener: time 43535027: onUltimateProducerReached: {requestId: 18, producer: NetworkFetchProducer, elapsedTime: -1 ms, success: true}
06-20 09:33:17.811 31330-5998/com.llymobile.pt V/unknown:StagingArea: Count = 1
06-20 09:33:17.812 31330-31678/com.llymobile.pt V/unknown:BufferedDiskCache: About to write to disk-cache for key https://oss/guidance/20170619/65977889560548038d83149118afb80e.png
06-20 09:33:17.812 31330-5998/com.llymobile.pt V/unknown:GenericByteArrayPool: release (reuse) (object, size) = (2202e71, 16384)
06-20 09:33:17.812 31330-5998/com.llymobile.pt V/unknown:GenericByteArrayPool: Used = (0, 0); Free = (5, 81920)
06-20 09:33:17.814 31330-31678/com.llymobile.pt V/unknown:GenericByteArrayPool: Used = (1, 16384); Free = (4, 65536)
06-20 09:33:17.814 31330-31678/com.llymobile.pt V/unknown:GenericByteArrayPool: get (reuse) (object, size) = (2a099eb, 16384)
06-20 09:33:17.815 31330-31678/com.llymobile.pt V/unknown:GenericByteArrayPool: release (reuse) (object, size) = (2a099eb, 16384)
06-20 09:33:17.816 31330-31678/com.llymobile.pt V/unknown:GenericByteArrayPool: Used = (0, 0); Free = (5, 81920)
06-20 09:33:17.816 31330-31678/com.llymobile.pt V/unknown:BufferedDiskCache: Successful disk-cache write for key https://oss/guidance/20170619/65977889560548038d83149118afb80e.png
06-20 09:33:17.816 31330-31678/com.llymobile.pt V/unknown:StagingArea: Count = 0
06-20 09:33:17.911 31330-31701/com.llymobile.pt V/unknown:DownsampleUtil: Downsample - Specified size: 240x240, image size: 1080x1920 ratio: 0.2 x 0.1, ratio: 0.222 for https://oss/guidance/20170619/65977889560548038d83149118afb80e.png
```
Log of the next time to load the uri.
```java
06-20 09:35:57.127 31330-31330/com.llymobile.pt V/unknown:AbstractDraweeController: controller f0a6157 null -> 26: initialize
06-20 09:35:57.128 31330-31330/com.llymobile.pt V/unknown:AbstractDraweeController: controller f0a6157 26: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@15e2444
06-20 09:35:57.150 31330-31330/com.llymobile.pt V/unknown:AbstractDraweeController: controller f0a6157 26 -> 27: initialize
06-20 09:35:57.150 31330-31330/com.llymobile.pt V/unknown:AbstractDraweeController: controller f0a6157 27: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@15e2444
06-20 09:35:57.150 31330-31330/com.llymobile.pt V/unknown:AbstractDraweeController: controller f0a6157 27: onAttach: request needs submit
06-20 09:35:57.150 31330-31330/com.llymobile.pt V/unknown:PipelineDraweeController: controller f0a6157: getDataSource
06-20 09:35:57.150 31330-31330/com.llymobile.pt V/unknown:RequestLoggingListener: time 43694367: onRequestSubmit: {requestId: 20, callerContext: null, isPrefetch: false}
06-20 09:35:57.150 31330-31330/com.llymobile.pt V/unknown:RequestLoggingListener: time 43694367: onProducerStart: {requestId: 20, producer: BitmapMemoryCacheGetProducer}
06-20 09:35:57.150 31330-31330/com.llymobile.pt V/unknown:RequestLoggingListener: time 43694367: onProducerFinishWithSuccess: {requestId: 20, producer: BitmapMemoryCacheGetProducer, elapsedTime: 0 ms, extraMap: {cached_value_found=false}}
06-20 09:35:57.150 31330-31330/com.llymobile.pt V/unknown:RequestLoggingListener: time 43694367: onProducerStart: {requestId: 20, producer: BackgroundThreadHandoffProducer}
06-20 09:35:57.151 31330-31677/com.llymobile.pt V/unknown:RequestLoggingListener: time 43694367: onProducerFinishWithSuccess: {requestId: 20, producer: BackgroundThreadHandoffProducer, elapsedTime: 0 ms, extraMap: null}
06-20 09:35:57.151 31330-31330/com.llymobile.pt V/unknown:AbstractDraweeController: controller f0a6157 27: submitRequest: dataSource: 51de62
06-20 09:35:57.151 31330-31677/com.llymobile.pt V/unknown:RequestLoggingListener: time 43694367: onProducerStart: {requestId: 20, producer: BitmapMemoryCacheProducer}
06-20 09:35:57.151 31330-31677/com.llymobile.pt V/unknown:RequestLoggingListener: time 43694368: onProducerFinishWithSuccess: {requestId: 20, producer: BitmapMemoryCacheProducer, elapsedTime: 1 ms, extraMap: {cached_value_found=false}}
06-20 09:35:57.151 31330-31677/com.llymobile.pt V/unknown:RequestLoggingListener: time 43694368: onProducerStart: {requestId: 20, producer: EncodedMemoryCacheProducer}
06-20 09:35:57.152 31330-31677/com.llymobile.pt V/unknown:RequestLoggingListener: time 43694368: onProducerFinishWithSuccess: {requestId: 20, producer: EncodedMemoryCacheProducer, elapsedTime: 0 ms, extraMap: {cached_value_found=true}}
06-20 09:35:57.152 31330-31677/com.llymobile.pt V/unknown:RequestLoggingListener: time 43694368: onUltimateProducerReached: {requestId: 20, producer: EncodedMemoryCacheProducer, elapsedTime: -1 ms, success: true}
06-20 09:35:57.153 31330-31702/com.llymobile.pt V/unknown:DownsampleUtil: Downsample - Specified size: 240x240, image size: 1080x1920 ratio: 0.2 x 0.1, ratio: 0.222 for https://oss/guidance/20170619/65977889560548038d83149118afb80e.png
06-20 09:35:57.153 31330-31702/com.llymobile.pt V/unknown:RequestLoggingListener: time 43694369: onProducerStart: {requestId: 20, producer: DecodeProducer}
06-20 09:35:57.154 31330-31702/com.llymobile.pt V/unknown:BitmapPool: Used = (11, 11889476); Free = (0, 0)
06-20 09:35:57.154 31330-31702/com.llymobile.pt V/unknown:BitmapPool: get (alloc) (object, size) = (33b40b0, 518400)
06-20 09:35:57.155 31330-31330/com.llymobile.pt V/unknown:AbstractDraweeController: controller 6105b29 null -> 28: initialize
06-20 09:35:57.155 31330-31330/com.llymobile.pt V/unknown:AbstractDraweeController: controller 6105b29 28: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@b737eae
06-20 09:35:57.205 31330-31702/com.llymobile.pt V/unknown:RequestLoggingListener: time 43694421: onProducerFinishWithSuccess: {requestId: 20, producer: DecodeProducer, elapsedTime: 52 ms, extraMap: {sampleSize=4, hasGoodQuality=true, imageFormat=PNG, isFinal=true, encodedImageSize=1080x1920, queueTime=0, requestedImageSize=240x240, bitmapSize=270x480}}
06-20 09:35:57.205 31330-31702/com.llymobile.pt V/unknown:RequestLoggingListener: time 43694422: onRequestSuccess: {requestId: 20, elapsedTime: 55 ms}
06-20 09:35:57.205 31330-31330/com.llymobile.pt V/unknown:AbstractDraweeController: controller f0a6157 27: set_final_result @ onNewResult: image: CloseableReferenceWithFinalizer 95a244f
```

**Comment by Presleyzheng** [comment] 2017-06-20 07:30
bug with PNG with [this line](https://github.com/facebook/fresco/blob/master/imagepipeline/src/main/java/com/facebook/imagepipeline/producers/DecodeProducer.java#L432)

If image formated with PNG and an intermediate_result of NetworkProducer will cause [BitmapFactory.decode](https://github.com/android/platform_frameworks_base/blob/master/graphics/java/android/graphics/BitmapFactory.java#L626) throw exception and [mIsFinished](https://github.com/facebook/fresco/blob/master/imagepipeline/src/main/java/com/facebook/imagepipeline/producers/DecodeProducer.java#L120) be set true, and the final image will not be decode to show on the first time to load from NetworkProducer.

**Comment by mawanli9843** [comment] 2017-06-27 13:03
@Presleyzheng I got same error as you , do you have any solution?

**Comment by Presleyzheng** [comment] 2017-06-28 10:16
@mawanli9843 it's not a bug. so embarrassed! just sure your config for request ProgressiveRenderingEnabled must be false for PNG request. the reason of the problem is the submit change ["Fix media variations with non-jpeg images"](https://github.com/facebook/fresco/blob/master/imagepipeline/src/main/java/com/facebook/imagepipeline/producers/DecodeProducer.java#L432)

**Comment by erikandre** [comment] 2018-01-18 17:28
Closing as this seems to be resolved

**Closed by erikandre** 2018-01-18 17:28 UTC
Labels: bug

**Comment by xiaochenu** [comment] 2019-07-17 04:10
request.setProgressiveRenderingEnabled(false) not work for me..
