### ISSUE TITLE
Class Not Found Error: DiskCacheProducer$1

### ISSUE THREAD

**Issue by ICECHN** [facebook/fresco#109] opened 2015-04-08 06:33 UTC
Error Info:
java.lang.NoClassDefFoundError: com.facebook.imagepipeline.producers.DiskCacheProducer$1
at com.facebook.imagepipeline.producers.DiskCacheProducer.produceResults(DiskCacheProducer.java:76)
            at com.facebook.imagepipeline.producers.MemoryCacheProducer.produceResults(MemoryCacheProducer.java:114)
            at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.startNextProducerIfHasAttachedConsumers(MultiplexProducer.java:362)
            at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.access$000(MultiplexProducer.java:121)
            at com.facebook.imagepipeline.producers.MultiplexProducer.produceResults(MultiplexProducer.java:85)
            at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer.produceResults(AddImageTransformMetaDataProducer.java:41)
            at com.facebook.imagepipeline.producers.ImageTransformProducer.produceResults(ImageTransformProducer.java:53)
            at com.facebook.imagepipeline.producers.RemoveImageTransformMetaDataProducer.produceResults(RemoveImageTransformMetaDataProducer.java:37)
            at com.facebook.imagepipeline.producers.DecodeProducer.produceResults(DecodeProducer.java:88)
            at com.facebook.imagepipeline.producers.MemoryCacheProducer.produceResults(MemoryCacheProducer.java:114)
            at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.startNextProducerIfHasAttachedConsumers(MultiplexProducer.java:362)
            at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.access$000(MultiplexProducer.java:121)
            at com.facebook.imagepipeline.producers.MultiplexProducer.produceResults(MultiplexProducer.java:85)
            at com.facebook.imagepipeline.producers.ThreadHandoffProducer$1.onSuccess(ThreadHandoffProducer.java:45)
            at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:54)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)

**Comment by IanChilds** [comment] 2015-04-08 08:35
Duplicate of #82

**Closed by IanChilds** 2015-04-08 08:35 UTC
