### ISSUE TITLE
HTTP errors are stored in cache

### ISSUE THREAD

**Issue by xjy2061** [facebook/fresco#675] opened 2015-10-21 03:26 UTC
When connect to a need need authenticate wifi, the response of image request is a html for login, and the html was cached to disk, after that load the image will get from disk cache, but the cache file is not a bitmap file, then the image show nothing, even connect to another wifi does not need authenticate.

**Comment by michalgr** [comment] 2015-10-21 12:14
Thank you for reporting.

**Comment by defHLT** [comment] 2018-07-09 15:59
Duplicate of #1413

**Closed by defHLT** 2018-07-09 15:59 UTC
Labels: bug
