### ISSUE TITLE
Unable to execute dex: method ID not in [0, 0xffff]: 65536

### ISSUE THREAD

**Issue by jehad-suliman** [facebook/fresco#368] opened 2015-06-11 11:48 UTC
Iam Working With Eclipse 

Fresco is too large to use

**Comment by ianrumac** [comment] 2015-06-11 17:12
You've reached the 65k dex method limit.
Split it into multidex, or check your libraries, this is not Fresco related.

**Comment by tyronen** [comment] 2015-06-12 12:30
A case can be made that Fresco is too large, but that is a duplicate of #260.

**Closed by tyronen** 2015-06-12 12:30 UTC
Labels: duplicate
