### ISSUE TITLE
com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary error

### ISSUE THREAD

**Issue by chonamdoo** [facebook/fresco#1336] opened 2016-07-04 04:10 UTC
i use 0.10.0

compile 'com.facebook.fresco:fresco:0.10.0@aar'
    compile 'com.facebook.fresco:drawee:0.10.0@aar'
    compile 'com.facebook.fresco:fbcore:0.10.0@aar'
    compile 'com.facebook.fresco:imagepipeline:0.10.0@aar'
    compile group: 'com.facebook.fresco', name: 'imagepipeline-okhttp3', version: '0.10.0'

http://crashes.to/s/47cbe863a3c

**Comment by massimocarli** [comment] 2016-07-04 15:30
Hi @chonamdoo,
please try the solution [here](https://github.com/facebook/fresco/issues/410)

**Comment by chonamdoo** [comment] 2016-07-05 06:33
hi @massimocarli 
try this?

compile('com.facebook.fresco:fresco:0.9.0+') { exclude module: 'bolts-android' } compile('com.facebook.fresco:imagepipeline-okhttp:0.9.0+') { exclude module: 'bolts-android' } compile('jp.wasabeef:fresco-processors:2.0.0') { exclude module: 'bolts-android' }

**Comment by massimocarli** [comment] 2016-07-05 10:02
Hi @chonamdoo,
I meant [this](https://github.com/facebook/fresco/issues/933#issuecomment-186266187) the usage if  [Relinker](https://github.com/KeepSafe/ReLinker) library in SoLoaderShim with Relinker.findLibrary() instead of System.findLibrary()

**Comment by chonamdoo** [comment] 2016-07-06 09:02
hi @massimocarli 

I tried as you advised but still having the same error. Is there anything else I can do?

**Comment by massimocarli** [comment] 2016-08-25 13:36
Hi @chonamdoo,
have you tried with the 0.13.0?
Thanks

**Comment by jmbusby** [comment] 2016-08-25 16:52
FWIW we were having a lot of similar errors, and applying the [solution](https://github.com/facebook/fresco/issues/933#issuecomment-186266187) suggested by @massimocarli fixed it for us. We are using Fresco v0.11.

**Comment by oprisnik** [comment] 2018-01-19 19:35
WIth 1.8.0, we made SoLoader the new default, so this should be fixed.

**Closed by oprisnik** 2018-01-19 19:35 UTC
Labels: bug

**Comment by lytefast** [comment] 2018-01-27 20:43
I'm still seeing this error:
```
Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libimagepipeline.so
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:522)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:420)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:370)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:335)
       at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:42)
       at com.facebook.imagepipeline.memory.NativeMemoryChunk.(NativeMemoryChunk.java:33)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:20)
       at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:257)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.(NativePooledByteBufferOutputStream.java:51)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:98)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:26)
       at com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(BufferedDiskCache.java:336)
       at com.facebook.imagepipeline.cache.BufferedDiskCache.access$100(BufferedDiskCache.java:36)
       at com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(BufferedDiskCache.java:182)
       at com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(BufferedDiskCache.java:166)
       at bolts.Task$4.run(Task.java:357)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:53)
       at java.lang.Thread.run(Thread.java:761)
```

**Comment by Anilugale** [comment] 2018-02-16 08:09
02-16 12:24:43.130 24662-25534/com.ms.engage E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                               Process: com.ms.engage, PID: 24662
                                                               java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/common/soloader/SoLoaderShim$Handler;
                                                                   at com.facebook.react.shell.MainReactPackage$8.get(MainReactPackage.java:149)
                                                                   at com.facebook.react.shell.MainReactPackage$8.get(MainReactPackage.java:146)
                                                                   at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:81)
                                                                   at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
                                                                   at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1071)
                                                                   at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1042)
                                                                   at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:980)
                                                                   at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:109)
                                                                   at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:802)
                                                                   at java.lang.Thread.run(Thread.java:761)
                                                                Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.common.soloader.SoLoaderShim$Handler" on path: DexPathList[[zip file "/data/app/com.ms.engage-2/base.apk", zip file "/data/app/com.ms.engage-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.ms.engage-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.ms.engage-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.ms.engage-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.ms.engage-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.ms.engage-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.ms.engage-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.ms.engage-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.ms.engage-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.ms.engage-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.ms.engage-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.ms.engage-2/lib/arm, /system/fake-libs, /data/app/com.ms.engage-2/base.apk!/lib/armeabi-v7a, /data/app/com.ms.engage-2/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/com.ms.engage-2/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/com.ms.engage-2/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/com.ms.engage-2/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/com.ms.engage-2/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/com.ms.engage-2/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/com.ms.engage-2/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/com.ms.engage-2/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/com.ms.engage-2/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/com.ms.engage-2/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/com.ms.engage-2/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                                                                   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                   at com.facebook.react.shell.MainReactPackage$8.get(MainReactPackage.java:149) 
                                                                   at com.facebook.react.shell.MainReactPackage$8.get(MainReactPackage.java:146) 
                                                                   at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:81) 
                                                                   at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106) 
                                                                   at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1071) 
                                                                   at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1042) 
                                                                   at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:980) 
                                                                   at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:109) 
                                                                   at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:802) 
                                                                   at java.lang.Thread.run(Thread.java:761)

**Comment by lambdapioneer** [comment] 2018-02-16 10:53
Hi @Anilugale,

we have fixed the `NoClassDefFoundError` in the 1.8.1 release after it has been found in the 1.8.0 release. Updating to that version number should fix the issue. We are sorry for the inconvenience.

**Comment by Anilugale** [comment] 2018-02-16 11:13
@lambdapioneer still got same error after updating fresco lib v 1.8.1. thanks for the reply

**Comment by lambdapioneer** [comment] 2018-02-16 11:22
Oh, just seeing that your are loading Fresco as part of React?

Can you maybe create a new issue (as this seems to be different from the original issue in this thread) and provide the information asked for in the issue template? :) that will allow us to narrow down the issue that you are experiencing :) Especially, the content of your `build.gradle` file would be interesting
