### ISSUE TITLE
java.lang.InternalError: Thread starting during runtime shutdown

### ISSUE THREAD

**Issue by zhouminghai** [facebook/fresco#1764] opened 2017-05-12 03:25 UTC
Our project often appears this bug "Thread starting during runtime shutdown" , It appears at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)  

  public Thread newThread(final Runnable runnable) {
    Runnable wrapperRunnable = new Runnable() {
      @Override
      public void run() {
        try {
          Process.setThreadPriority(mThreadPriority);
        } catch (Throwable t) {
          // just to be safe
        }
        runnable.run();
      }
    };
    return new Thread(wrapperRunnable);
  }

}
can you help me to resolve this bug?

**Comment by foghina** [comment] 2017-05-12 16:16
Duplicate of #1144.

**Closed by foghina** 2017-05-12 16:16 UTC
