### ISSUE TITLE
Scaling on nexus 6 (false xxxhdpi)

### ISSUE THREAD

**Issue by mappy-mobile** [facebook/fresco#1699] opened 2017-03-14 13:34 UTC
Hello,

I use fresco to download icon. Icon are not correctly scaled on nexus 6. 
My 192*192 icon from url should be scale to 168*168 (nexus 6 is 560 dpi).

Maybe i'm missing something in imageRequest parameter.

`    ImageRequest imageRequest = ImageRequestBuilder
                .newBuilderWithSource(builder.mUri)
                .setLocalThumbnailPreviewsEnabled(true)
                .setLowestPermittedRequestLevel(ImageRequest.RequestLevel.FULL_FETCH)
                .setProgressiveRenderingEnabled(false)
                .setResizeOptions(new ResizeOptions())
                .build();
        final ImagePipeline imagePipeline = Fresco.getImagePipeline();
        DataSource<CloseableReference<CloseableImage>> dataSource = imagePipeline.fetchDecodedImage(imageRequest, builder.mContext);
        builder.mListener.mUri = builder.mUri;`

* Fresco version: com.facebook.fresco:fresco:1.0.1
* Platform version: [nexus 6  android 6]

Note : same "image"(196*196) loaded using Drawable drawable = ContextCompat.getDrawable(mContext,R.drawable.image) works correctly (scale at 168 *168)

Thanks

**Comment by erikandre** [comment] 2017-03-14 14:28
Hi @mappy-mobile!

If you want Fresco to resize the image you need to pass in the desired width and height into the ResizeOptions(), like this:

```
int width = 50, height = 50;
ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
    .setResizeOptions(new ResizeOptions(width, height))
    .build();
```
More information about this can be found [here](http://frescolib.org/docs/resizing-rotating.html)

**Comment by mappy-mobile** [comment] 2017-03-14 14:54
Hi,

Thanks for your help. yes i've seen i can resize on the fly. What i mean is fresco should handle the resizing regarding the phone density. It works for devices with true density (the screen is exactly the density) but it doesn't work for hybrid density (ex : nexus 6 is 560dpi, it's in between xxhdpi and xxxhdpi). The image is resizing as a xxxhdpi density nexus 6 is not perfect xxxhdpi.

So do i need to apply myself the delta if the phone is not perfect density (there are a lot of devices in this case) ?

**Comment by erikandre** [comment] 2017-03-14 15:00
Yes. If you are using Fresco to load an remote image (not a local resource) we are not doing any kind of resizing if you don't specify it explicitly. It's not really related to the density of the device since that only applies if the image you are loading has associated information about what density it was designed for (as is the case for local resources like in the example you mention: `ContextCompat.getDrawable(mContext,R.drawable.image)`).

**Comment by oprisnik** [comment] 2017-03-15 10:33
An alternative if you're using a DraweeView is using a scale type (which should be fine if the image dimensions are similar): http://frescolib.org/docs/scaling.html

If the dimensions differ by a lot, you would ideally request different images with suitable dimensions from the server to reduce network usage (if the server image is larger) or/and use resizing as @erikandre  described.

**Comment by mappy-mobile** [comment] 2017-03-21 16:59
thanks @oprisnik for your answer.
I already use different image with suitable dimensions. 
If i understand correctly i need to find a way to calculate scale type for intermediate densities (nexus 6 is between xxhdpi and xxxhdpi) . Same with DraweeView i need to provide scale values if i understand correctly.

**Comment by oprisnik** [comment] 2017-03-21 23:14
I don't understand. You have a DraweeView on the client that is AxB dp wide. You then request an image from the server that is also AxB dp (converted to pixels) - so everything should be fine. If you only have larger images, you can supply resize options to resize the image.
If the image is too small or too large, you can also simply use a[ ScaleType](http://frescolib.org/docs/scaling.html) that suits your needs.

**Comment by erikandre** [comment] 2017-05-09 17:38
It is not clear what the issue is, so closing until more information is provided.

**Closed by erikandre** 2017-05-09 17:38 UTC
Labels: needs-details
