### ISSUE TITLE
Images are not appearing back in list view when switching between tabs

### ISSUE THREAD

**Issue by madkid66** [facebook/fresco#1000] opened 2016-02-17 20:26 UTC
We just started using Fresco in our app. The UI has different tabs with list views in each with an image (SimpleDrawee) in each cell. The initial load happens fine. But, when we switch between tabs and go to another screen and come back, some of the SimpleDrawees are not showing up on the screen. Please reply with any suggestions at the earliest. I am attaching the screenshot and the logs (verbose - as suggested on the Troubleshooting section of frescolib.org.
Thank you
![screenshot_2016-02-17-10-35-14](https://cloud.githubusercontent.com/assets/10780191/13123476/1fd1a1e4-d571-11e5-99b9-278cb1bb7ea4.png)
[logs.txt](https://github.com/facebook/fresco/files/135084/logs.txt)

**Comment by IanChilds** [comment] 2016-02-18 10:26
Does the image ever load? Is there just a delay or does it stay black? Also, if you scroll up and down does the image become visible?

**Comment by madkid66** [comment] 2016-02-18 18:22
Thank you IanChilds for the reply. I noticed that the images load first time (although few of them take time   ). But, the issue is when I switch between tabs or go to another screen (clicking the images takes to another screen) and return to the list, the images are blank. When I scroll up and down, the images appear back most of the time (although not always).

**Comment by madkid66** [comment] 2016-02-20 02:34
IanChilds,

Please help reply with any suggestions. We are seeing more of it. 
Thank you

![screenshot_2016-02-19-18-30-09](https://cloud.githubusercontent.com/assets/10780191/13193963/581e53fe-d737-11e5-9f31-7652a319243f.png)

**Comment by IanChilds** [comment] 2016-02-24 15:26
From your logs, it looks like the only errors are coming from `ChatterAndTweetsAdapter` - could that be relevant? 

Perhaps your cache is getting full? Are you holding onto a lot of images in other tabs that are not on the screen? Can you try increasing the size of the cache?

**Comment by madkid66** [comment] 2016-02-27 20:21
The messages related to ChatterAndTweetsAdapter are not related.
From the logs I see that certain images are going through 'clearImage' when not visible, but are not appearing back (and any associated log) when they are supposed to be visible again.

**Comment by michalgr** [comment] 2016-02-29 12:12
I wonder if all the drawee views get notification of being reattached. It might be worth looking at part of the logcat that correspond to "going back" to the affected tab. Could you please do this to get us more debugging data:
1. open any tab in your app and wait for all the images to show up
2. go to another tab and wait for all the images to show up
3. clear logcat (`adb logcat -c`)
4. start recording logcat
5. go back to the first tab
6. check that some images do not show up
7. make a screenshot

Having such screenshot and logcat output should allow us to check how many drawee views  were reattached, how many of them submitted image requests, how many of the request completed and how many images become visible after that.

**Comment by plamenko** [comment] 2016-03-09 22:45
I am seeing `controller 44198828 3: ignore_old_datasource @ onFailure: failure: java.lang.NullPointerException` in logs. Let me take a closer look.

**Comment by plamenko** [comment] 2016-03-09 22:53
Even if we are not getting `onAttach` event, as a fail-safe mechanism, we do reattach in `onDraw`. So I suspect something is clearing uri/controller or failure in the pipeline.

**Comment by plamenko** [comment] 2016-03-09 23:48
So I took a look at the log data in Excel and I can't see the issue. The problem is that the data looks pretty much normal. It would definitely help if you follow steps @michalgr suggested. That way we will have more interesting log, as the current one contains tons of valid data and is hard to spot anomalies.
[issue1000.xlsx](https://github.com/facebook/fresco/files/166297/issue1000.xlsx)
![screen shot 2016-03-09 at 23 44 48](https://cloud.githubusercontent.com/assets/3705123/13654642/6419f2d4-e651-11e5-8a98-6907ccdf001a.png)

**Comment by plamenko** [comment] 2016-03-09 23:54
Let me quickly explain the Excel data I made. I kept only lines containing "AbstractDraweeController". I sorted them by controller hash and then by time. Then on the right side I marked events of interest (initialize, set hierarchy, attach, submit, set_final, detach, release). You can observe that sequence of events look normal for each controller (at least for the first few I checked). The events of interest happen in correct order and with expected times between them.
The two lines I marked in red are suspicious because onDetach happened very quickly after the image has been shown. This can be expected if you changed tab just after the image loaded, but there is no way for me to tell if that was the case. If you could log each time you change tabs that would be super useful too.

**Comment by madkid66** [comment] 2016-03-11 20:49
Thank you plamenko for the messages. I will generate the logs and upload.

**Comment by tyronen** [comment] 2016-05-27 10:16
Are you still experiencing this?

**Comment by 9h0st** [comment] 2016-11-15 03:16
I also have some problem like this. My case is below:
1.  I go to Activity B from Activity A and the A has a simpleDraweeView loading image from web. 
the log:

`AbstractDraweeController: controller 9cca437 1747: onDetach`
`AbstractDraweeController: controller 9cca437 1747: release: image: CloseableReference 6691551`
2.  I go back to Activity A from Activity B using a swipe back gesture animation. The image in Activity A dismiss and the appear again for a little while.
the log:

`AbstractDraweeController: controller 9cca437 1747: onAttach: request needs submit`
`AbstractDraweeController: controller 9cca437 1747: set_final_result @ onNewResult: image: CloseableReference 6691551`

But this only happen to Android Nougat. Below Nougat, everything is OK, NO such log like above(No Detach and No Attach in this operate)

**Comment by lambdapioneer** [comment] 2016-11-15 12:56
Hi @9h0st, do you have a (minimal) example that reproduces the issue? If this happening only on Nougat, we would want to follow up on this (ideally in a new issue).

Thanks a lot, Daniel

**Comment by 9h0st** [comment] 2016-11-18 01:50
@lambdapioneer 
Hi Daniel, Thanks for your quick response.
I figure out why this happened. Because In SDK version 24 Google add new function onVisibilityAggregated, this function will make drawable change its visibility every time the activity change to the backstage. So RootDrawable will change its visibility and call DraweeHolder's onVisibilityChange back. That makes the Detach and Attach happen.

see this log [Add View#onVisibilityAggregated](https://android.googlesource.com/platform/frameworks/base/+/41d9690c3e3588dd273308279b9e609c2c6da3c7).

![screenshot](https://cloud.githubusercontent.com/assets/7588390/20415561/11bff548-ad74-11e6-93e2-3f5b6e848663.png)

I make a example for you to check the problem, see this repository [SlideBackDemoWithFresco](https://github.com/9h0st/SlideBack).

**Comment by erikandre** [comment] 2018-01-18 17:23
Closing due to lack of updates or further reports since 2016

**Closed by erikandre** 2018-01-18 17:23 UTC
Labels: needs-details

**Comment by twlkyao** [comment] 2019-04-16 10:23
This is introduced when your app is target Android N or above, I resolve by hooking the `RootDrawable#setVisible(boolean visible, boolean restart)` method, making the param `visibile` to `true`.
