### ISSUE TITLE
Using color resource id when setting placeholder image shares its state with wherever same color is used

### ISSUE THREAD

**Issue by raylee4204** [facebook/fresco#1709] opened 2017-03-22 23:01 UTC
I have an activity that has a grey background color set using getWindow(). setBackgroundDrawableResource(R.color.grey).

In another activity, I have Fresco loading a list of images from live photos taken from Camera Intent where its placeholder uses R.color.grey as well by the following:

GenericDraweeHierarchy hierarchy = imageView.getHierarchy();
hierarchy.setPlaceholderImage(R.color.grey);
imageView.setHierarchy(hierarchy);

For some reason, after live photos have been taken and loaded using Fresco, when I navigate back to the previous activity, the background color changes to black.

### Additional Information

* Fresco version: 1.1.0
* Platform version: Lollipop - Marshmallow. (Other versions not tested)

**Comment by massimocarli** [comment] 2017-04-19 10:02
Hi @raylee4204 ,
I don't think this is related to Fresco which, with what you say, into another Activity. Please double check when you invoke the 
`getWindow().setBackgroundColor(R.color.grey).`
code into the first activity. 
Thankx

**Comment by raylee4204** [comment] 2017-04-19 14:32
The activity has several fragments using viewpager, and each fragment triggers getActivity().getWindow().setBackgroundColor() as user swipes the viewpager to view one.

The fragments that use the grey color as the background are only affected.

**Comment by erikandre** [comment] 2017-04-25 15:23
Hi @raylee4204! Just to confirm something. If you remove this line:

`hierarchy.setPlaceholderImage(R.color.grey);`

Does the problem go away?

**Comment by raylee4204** [comment] 2017-04-25 15:25
Yeah, it does.

I've also tried hierarchy.setPlaceholderImage(ContextCompat.getColor(context, R.color.grey));

**Comment by erikandre** [comment] 2017-04-25 16:02
OK, then it's starting to make sense. I tried reproducing the problem myself but haven't succeeded yet. 

You mentioned that you are using getWindow().setBackgroundColor() from the activity. Do you mean getWindow().setBackgroundDrawableResource()? 

In any case, could you try setting the background color this way instead:

`setBackgroundDrawable(getResources().getDrawable(R.color. grey).mutate());`

**Comment by raylee4204** [comment] 2017-04-25 16:19
Sorry about that. 

`setBackgroundDrawableResource` is correct

**Comment by erikandre** [comment] 2017-07-10 16:51
Closing this as we've been unable to reproduce the issue.

**Closed by erikandre** 2017-07-10 16:51 UTC
