### ISSUE TITLE
Fresco 0.8.0 throw exception when build with proguard

### ISSUE THREAD

**Issue by kimkha** [facebook/fresco#698] opened 2015-10-26 11:01 UTC
The error is:
> Warning:com.facebook.imagepipeline.bitmaps.DalvikBitmapFactory: can't find referenced field 'android.graphics.Bitmap$Config BITMAP_CONFIG' in program class com.facebook.imagepipeline.nativecode.Bitmaps

When I extract the aar from http://mvnrepository.com/artifact/com.facebook.fresco/imagepipeline/0.8.0 and zip from https://github.com/facebook/fresco/releases/tag/v0.8.0. I can see com.facebook.imagepipeline.bitmaps.DalvikBitmapFactory in aar file, but NOT in zip file.

By the way, when I rollback to Fresco 0.7.0, everything is OK.

**Comment by emce** [comment] 2015-10-29 10:13
+1 - Same for me

**Comment by michalgr** [comment] 2015-10-29 12:48
duplicate of https://github.com/facebook/fresco/issues/681

**Closed by michalgr** 2015-10-29 12:48 UTC
