### ISSUE TITLE
Loading .WebP image taking too much time

### ISSUE THREAD

**Issue by obabujiApp** [facebook/fresco#1985] opened 2017-12-11 11:13 UTC
Hello,

I am loading images in RecyclerView from web url but its taking too much time all images are in
 .WebP format , upto 100KB Size & 1000*1000 dimensions.

Earlier I was using same images in png (each size upto 500KB, dimension 1000*1000) i thought may be due to this reason its taking more time but i changed all images to .WebP after that size is reduced but still getting same issue.

I already set all requirements of .WebP image like dependency compile 'com.facebook.fresco:webpsupport:1.5.0'  , minSdkVersion 18 etc.

**Comment by dmitry-voronkevich** [comment] 2017-12-11 14:16
@obabujiApp, can you please follow the guidance when posting issues. We need more details to help you.
Do you have example of an image you are loading?
What is definition of "taking too much time"? Is this time to load image or display image?
Is it slow when image been already cached and loaded from disc cache? (for this you can kill app and restart and if you have same urls you can expect them to be in disc cache).
How many images do you want to show?
How does your request looks like? Do you apply any transformations to the request?
How does you pipeline configured?
Thank you

**Comment by obabujiApp** [comment] 2017-12-13 11:29
@dmitry-voronkevich  

Example of images i am loading
http://apnasweets.com/image/catalog/mobile_products/AlmondNut_1000X1000-min.webp
http://apnasweets.com/image/catalog/mobile_products/AlmondSandwitch_1000X1000-min.webp
http://apnasweets.com/image/catalog/mobile_products/Dry-Fruit-Cheeku_1000X1000-min.webp
etc 

*Note:  all images are same dimension 1000x1000 with various size .

**taking too much time?**
Means when loading image first time from image url it is slow while second time (from cached ) its fine

**How many images do you want to show?**
As I told you i am using RecyclerView and its depend on user's scroll once its showing  3-7 rows depend on screen size total number rows around 40 

**How does your request looks like? Do you apply any transformations to the request?**

I am following below steps

1. In My Application class 
```
ImagePipelineConfig config = ImagePipelineConfig.newBuilder(getApplicationContext())
                .build();
Fresco.initialize(getApplicationContext(), config);
```
2. In xml 
  ```
<com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/product_image"
        android:layout_width="125dp"
        android:layout_height="125dp"
        android:layout_gravity="center"
        app:placeholderImage="@drawable/plcae_holder"
        app:failureImage="@drawable/no_image_found"
        app:actualImageScaleType="centerCrop" />
```
 
3. In adapter class
     `holder.itemImage.setImageURI(singleItem.getImageUrl()); ` 

**How does you pipeline configured?**
I did not configured any pipeline.

**Comment by dmitry-voronkevich** [comment] 2017-12-13 11:37
@obabujiApp, by saying "slow", are you talking about minutes, seconds, milliseconds? What is your network speed? How fast browser loads same images on your phone on the same connection? Is it relatively same time or fresco is much slower?

**Comment by obabujiApp** [comment] 2017-12-13 11:57
@dmitry-voronkevich  In browser  its taking around 20 sec but in my app around 40-50 sec with same network speed.

**Comment by dmitry-voronkevich** [comment] 2017-12-14 13:46
Thank you, @obabujiApp, we will investigate this issue

**Comment by erikandre** [comment] 2018-01-16 16:43
@obabujiApp I've tried to reproduce the described issue in the Fresco showcase app.

For me it took about 2000ms before the image was displayed (I used one of your example images).
Most of that time was spent waiting for the download to finish.

When doing the same download on my laptop (just using wget) it takes about 500ms so 4x faster.

The times that you mention sounds really long, specially that it would 40 seconds to load in browser (is that the browser on your device). Since I don't see any action to take here or a strong connection to Fresco itself I'm going to close the issue.

If you have some additional information that could help us investigate this, then please comment here and I can reopen the issue.

**Closed by erikandre** 2018-01-16 16:43 UTC
