### ISSUE TITLE
Landscape Image Has Been Cropped

### ISSUE THREAD

**Issue by younas-bangash** [facebook/fresco#1889] opened 2017-09-04 13:22 UTC
### Description

I take Image from camera and upload to the server when I try to display that image on the SimpleDraweeView the image has been cropped while it work perfectly when I upload the image using Gallary I use below code to get the image and display on the view

```
 <com.facebook.drawee.view.SimpleDraweeView
            xmlns:fresco="http://schemas.android.com/tools"
            android:id="@+id/voucherImage"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            fresco:failureImage="@drawable/no_image" />
```

```
GenericDraweeHierarchyBuilder builder = new GenericDraweeHierarchyBuilder(getResources());
        GenericDraweeHierarchy hierarchy = builder.setFadeDuration(100).build();
        hierarchy.setProgressBarImage(new ImageLoadProgressBar());
        imageView.setHierarchy(hierarchy);
        imageView.getHierarchy().setFailureImage(R.mipmap.no_image);

        ImageRequest imageRequest = ImageRequestBuilder.newBuilderWithSource(uri)
                .build();
        PipelineDraweeControllerBuilder controllerBuilder = Fresco.newDraweeControllerBuilder()
                .setOldController(imageView.getController())
                .setControllerListener(new BaseControllerListener<ImageInfo>(){
                    @Override
                    public void onSubmit(String id, Object callerContext) {
                        super.onSubmit(id, callerContext);
                    }

                    @Override
                    public void onFinalImageSet(String id, ImageInfo imageInfo, Animatable animatable) {
                        Log.i("DraweeUpdate", "Image is fully loaded!");
                        super.onFinalImageSet(id, imageInfo, animatable);
                       
                    }

                    @Override
                    public void onIntermediateImageSet(String id, ImageInfo imageInfo) {
                        Log.i("DraweeUpdate", "Image is partly loaded! (maybe it's a progressive JPEG?)");
                        super.onIntermediateImageSet(id, imageInfo);

                    }

                    @Override
                    public void onIntermediateImageFailed(String id, Throwable throwable) {
                        super.onIntermediateImageFailed(id, throwable);
                      
                    }

                    @Override
                    public void onFailure(String id, Throwable throwable) {
                        Log.i("DraweeUpdate", "Image failed to load: " + throwable.getMessage());
                        super.onFailure(id, throwable);
                        
                    }

                    @Override
                    public void onRelease(String id) {
                        super.onRelease(id);
                    }
                })
                .setImageRequest(imageRequest);
        imageView.setController(controllerBuilder.build());
```

### Additional Information

* Fresco version: [com.facebook.fresco:fresco:1.5.0]
* Platform version: [Android  6.0]

**Comment by lambdapioneer** [comment] 2017-09-04 15:58
Hey @younas-bangash, have a look at http://frescolib.org/docs/scaletypes.html on how to use scale types. Let me know if this does not solve the problem for you or I've misunderstood the question.

**Comment by younas-bangash** [comment] 2017-09-05 05:57
Below is the original  Image that is uploaded on server
![voucher](https://user-images.githubusercontent.com/4440531/30047025-0521908a-9220-11e7-8a89-d3a7e9973066.jpg)

I used the above code to show the image on the view of id voucherImage but it displays as below and I try all the scale type nothing is working 

![voucher](https://user-images.githubusercontent.com/4440531/30047108-82a6aa22-9220-11e7-8546-1bc4f318173e.jpg)

and same is the case if I take an image in the Landscape So should I change the library or I am doing it wrong

**Comment by lambdapioneer** [comment] 2017-09-05 09:36
I'd be inclined to say that this is likely caused by the layout that includes the `SimpleDraweeView`. We can confirm that the following way: enable the controller overlay in the Fresco configuration (see below) and post the screenshot. Ideally, you also enable the layout bounds in the developer settings. CC @oprisnik 

It shows two lines which are `I: wxh` (the image dimensions) and `D: wxh` (the drawable dimensions). The layout cause is confirmed then the image dimensions match the original image (at least in terms of aspects ratio), but the drawable ones do not.

Where you initialize Fresco add the following:

```java
ImagePipelineConfig imagePipelineConfig = ... // you should already have this

DraweeConfig.Builder draweeConfigBuilder = DraweeConfig.newBuilder();
draweeConfigBuilder.setDebugOverlayEnabledSupplier(
        Suppliers.of(true));

Fresco.initialize(this, imagePipelineConfig, draweeConfigBuilder.build()); // you should already have a similar call. replace it with this
```

Alternatively, if you find a way to reproduce it in the showcase app that is in this repo, we can work from there.

**Comment by younas-bangash** [comment] 2017-09-05 13:28
After trying method which you mention I am not able to solve my issue so I have no other ways but to use the Glide library which working perfectly

**Comment by lambdapioneer** [comment] 2017-09-05 13:33
Sorry that I couldn't help you with the information provided. I'll close this issue then.

**Closed by lambdapioneer** 2017-09-05 13:33 UTC
