### ISSUE TITLE
Image doesn't show up when width and height are set to match_parent

### ISSUE THREAD

**Issue by mpivchev** [facebook/fresco#2048] opened 2018-02-10 18:39 UTC
I want to load an image on fullscreen and make it fit the screen. However, when I set the width and height to `match_parent` nothing gets shown. If I change them to a fixed dp it displays just fine. What is the problem?

**Layout:**
```
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    tools:context="com.github.mpivchev.app.fragments.ImageViewerFragment">

    <com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/iv_media"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:placeholderImage="@drawable/ic_pen_fab"/>
</FrameLayout>
```

**Fetching the image:**

```
  Uri uri = Uri.parse("https://i.imgur.com/sMeqqb4.jpg");
  media.setImageURI(uri);
```

**With `match_parent`:**
https://i.imgur.com/vLTf2uj.png

**Fixed dp:**
https://i.imgur.com/TAh3v2x.png

**Comment by oprisnik** [comment] 2018-02-12 10:57
Hi @mpivchev, our Showcase sample app has an example that does exactly that.

The XML layout looks similar to yours:
https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/res/layout/activity_drawee_transition_detail.xml

The Java code is here (which is again very similar):
https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/drawee/transition/ImageDetailsActivity.java

Please check where your code differs from the sample I've linked to above. Everything works in the sample app and your code does look quite similar, so I suppose the issue is somewhere else.

I'm closing this for now, but if you think there is an issue with the Fresco library, let us know with more details and how to reproduce in the Showcase sample app (e.g. by changing the example) and we'll re-open and investigate.

**Closed by oprisnik** 2018-02-12 10:57 UTC
