### ISSUE TITLE
Gif loading shows some part blank for specific devices

### ISSUE THREAD

**Issue by PalDhv** [facebook/fresco#2061] opened 2018-03-05 14:18 UTC
I have used SimpleDraweeView for gif image loading.
But for some of the devices like Samsung J7 max, it shows some part white.
Kindly check attached screenshot for more reference.
* Fresco version: 1.4.0
* Platform version: Samsung J7 Max(7.0)
![device-2018-03-05-194356](https://user-images.githubusercontent.com/28922865/36979631-20ec97b6-20ae-11e8-8b6a-c59018e67687.png)

**Comment by zmroczek** [comment] 2018-03-05 14:55
Hi @PalDhv,

Thanks for reporting this issue. Have you checked our [showcase app](https://github.com/facebook/fresco/tree/master/samples) that shows an example of [gif loading](https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/imageformat/gif/ImageFormatGifFragment.java)? 

Please take a look on the link I provided to see if you're using the correct code, otherwise please provide a code sample to reproduce your issue.

**Comment by PalDhv** [comment] 2018-03-06 05:08
This issue is device specific...Happening in  Samsung J7 Max(7.0). Working fine for other Motorola devices.
Have look at my code
      GenericDraweeHierarchy hierarchy = holderView.gifImage.getHierarchy();
      hierarchy.setProgressBarImage(R.drawable.gif_loading);
      hierarchy.setActualImageScaleType(ScalingUtils.ScaleType.FIT_XY);
      DraweeController controller =

        Fresco.newDraweeControllerBuilder()
          .setUri(mMessage.toString())
          .setAutoPlayAnimations(true)
          .setRetainImageOnFailure(true)
          .build();



Let me know if I am doing something wrong.

**Comment by oprisnik** [comment] 2018-03-07 14:47
Does this happen exclusively for GIF images or also for normal images? Do you have a sample GIF for us?

**Comment by oprisnik** [comment] 2018-04-11 11:05
This seems to be a duplicate of #2067 due to the FIT_XY scale type.

**Closed by oprisnik** 2018-04-11 11:05 UTC
