### ISSUE TITLE
Issue with Build Tools 1.5.0 Beta 1?

### ISSUE THREAD

**Issue by jkane001** [facebook/fresco#733] opened 2015-11-05 14:35 UTC
I'm using Fresco 0.8.1, but this happened with 0.7.0 as well...

I just tried upgrading my BuildTools to 1.5.0 beta 1, and upon app start, I now get this:

Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.carmax.carmaxowner.qa-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libmemchunk.so"
       at java.lang.Runtime.loadLibrary(Runtime.java:366)
       at java.lang.System.loadLibrary(System.java:989)
       at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:32)
       at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
       at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:36)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
       at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:98)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:26)
       at com.facebook.imagepipeline.producers.LocalFetchProducer.getByteBufferBackedEncodedImage(LocalFetchProducer.java:99)
       at com.facebook.imagepipeline.producers.LocalFetchProducer.getEncodedImage(LocalFetchProducer.java:119)
       at com.facebook.imagepipeline.producers.LocalResourceFetchProducer.getEncodedImage(LocalResourceFetchProducer.java:42)
       at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:66)
       at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:62)
       at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:45)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

When I go back to BuildTools 1.4.0 beta 6, all is well.

**Comment by tyronen** [comment] 2015-11-05 20:32
Duplicate of #410 please comment there.

**Closed by tyronen** 2015-11-05 20:32 UTC
Labels: duplicate
