### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by droidwolf** [facebook/fresco#449] opened 2015-07-13 10:05 UTC
ANDROID VERSION4.2.2

java.lang.IllegalArgumentException
       at com.facebook.common.internal.Preconditions.checkArgument(Preconditions.java:108)
       at com.facebook.imagepipeline.memory.BitmapCounter.decrease(BitmapCounter.java:64)
       at com.facebook.imagepipeline.bitmaps.DalvikBitmapFactory$1.release(DalvikBitmapFactory.java:54)
       at com.facebook.imagepipeline.bitmaps.DalvikBitmapFactory$1.release(DalvikBitmapFactory.java:50)
       at com.facebook.common.references.SharedReference.deleteReference(SharedReference.java:211)
       at com.facebook.common.references.CloseableReference.close(CloseableReference.java:146)
       at com.facebook.imagepipeline.image.CloseableStaticBitmap.close(CloseableStaticBitmap.java:81)
       at com.facebook.common.internal.Closeables.close(Closeables.java:75)
       at com.facebook.common.references.CloseableReference$1.release(CloseableReference.java:75)
       at com.facebook.common.references.CloseableReference$1.release(CloseableReference.java:71)
       at com.facebook.common.references.SharedReference.deleteReference(SharedReference.java:211)
       at com.facebook.common.references.CloseableReference.close(CloseableReference.java:146)
       at com.facebook.common.references.CloseableReference.closeSafely(CloseableReference.java:265)
       at com.facebook.imagepipeline.cache.CountingMemoryCache.releaseClientReference(CountingMemoryCache.java:216)
       at com.facebook.imagepipeline.cache.CountingMemoryCache.access$000(CountingMemoryCache.java:44)
       at com.facebook.imagepipeline.cache.CountingMemoryCache$2.release(CountingMemoryCache.java:202)
       at com.facebook.common.references.SharedReference.deleteReference(SharedReference.java:211)
       at com.facebook.common.references.CloseableReference.close(CloseableReference.java:146)
       at com.facebook.common.references.CloseableReference.closeSafely(CloseableReference.java:265)
       at com.facebook.drawee.backends.pipeline.PipelineDraweeController.releaseImage(PipelineDraweeController.java:127)
       at com.facebook.drawee.backends.pipeline.PipelineDraweeController.releaseImage(PipelineDraweeController.java:41)
       at com.facebook.drawee.controller.AbstractDraweeController.onNewResultInternal(AbstractDraweeController.java:482)
       at com.facebook.drawee.controller.AbstractDraweeController.access$000(AbstractDraweeController.java:47)
       at com.facebook.drawee.controller.AbstractDraweeController$1.onNewResultImpl(AbstractDraweeController.java:413)
       at com.facebook.datasource.BaseDataSubscriber.onNewResult(BaseDataSubscriber.java:43)
       at com.facebook.datasource.AbstractDataSource$1.run(AbstractDataSource.java:181)
       at android.os.Handler.handleCallback(Handler.java:800)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5433)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by michalgr** [comment] 2015-07-13 17:57
Which version of Fresco do you use? Are there any modifications to the library ?

**Comment by droidwolf** [comment] 2015-07-14 02:33
fresco 0.5.0.
No modifications.

**Comment by Eagles2F** [comment] 2015-08-17 22:12
I'm also experiencing the same problem. Evan though the image still get loaded successfully.

**Comment by plamenko** [comment] 2015-08-18 15:28
Does this happen with the latest Fresco version?

**Comment by Eagles2F** [comment] 2015-08-18 16:08
compile 'com.facebook.fresco:fresco:0.6.1'
    compile 'com.facebook.fresco:imagepipeline-okhttp:0.6.1+'

**Comment by plamenko** [comment] 2015-08-21 18:58
We are investigating.

**Comment by tyronen** [comment] 2015-10-30 12:11
Fixed in 0.7.0.

**Closed by tyronen** 2015-10-30 12:11 UTC
Labels: bug

**Comment by sourabhv** [comment] 2016-12-12 09:02
Similar exception in `0.14.0`

	E/unknown:TransformingConsumer: unhandled exception
	    java.lang.IllegalArgumentException
	        at com.facebook.common.internal.Preconditions.checkArgument(Preconditions.java:108)
	        at com.facebook.imagepipeline.producers.ResizeAndRotateProducer.getRotationAngle(ResizeAndRotateProducer.java:288)
	        at com.facebook.imagepipeline.producers.ResizeAndRotateProducer.shouldRotate(ResizeAndRotateProducer.java:301)
	        at com.facebook.imagepipeline.producers.ResizeAndRotateProducer.shouldTransform(ResizeAndRotateProducer.java:228)
	        at com.facebook.imagepipeline.producers.ResizeAndRotateProducer.access$600(ResizeAndRotateProducer.java:43)
	        at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.onNewResultImpl(ResizeAndRotateProducer.java:128)
	        at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.onNewResultImpl(ResizeAndRotateProducer.java:76)
	        at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
	        at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer$AddImageTransformMetaDataConsumer.onNewResultImpl(AddImageTransformMetaDataProducer.java:48)
	        at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer$AddImageTransformMetaDataConsumer.onNewResultImpl(AddImageTransformMetaDataProducer.java:32)
	        at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
	        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onNextResult(MultiplexProducer.java:442)
	        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:499)
	        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:496)
	        at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
	        at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer$1.onNewResultImpl(EncodedMemoryCacheProducer.java:94)
	        at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer$1.onNewResultImpl(EncodedMemoryCacheProducer.java:89)
	        at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
	        at com.facebook.imagepipeline.producers.DiskCacheProducer$DiskCacheConsumer.onNewResultImpl(DiskCacheProducer.java:234)
	        at com.facebook.imagepipeline.producers.DiskCacheProducer$DiskCacheConsumer.onNewResultImpl(DiskCacheProducer.java:206)
	        at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
	        at com.facebook.imagepipeline.producers.NetworkFetchProducer.notifyConsumer(NetworkFetchProducer.java:168)
	        at com.facebook.imagepipeline.producers.NetworkFetchProducer.maybeHandleIntermediateResult(NetworkFetchProducer.java:145)
	        at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:104)
	        at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(NetworkFetchProducer.java:37)
	        at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:72)
	        at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher.fetchSync(HttpUrlConnectionNetworkFetcher.java:83)
	        at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher$1.run(HttpUrlConnectionNetworkFetcher.java:61)
	        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	        at java.lang.Thread.run(Thread.java:818)

**Comment by lambdapioneer** [comment] 2016-12-12 17:30
Hi @sourabhv, your issue seems to be a duplicate of https://github.com/facebook/fresco/issues/1482. @kirwan put a fix up with https://github.com/facebook/fresco/commit/573986ac0530300a42941534898b534234745c24 .

Please update to 0.14.1 in order to fix this issue :)
