### ISSUE TITLE
dlopen failed: library "libnative-imagetranscoder.so" not found - V3.0.0

### ISSUE THREAD

**Issue by leandro1995** [facebook/fresco#2722] opened 2023-04-11 05:55 UTC
Apparently, in the case of the library, version 3.0.0, the error "dlopen failed: library "libnative-imagetranscoder.so" not found" appears. I have seen error reports from 2019, but for some reason, it started to appear in this latest version, which is preventing me from using it. Therefore, I had to downgrade the library to version 2.6.0, which works normally. Please review this error.

![Captura de pantalla 2023-04-11 005356](https://user-images.githubusercontent.com/25448691/231068979-f7cb4e7e-2a72-474a-a2fb-2756ae7ca30c.png)

**Comment by oprisnik** [comment] 2023-04-11 11:05
Can you please try adding the following Gradle dependency to your build:
```
com.facebook.fresco:nativeimagetranscoder3:3.0.0
```
That should fix the crash.

**Comment by ongakuer** [comment] 2023-04-12 04:47
> Can you please try adding the following Gradle dependency to your build:
> 
> ```
> com.facebook.fresco:nativeimagetranscoder3:3.0.0
> ```
> 
> That should fix the crash.

There is NO **libnative-imagetranscoder.so** file in `com.facebook.fresco:nativeimagetranscoder:3.0.0`
Please fix this bug.

We can check files in maven.  The "nativeimagetranscoder-3.0.0" is only 7kb.
https://repo1.maven.org/maven2/com/facebook/fresco/nativeimagetranscoder/3.0.0/nativeimagetranscoder-3.0.0.aar

But the "nativeimagetranscoder-2.6.0" is almost 700kb. and unzip file, we can found libnative-imagetranscoder.so
https://repo1.maven.org/maven2/com/facebook/fresco/nativeimagetranscoder/2.6.0/nativeimagetranscoder-2.6.0.aar

**Comment by MALTF** [comment] 2023-04-21 02:15
I have also encountered this situation, and the introduction of "com. Facebook. Fresco: nativeimagetranscoder3:3.0.0" cannot solve it.
The current solution is to copy the "libnative imagetranscoder. so" file under 2.6.0 to the project jniLibs directory for use, and wait for the fixed version.

**Comment by kojofosu** [comment] 2023-04-24 10:52
Having same issue 

```              
   java.lang.UnsatisfiedLinkError: dlopen failed: library "libnative-imagetranscoder.so" not found
                 	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                 	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                 	at java.lang.System.loadLibrary(System.java:1661)
                 	at com.facebook.soloader.nativeloader.SystemDelegate.loadLibrary(SystemDelegate.java:24)
                 	at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:52)
                 	at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:30)
                        ...
```

**Comment by charlesBon** [comment] 2023-04-30 18:19
> I have also encountered this situation, and the introduction of "com. Facebook. Fresco: nativeimagetranscoder3:3.0.0" cannot solve it. The current solution is to copy the "libnative imagetranscoder. so" file under 2.6.0 to the project jniLibs directory for use, and wait for the fixed version.

Please can you give more details on how to do this, because I tried copying "libnative imagetranscoder. so" file to src/main/jniLibs. still giving me the same error

**Comment by charlesBon** [comment] 2023-04-30 18:24
Still getting this error please have tried everything even downgrading and this crashes android app when loading images from the web

`FATAL EXCEPTION: FrescoIoBoundExecutor-2
                                                                                                    Process: com.myapp, PID: 21806
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: library "libnative-imagetranscoder.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    	at com.facebook.soloader.nativeloader.SystemDelegate.loadLibrary(SystemDelegate.java:24)
                                                                                                    	at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:52)
                                                                                                    	at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:30)
                                                                                                    	at com.facebook.imagepipeline.nativecode.NativeJpegTranscoderSoLoader.ensure(NativeJpegTranscoderSoLoader.java:33)
                                                                                                    	at com.facebook.imagepipeline.nativecode.NativeJpegTranscoder.<init>(NativeJpegTranscoder.java:59)
                                                                                                    	at com.facebook.imagepipeline.nativecode.NativeJpegTranscoderFactory.createImageTranscoder(NativeJpegTranscoderFactory.java:43)
                                                                                                    	at com.facebook.imagepipeline.transcoder.MultiImageTranscoderFactory.getNativeImageTranscoder(MultiImageTranscoderFactory.kt:59)
                                                                                                    	at com.facebook.imagepipeline.transcoder.MultiImageTranscoderFactory.createImageTranscoder(MultiImageTranscoderFactory.kt:40)
                                                                                                    	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.onNewResultImpl(ResizeAndRotateProducer.java:166)
                                                                                                    	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.onNewResultImpl(ResizeAndRotateProducer.java:84)
                                                                                                    	at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:89)
                                                                                                    	at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer$AddImageTransformMetaDataConsumer.onNewResultImpl(AddImageTransformMetaDataProducer.java:49)
                                                                                                    	at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer$AddImageTransformMetaDataConsumer.onNewResultImpl(AddImageTransformMetaDataProducer.java:33)
                                                                                                    	at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:89)
                                                                                                    	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onNextResult(MultiplexProducer.java:510)
                                                                                                    	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:569)
                                                                                                    	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:562)
                                                                                                    	at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:89)
                                                                                                    	at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer$EncodedMemoryCacheConsumer.onNewResultImpl(EncodedMemoryCacheProducer.java:188)
                                                                                                    	at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer$EncodedMemoryCacheConsumer.onNewResultImpl(EncodedMemoryCacheProducer.java:123)
                                                                                                    	at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:89)
                                                                                                    	at com.facebook.imagepipeline.producers.DiskCacheReadProducer$1.then(DiskCacheReadProducer.java:113)
                                                                                                    	at com.facebook.imagepipeline.producers.DiskCacheReadProducer$1.then(DiskCacheReadProducer.java:93)
                                                                                                    	at bolts.Task$14.run(Task.java:872)
                                                                                                    	at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
                                                                                                    	at bolts.Task.completeImmediately(Task.java:863)
                                                                                                    	at bolts.Task.access$000(Task.java:32)
                                                                                                    	at bolts.Task$10.then(Task.java:654)
                                                                                                    	at bolts.Task$10.then(Task.java:651)
                                                                                                    	at bolts.Task.runContinuations(Task.java:956)
                                                                                                    	at bolts.Task.trySetResult(Task.java:994)
                                                                                                    	at bolts.TaskCompletionSource.trySetResult(TaskCompletionSource.java:39)
                                                                                                    	at bolts.TaskCompletionSource.setResult(TaskCompletionSource.java:62)
                                                                                                    	at bolts.Task$4.run(Task.java:357)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at com.facebook.imagepipeline.core.PriorityThreadFactory.newThread$lambda$0(PriorityThreadFactory.kt:37)
                                                                                                    	at com.facebook.imagepipeline.core.PriorityThreadFactory.$r8$lambda$IPp7Vm9a1KDy8D4770JTjI9qOG4(Unknown Source:0)
2023-04-30 14:11:44.994 21806-21926 AndroidRuntime          com.prendz                           E  	at com.facebook.imagepipeline.core.PriorityThreadFactory$$ExternalSyntheticLambda0.run(Unknown Source:4)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)`

**Comment by initialjie** [comment] 2023-05-05 02:38
> 

Extract corresponding imagetranscoder. so from aar([2.6.0 version](https://repo1.maven.org/maven2/com/facebook/fresco/nativeimagetranscoder/2.6.0/nativeimagetranscoder-2.6.0.aar)) to your project src/main/jniLibs, and still using com.facebook.fresco:nativeimagetranscoder:3.0.0

**Comment by amalshahzee** [comment] 2023-05-13 08:01
Hi, When will the fix for this be released ?

**Comment by dcalandria** [comment] 2023-05-18 17:59
This can solve the issue:

```
implementation('com.facebook.fresco:nativeimagetranscoder') {
        version {
            strictly '2.6.0'
        }
}
```

**Comment by cadalt** [comment] 2023-08-11 13:00
hi! is https://github.com/facebook/fresco/issues/2722#issuecomment-1553420152 really the permanent solution here, or will this be fixed in an upcoming release?

**Comment by MALTF** [comment] 2023-08-17 01:57
At present, it has been temporarily resolved. It should be due to forgetting the resources when packaging and publishing. Let's wait for the official resolution in the future.




┏&nbsp;(゜ω゜)=?????
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebook/fresco"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月11日(星期五) 晚上9:00
***@***.***&gt;;
抄送:&nbsp;"┏ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebook/fresco] dlopen failed: library "libnative-imagetranscoder.so" not found - V3.0.0 (Issue #2722)





 
hi! is #2722 (comment) really the permanent solution here, or will this be fixed in an upcoming release?

**Comment by ongakuer** [comment] 2023-09-19 03:17
> > Can you please try adding the following Gradle dependency to your build:
> > ```
> > com.facebook.fresco:nativeimagetranscoder3:3.0.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That should fix the crash.
> 
> There is NO **libnative-imagetranscoder.so** file in `com.facebook.fresco:nativeimagetranscoder:3.0.0` Please fix this bug.
> 
> We can check files in maven. The "nativeimagetranscoder-3.0.0" is only 7kb. https://repo1.maven.org/maven2/com/facebook/fresco/nativeimagetranscoder/3.0.0/nativeimagetranscoder-3.0.0.aar
> 
> But the "nativeimagetranscoder-2.6.0" is almost 700kb. and unzip file, we can found libnative-imagetranscoder.so https://repo1.maven.org/maven2/com/facebook/fresco/nativeimagetranscoder/2.6.0/nativeimagetranscoder-2.6.0.aar

3.1.0 works well

**Comment by jraska** [comment] 2023-10-03 21:10
Hey, regression:

- 👍 Version 3.1.0 works well - with the [nativeimagetranscoder-3.1.0.aar](https://repo1.maven.org/maven2/com/facebook/fresco/nativeimagetranscoder/3.1.0/nativeimagetranscoder-3.1.0.aar) having around [700 kB on Maven Central](https://repo1.maven.org/maven2/com/facebook/fresco/nativeimagetranscoder/3.1.0/).
- 👎 Version **3.1.1** doesn't work throwing the `dlopen failed: library "libnative-imagetranscoder.so" not found` with the [nativeimagetranscoder-3.1.1.aar](https://repo1.maven.org/maven2/com/facebook/fresco/nativeimagetranscoder/3.1.1/nativeimagetranscoder-3.1.1.aar) having [7 kB on Maven Central](https://repo1.maven.org/maven2/com/facebook/fresco/nativeimagetranscoder/3.1.1/)- meaning the `libnative-imagetranscoder.so` is missing.

Therefore current solution is using version 3.1.0 and 
`implementation 'com.facebook.fresco:nativeimagetranscoder:3.1.0'`

**Comment by crumpf** [comment] 2023-10-05 17:12
Seems like `libnative-imagetranscoder.so` reappeared in 3.1.0, only to disappear in 3.1.1. Similar to https://github.com/facebook/fresco/issues/2722#issuecomment-1553420152, I was able to run by strictly using the 3.1.0 lib. Wondering if this is viable until there's a future fix?

```
implementation('com.facebook.fresco:nativeimagetranscoder') {
    version {
        strictly '3.1.0'
    }
}
```

**Comment by asos-edgeorge** [comment] 2023-10-09 18:31
Not sure why this was closed - seems like an issue that remains unresolved, albeit with a valid workaround

**Comment by crumpf** [comment] 2023-10-19 19:51
This still seems to be an issue with `3.1.2`

**Closed** 2023-10-25 13:48 UTC

**Comment by oprisnik** [comment] 2023-10-25 16:25
Please update to version 3.1.3, which should fix the native library issues.
