### ISSUE TITLE
Windows os How to build?

### ISSUE THREAD

**Issue by PmtPrt** [facebook/fresco#24] opened 2015-03-28 15:10 UTC
## My Environment
* os : WIndows 7 Ultimake
* SET ANDROID_HOME=C:\android-sdk-windows
* SET PATH=C:\android-ndk-r10d;%PATH%

## Run
* gradlew build

## Result
FAILURE: Build failed with an exception.

\* What went wrong:
Execution failed for task ':imagepipeline:ndk_build_gifimage'.
\> A problem occurred starting process 'command 'ndk-build''

\* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

....... ㅜ.ㅡ

## Retry
* gradlew build -- stacktrace

## Result
\* What went wrong:
Execution failed for task ':imagepipeline:ndk_build_gifimage'.
\> A problem occurred starting process 'command 'ndk-build''

\* Try:
Run with --info or --debug option to get more log output.

\* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':imagepipeline:ndk_build_gifimage'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
...

**Comment by 81813780** [comment] 2015-03-30 03:48
I have same problem ,Did you solved it ?

**Comment by MarkMjw** [comment] 2015-03-30 09:21
#5 maybe resolve this, but i failed in windows.

**Comment by appledong** [comment] 2015-03-30 09:46
I have same problem ,Did you solved it ?

**Comment by michalgr** [comment] 2015-03-30 12:42
Thanks for reporting!

Could you check if replacing "ndk-build" with "C:\android-ndk-r10d\ndk-build.cmd" in imagepipeline/build.gradle resolves the issue ?

If no, can you cd to imagepipeline directory and see if there is anything suspicious in the output of following command:
C:\android-ndk-r10d\ndk-build.cmd NDK_APPLICATION_MK=../Application.mk NDK_OUT=build NDK_LIBS_OUT=build -C src/main/jni/gifimage
There are couple of hardcoded "/" in the build script, I wonder if replacing them with "\" solves the issue.

**Comment by tyronen** [comment] 2015-03-30 20:46
Also, the Android NDK on Windows requires that [Cygwin](https://www.cygwin.com) 1.7 or later be installed. I will update the docs to reflect this.

**Comment by hiphonezhu** [comment] 2015-03-31 05:35
:imagepipeline:ndk_build_gifimage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':imagepipeline:ndk_build_gifimage'.
> A problem occurred starting process 'command 'D:/Android/software/android-ndk-
r5b/ndk-build''



This error also accured when I build it, so did anyone have solved it?

**Comment by hiphonezhu** [comment] 2015-03-31 05:43
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':imagepi
peline:ndk_build_gifimage'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExec
uter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.exec
ute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execut
e(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecu
ter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter
.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execut
e(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter
.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailur
e(AbstractTask.java:305)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
orker.executeTask(AbstractTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
orker.processTask(AbstractTaskPlanExecutor.java:63)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
orker.run(AbstractTaskPlanExecutor.java:51)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(Defaul
tTaskPlanExecutor.java:23)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(Defau
ltTaskGraphExecuter.java:88)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTask
ExecutionAction.java:29)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
r.java:62)
        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExec
uter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecu
ter.java:68)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildEx
ecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
r.java:62)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
r.java:55)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(Default
GradleLauncher.java:149)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradle
Launcher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLaun
cher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildCon
troller.run(InProcessBuildActionExecuter.java:80)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.jav
a:33)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.jav
a:24)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
ssBuildActionExecuter.java:36)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
ssBuildActionExecuter.java:26)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.jav
a:171)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti
meValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti
meValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
ortingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
ortingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBoots
trap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.j
ava:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.ja
va:33)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Caused by: org.gradle.process.internal.ExecException: A problem occurred startin
g process 'command 'ndk-build''
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(Default
ExecHandle.java:196)
        at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandl
e.java:325)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.jav
a:83)
        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecut
orImpl$1.run(DefaultExecutorFactory.java:64)
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'ndk-bui
ld'
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(Def
aultProcessLauncher.java:27)
        at net.rubygrapefruit.platform.internal.WindowsProcessLauncher.start(Win
dowsProcessLauncher.java:22)
        at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(Wra
pperProcessLauncher.java:36)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.jav
a:65)
        ... 1 more
Caused by: java.io.IOException: Cannot run program "ndk-build" (in directory "D:
\Android\源码相关\fresco\imagepipeline"): CreateProcess error=2, ?????????
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(Def
aultProcessLauncher.java:25)
        ... 4 more
Caused by: java.io.IOException: CreateProcess error=2, ?????????
        ... 5 more

It is the whole stacktrace, please help me

**Comment by BaronZ** [comment] 2015-04-01 01:31
anybody solved this problem?

**Comment by Flywhiter** [comment] 2015-04-01 02:20
I have same problem:
Error:Execution failed for task ':imagepipeline:ndk_build_gifimage'.
> A problem occurred starting process 'command 'ndk-build''

**Comment by treeseedm** [comment] 2015-04-01 10:13
anybody solved this problem?

**Comment by tyronen** [comment] 2015-04-01 15:41
The ndk-build command is supposed to get NDK_PROJECT_PATH from the NDK_APPLICATION_MK passed in on the command line, but for some reason this does not seem to work on Windows.

**Comment by lgengsy** [comment] 2015-04-01 17:29
got  it

**Comment by treeseedm** [comment] 2015-04-02 02:21
@lgengsy  How to solve?

**Comment by qiaodi** [comment] 2015-04-02 03:13
I have same problem.how to solve.....!

**Comment by ljnalex** [comment] 2015-04-03 06:06
Is already solve?

**Comment by tyronen** [comment] 2015-04-03 11:19
Hi, note for everybody:

We understand people are frustrated that there are multiple issues with the Windows build. We take responsibility for it - as you might have guessed, our team develops on Mac OS and Linux and missed Windows. We are committed to making it work on all three.

Our office is closed for the Easter weekend right now but we will be back on Tuesday and will fix this as soon as we can.

**Comment by plamenko** [comment] 2015-04-03 16:45
Stay tuned, I think @michalgr got windows build working. We'll update gradle files and provide how-to instructions on Tuesday.

**Comment by tbarthel-fr** [comment] 2015-04-04 12:11
For those who would like to build the project before the official update on Tuesday, here is a quick fix that works for me :

https://github.com/tbarthel-fr/fresco/commit/c1ba14ba855037497e89ccd11816c4f365af265e

It relies on com.android.library to find ndk-dir, so be sure that ndk.dir='my-ndk-path' is set in fresco/local.properties.

Happy Easter =)

**Comment by yuzhuguan** [comment] 2015-04-05 05:10
@tbarthel-fr  thanks , it's work

**Comment by jalpesh** [comment] 2015-04-06 04:41
@tbarthel-fr Confirmed, it works :)

**Comment by JoysonF** [comment] 2015-04-06 10:32
I am using Ubuntu , 
I have set the Path variables using the following commands
export NDK=~/home/joysonf/android_ndk/android-ndk-r10d
.But when i Build the project i still get the same error
Error:Execution failed for task ':imagepipeline:ndk_build_gifimage'.
> A problem occurred starting process 'command 'ndk-build''

**Comment by jalpesh** [comment] 2015-04-06 10:34
Hey @JoysonF , I managed to compile it in ubuntu by hardcoing the entire path to the ndk dir in the build.gradle file. TIP : Do not use ~, use /home/username path. 
Worked for me. I know not the best way, but this worked for me as a temp solution until I figure out a better way. Let me know if it works for you.

**Comment by JoysonF** [comment] 2015-04-06 10:53
@jalpesh , Thanks for your quick reply.
I have set the following path in build.gradle (imagepipeline) :
 ndk.dir=/home/joysonf/android_ndk/android-ndk-r10d
But when i build the project it still gives the above error.

**Comment by jalpesh** [comment] 2015-04-06 11:02
Hey @JoysonF , Not sure where did you make your change. Here is my gradle.build file

def makeNdkTasks(String name) {
    task "ndk_build_$name"(type: Exec) {
        println "Printing name here "
        println "[$name]"
        inputs.file("src/main/jni/$name")
        outputs.dir("$buildDir/$name")
	commandLine '/home/jjr/ndk/android-ndk-r10d/ndk-build',
            'NDK_APPLICATION_MK=../Application.mk',
            'NDK_OUT=' + temporaryDir,
            "NDK_LIBS_OUT=$buildDir/$name",
            '-C', file("src/main/jni/$name").absolutePath,
            '--jobs', '8'
    }

    task "ndk_clean_$name"(type: Exec) {
        println "Printing name here 2"
        println "[$name]"
        //commandLine 'ndk-build',
	//commandLine '/home/jjr/mounter/android-ndk-r10d/ndk-build',
	commandLine '/home/jjr/ndk/android-ndk-r10d/ndk-build',
            'NDK_APPLICATION_MK=../Application.mk',
            'NDK_OUT=' + temporaryDir,
            "NDK_LIBS_OUT=$buildDir/$name",
            '-C', file("src/main/jni/$name").absolutePath,
            'clean'
    }

**Comment by JoysonF** [comment] 2015-04-06 11:20
@jalpesh , Thanks Mate.It works.

**Comment by ljnalex** [comment] 2015-04-06 12:08
@jalpesh ,Thanks, it works

**Comment by plamenko** [comment] 2015-04-06 15:42
We should create a separate issue for linux

**Comment by qiaodi** [comment] 2015-04-07 03:02
yes,its worked in win7
"
    task "ndk_build_$name"(type: Exec) {
        println "Printing name here "
        println "[$name]"
        inputs.file("src/main/jni/$name")
        outputs.dir("$buildDir/$name")
        commandLine 'C:\\Work_Enviorment\\android-ndk-r10d\\ndk-build',
                'NDK_APPLICATION_MK=../Application.mk',
                'NDK_OUT=' + temporaryDir,
                "NDK_LIBS_OUT=$buildDir/$name",
                '-C', file("src/main/jni/$name").absolutePath,
                '--jobs', '8'
    }

    task "ndk_clean_$name"(type: Exec) {
        println "Printing name here 2"
        println "[$name]"
        //commandLine 'ndk-build',
//commandLine '/home/jjr/mounter/android-ndk-r10d/ndk-build',
        commandLine 'C:\\Work_Enviorment\\android-ndk-r10d\\ndk-build',
                'NDK_APPLICATION_MK=../Application.mk',
                'NDK_OUT=' + temporaryDir,
                "NDK_LIBS_OUT=$buildDir/$name",
                '-C', file("src/main/jni/$name").absolutePath,
                'clean'
    }
"

**Comment by treeseedm** [comment] 2015-04-07 04:15
it work, but I have another question
       https://chromium.googlesource.com/webm/libwebp ,this url Forbidden

**Comment by radmonac** [comment] 2015-04-07 07:36
@treeseedm , maybe you can clone from this mirror [https://github.com/webmproject/libwebp/](https://github.com/webmproject/libwebp/)

**Comment by treeseedm** [comment] 2015-04-07 08:30
a lot of  problem on windows os,too much troubles

**Comment by ICECHN** [comment] 2015-04-07 09:37
FAILED，help, help。。。
def makeNdkTasks(String name) {
    task "ndk_build_$name"(type: Exec) {
        println "Printing name here "
        println "[$name]"
        inputs.file("src/main/jni/$name")
        outputs.dir("$buildDir/$name")
        commandLine 'D:\\work\\android\\android-ndk-r10c\\ndk-build',
            'NDK_APPLICATION_MK=../Application.mk',
            'NDK_OUT=' + temporaryDir,
            "NDK_LIBS_OUT=$buildDir/$name",
            '-C', file("src/main/jni/$name").absolutePath,
            '--jobs', '8'
    }

    task "ndk_clean_$name"(type: Exec) {
        println "Printing name here 2"
        println "[$name]"
        commandLine 'D:\\work\\android\\android-ndk-r10c\\ndk-build',
            'NDK_APPLICATION_MK=../Application.mk',
            'NDK_OUT=' + temporaryDir,
            "NDK_LIBS_OUT=$buildDir/$name",
            '-C', file("src/main/jni/$name").absolutePath,
            'clean'
    }

    tasks.withType(JavaCompile) {
        compileTask -> compileTask.dependsOn "ndk_build_$name"
    }
    clean.dependsOn "ndk_clean_$name"
}

**Comment by tyronen** [comment] 2015-04-07 11:34
Sync to head and you should now be able to build on Windows.

Please file a new issue if any other problems appear.

**Closed by tyronen** 2015-04-07 11:34 UTC
Labels: bug

**Comment by hanks-zyh** [comment] 2015-05-05 15:14
I have in trouble when I build app
```
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
	E:\android-sdk\build-tools\22.0.1\dx.bat --dex --output E:\bysj\WifiProject-AS\WifiProject\app\build\intermediates\dex\debug --input-list=E:\bysj\WifiProject-AS\WifiProject\app\build\intermediates\tmp\dex\debug\inputList.txt
Error Code:
	2
Output:
	UNEXPECTED TOP-LEVEL EXCEPTION:
	com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
		at com.android.dx.command.dexer.Main.run(Main.java:246)
		at com.android.dx.command.dexer.Main.main(Main.java:215)
		at com.android.dx.command.Main.main(Main.java:106)
```

**Comment by MarkMjw** [comment] 2015-05-06 15:31
可能是有重复的jar被引用，查看dependencies和libs是否有重复引入的.jar包，同时看向版本是否一致。

Date: Tue, 5 May 2015 08:14:26 -0700

**Comment by hanks-zyh** [comment] 2015-05-06 16:02
@MarkMjw  dependencies and libs, any suggestion
```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.orhanobut:logger:1.8'
    compile 'io.reactivex:rxandroid:0.24.0'
    compile 'com.android.support:recyclerview-v7:21.0.0'
//    compile 'com.facebook.fresco:fresco:0.3.0+'
}
```
![qq 20150507000040](https://cloud.githubusercontent.com/assets/6268322/7497320/3e630c08-f44c-11e4-9717-1e726d93d711.png)

**Comment by Flywhiter** [comment] 2015-05-07 00:00
i have fix this来自我的华为手机-------- 原始邮件 --------主题：Re: [fresco] Windows os How to build? (#24)发件人：Mjw 收件人：facebook/fresco 抄送：Flywhiter 可能是有重复的jar被引用，查看dependencies和libs是否有重复引入的.jar包，同时看向版本是否一致。



Date: Tue, 5 May 2015 08:14:26 -0700

**Comment by MarkMjw** [comment] 2015-05-07 01:39
@Flywhiter has fixed this problem, @hanks-zyh you can discuss with he.

**Comment by hanks-zyh** [comment] 2015-05-07 04:07
@MarkMjw  Thanks, I solved it by remove `/libs/*.jar `,and add in dependencies 
```
  compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.orhanobut:logger:1.8'
    compile 'io.reactivex:rxandroid:0.24.0'
    compile "com.android.support:appcompat-v7:22.+"
    compile 'com.android.support:support-v13:21.+'
    compile 'com.android.support:support-v4:22.+'
    compile 'com.android.support:palette-v7:+'
    compile 'com.android.support:recyclerview-v7:+'
    compile 'com.android.support:cardview-v7:21.0.+'
    compile 'com.facebook.rebound:rebound:0.3.7'
    compile 'com.facebook.fresco:fresco:0.3.0+'
```

**Comment by klob** [comment] 2015-09-15 12:20
I think it is due to  windows NDK has file named “ndk-build,cmd ” and file named "ndk-build" which may make Android Studio confused.So I make following changes and it works.
    

def getNdkBuildFullPath() {
    return 'E:/SDK/android-ndk-r10e/ndk-build.cmd'
    // we allow to provide full path to ndk-build tool
    if (hasProperty('ndk.command')) {
        return property('ndk.command')
    }
    // or just a path to the containing directiry
    if (hasProperty('ndk.path')) {
        def path = property('ndk.path')
        if (!path.endsWith(File.separator)) {
            path += File.separator
        }
        return path + getNdkBuildName()
    }
    // if none of above is provided, we assume ndk-build is already in $PATH

    return getNdkBuildName()
}
![image](https://cloud.githubusercontent.com/assets/8454656/9876245/2c62a222-5be7-11e5-8200-f1b5538fbe7a.png)

**Comment by smallgp** [comment] 2015-10-22 08:52
@klob your way is ok ,thanx~~

**Comment by srajesh529** [comment] 2015-12-04 06:46
all solutions are tried but no use for me,getting the error like

Error:Execution failed for task ':imagepipeline:ndk_build_bitmaps'.
> A problem occurred starting process 'command 'E:/softwares/android-ndk-r10d/ndk-build''

How to build the fesco library?

**Comment by Qamar4P** [comment] 2016-04-28 13:09
**Solution** for build errors like Error:Execution failed for task ':imagepipeline:ndk_build_bitmaps'
also found in animated-webp & animated-gif
You need to open there Module build.gradle and relpace `commandLine getNdkBuildFullPath(),` with `commandLine "D:\\Android\\sdk\\ndk-bundle\\ndk-build.cmd",` absolute Path.
