### ISSUE TITLE
CloseableAnimatedImage  class can not be found

### ISSUE THREAD

**Issue by cjztool** [facebook/fresco#2577] opened 2021-01-20 05:11 UTC
After upgraded Fresco  from 1.9.0 to 2.3.0, add additional Fresco feature modules as follow:

    api 'com.facebook.fresco:fresco:2.3.0'
    api 'com.facebook.fresco:animated-gif:2.3.0'
    api 'com.facebook.fresco:animated-webp:2.3.0'
    api 'com.facebook.fresco:webpsupport:2.3.0'
    api 'com.facebook.fresco:imagepipeline-okhttp3:2.3.0'

CloseableAnimatedImage  class can not be found.

Did i miss something?

**Comment by wizh** [comment] 2021-01-20 11:46
Hi! Thanks for your question. Can you please try adding a dependency to 'com.facebook.fresco:animated-base:2.3.0'?

**Comment by cjztool** [comment] 2021-01-20 16:50
> Hi! Thanks for your question. Can you please try adding a dependency to 'com.facebook.fresco:animated-base:2.3.0'?

worked, Thank you!

Where can I find the full list of Fresco feature modules or/and some docs about upgrading?

**Comment by wizh** [comment] 2021-01-20 16:59
You can find all of our documentation here: https://frescolib.org/docs/. I'm closing this since the issue is resolved, but feel free to open a new issue if you need further support!

**Closed by wizh** 2021-01-20 16:59 UTC
Labels: question
