### ISSUE TITLE
The WebP animation always twinkles !

### ISSUE THREAD

**Issue by UFreedom** [facebook/fresco#1818] opened 2017-07-09 08:49 UTC
Recently,I have use Fresco to play webp animation,The picture will flash several times at the beginning.

But when I use YYImage to play WebP animation for IOS, everything works well with the same WebP file.

Also,I have try to change the frame rate of the animation or set a background with no alpha ,But no improvement has been made.

I have see the same issue [issue 1700](https://github.com/facebook/fresco/issues/1700), Is there any progress in this problem?

This is a very serious matter. this happens to every webp animation file.

The webp file ：http://oc3qvf0y5.bkt.clouddn.com/animate_webp_test.webp
The demo video: http://oc3qvf0y5.bkt.clouddn.com/animated_webp_test.mp4

* Fresco version: 1.3.0
* Platform version: Android 4.0+

**Comment by oprisnik** [comment] 2017-07-09 09:37
Do you have a sample WebP file where this happens?

**Comment by UFreedom** [comment] 2017-07-09 10:01
@oprisnik
Thanks,
 I have updated the comment, and add a webp file that I used.

**Comment by UFreedom** [comment] 2017-07-10 07:32
@oprisnik 

have you test the webp file? Are there any other useful information found?

**Comment by erikandre** [comment] 2017-07-12 18:05
@UFreedom The next release of Fresco will contain an updated version of libwebp as well as improved animation support. Once that is released, let's retest this.
I tried reproducing the issue with your webp files in the Showcase app, but have not succeeded so far (although this was already with a newer build of Fresco than what you are most likely running).

**Comment by UFreedom** [comment] 2017-07-13 23:56
@oprisnik 
Thanks,

when the next release comes, I can't wait to test it.

**Comment by kirwan** [comment] 2017-07-14 10:58
I'm closing this as a duplicate of #1700.

**Closed by kirwan** 2017-07-14 10:58 UTC
Labels: duplicate, needs-details

**Comment by oprisnik** [comment] 2017-07-17 14:23
We've released [Fresco v1.4.0](https://github.com/facebook/fresco/releases/tag/v1.4.0), which includes a new implementation for animated GIFs that is way more performant, especially in the case where you display multiple GIFs. Let us know if you're still experiencing problems with 1.4.0.
