### ISSUE TITLE
v0.10.0 Fresco with OkHttp v0.10.0 is leaking connections when some fetches produce 404 errors

### ISSUE THREAD

**Issue by jmbusby** [facebook/fresco#1180] opened 2016-05-02 19:30 UTC
I have been using Fresco 0.9.0 for a while with the OkHttp 0.9.0 network fetcher and everything has been fine. However, after upgrading to v0.10.0 for both Fresco and the OkHttp backend, I am seeing errors like this on occasion:

```
05-02 12:20:53.653 13097-14210/com.appname W/OkHttpClient: A connection to <URL_REMOVED> was leaked. Did you forget to close a response body?
```

This only happens in a certain scenario. I have some debug code that deliberately mangles some of my fetch URLs to test 404 handing, and when that code is enabled, I see the connection leaks as shown above. If I disable the mangling code, I see no leaks. If I change the debug code to mangle 100% of the URLs instead of 90%, this also works with no leaks (surprisingly).

My concern is that when I get legitimate 404 errors occurring in the wild (rather than faking them like this), they will be leaking connections which may eventually prevent images from loading.

**UPDATE: These connection leaks do not happen with Fresco 0.10.0 / OkHttp 0.9.0. Seems to be OkHttp 0.10.0 that is causing the problem?**

**Comment by jmbusby** [comment] 2016-05-09 17:46
I've also test with the new OkHttp3 network library offered, and I seem the same connection leaks.

**Comment by jmbusby** [comment] 2016-05-13 16:35
Any thoughts from Facebook devs on this? Is there further info I can provide to help?

**Comment by kirwan** [comment] 2016-05-17 17:06
That warning was added to OkHttp [here](https://github.com/square/okhttp/commit/4ae314a1f21d07ee5dbad024bc098182219e9e07) which is more recent than 2.6, which is what Fresco 0.9.1 depended on, so that explains the warning not showing before.

Taking a look at a couple of issues around this warning on OkHttp's project it seems the advice is to always call `ResponseBody.close()` regardless of whether the response was successfull and I've noticed we don't do that in the [error case](https://github.com/facebook/fresco/blob/master/imagepipeline-backends/imagepipeline-okhttp3/src/main/java/com/facebook/imagepipeline/backends/okhttp3/OkHttpNetworkFetcher.java#L109).

I'll fix this.

**Comment by jmbusby** [comment] 2016-05-17 17:31
Great thanks!

**Comment by kirwan** [comment] 2016-05-17 18:12
I think I have a fix but I've been unable to reproduce the bug. When you say you're mangling the URLs are you simply changing the URL before adding it to the `ImageRequest`?

If they're not private, would you mind sending me an example of one of these URLs to see if that then reproduces the original issue for me.

**Comment by jmbusby** [comment] 2016-05-17 18:48
The "mangling" is simply adding a suffix to the original URL prior to adding it to the `ImageRequest`, such as "mangled.jpg", so as to make the URL invalid.

There is not one particular URL that causes the issue for me. It only happens when I mangle a certain proportion of my image loads e.g. 10%. The percentage of URLs that I mangle does not matter for reproducing the issue, providing I do NOT mangle all URLs. If I mangle all the URLs, no connection leaks are reported although swiftly Fresco appears to stop loading images altogether which is also bad.

**Comment by kirwan** [comment] 2016-05-18 09:36
I'm still unable to reproduce the bug following the same approach that causes problems for you.

Can you share with me the code where you setup your `OkHttpClient` instance in case something you've set there is related?

**Comment by jmbusby** [comment] 2016-05-18 16:35
Here is our setup code:
```
OkHttpClient client = new OkHttpClient();
client.interceptors().add(new ImageHttpRequestInterceptor());

ImagePipelineConfig config = OkHttpImagePipelineConfigFactory.newBuilder(context, client)
    .setRequestListeners(ImageFetcherConfigHelper.getRequestListeners(mRequestListeners))
    .setDownsampleEnabled(true)
    .build();
Fresco.initialize(context, config);
```
`ImageHttpRequestInterceptor` looks like this:
```
public class ImageHttpRequestInterceptor implements Interceptor
{
	private static final int STATUS_CODE_404 = 404;

	@Override
	public Response intercept(Chain chain) throws IOException
	{
		Request request = chain.request();

		Response response = chain.proceed(request);

		if (response.code() == STATUS_CODE_404)
		{
			logImageLoadFailureToAnalytics(request.urlString(), STATUS_CODE_404);
		}
		return response;
	}
}
```

**Comment by kirwan** [comment] 2016-05-24 18:15
@jmbusby I've confirmed that the addition of the `ImageHttpRequestInterceptor` uncovered this issue and that my fix resolves it in this case. The fix will be merged to master soon.

**Closed** 2016-05-24 19:00 UTC
Labels: bug
