### ISSUE TITLE
Pause and restart processing queue

### ISSUE THREAD

**Issue by karun2189** [facebook/fresco#706] opened 2015-10-27 14:19 UTC
How can i stop processing queue during scroll in listview making smooth scroll ? How can i achieve this?  Thanks

**Comment by massimocarli** [comment] 2015-10-28 10:54
`ImagePipeline` is already design in order to optimize the load of the images. The `Drawee` framework is then optimize to interact with the `ImagePipeline`. Do you have any specific use case? What do you mean with 'stop processing queue'?
Thanks

**Comment by karun2189** [comment] 2015-10-28 12:08
My use case is  : If the image is not available in memory i will create the snapshot based on my views.If i am scrolling at that time may be scroll is stuck....

**Comment by tyronen** [comment] 2015-11-02 16:06
Duplicate of #512

**Closed by tyronen** 2015-11-02 16:06 UTC
Labels: duplicate
