### ISSUE TITLE
Q: animated gif decoding still uses DVM heap and causes OOM issue?

### ISSUE THREAD

**Issue by BHsueh** [facebook/fresco#344] opened 2015-06-04 02:07 UTC
Hi,
We use fresco to download and display many animated gifs in our app(tens of gifs in one scrolled page and many pages can be switched).  We are seeing a lot of gif decoding OOM issue reported from bug reporter like this,

java.lang.OutOfMemoryError
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:718)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:695)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:662)
	at com.facebook.imagepipeline.animated.impl.AnimatedDrawableCachingBackendImpl.createNewBitmap(AnimatedDrawableCachingBackendImpl.java:147)
	at com.facebook.imagepipeline.animated.impl.AnimatedDrawableCachingBackendImpl.obtainBitmapInternal(AnimatedDrawableCachingBackendImpl.java:340)
	at com.facebook.imagepipeline.animated.impl.AnimatedDrawableCachingBackendImpl.runPrefetch(AnimatedDrawableCachingBackendImpl.java:450)
	at com.facebook.imagepipeline.animated.impl.AnimatedDrawableCachingBackendImpl.access$200(AnimatedDrawableCachingBackendImpl.java:52)
	at com.facebook.imagepipeline.animated.impl.AnimatedDrawableCachingBackendImpl$3.call(AnimatedDrawableCachingBackendImpl.java:410)
	at bolts.Task$2.run(Task.java:195)
	at com.facebook.common.executors.ConstrainedExecutorService$Worker.run(ConstrainedExecutorService.java:178)
	at com.facebook.common.executors.SerialDelegatingExecutor.executeSingleCommand(SerialDelegatingExecutor.java:76)
	at com.facebook.common.executors.SerialDelegatingExecutor.access$000(SerialDelegatingExecutor.java:24)
	at com.facebook.common.executors.SerialDelegatingExecutor$1.run(SerialDelegatingExecutor.java:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:856)

So our questions is that gif decoding still is done on DVM heap, not native heap? Is there any plan to support on native heap just like png decoding?

Here is some info about how we use fresco in this case,
We includes fresco as following,
dependencies {
    compile 'com.facebook.fresco:fresco:0.4.0+'
}
final Uri gifUri = Uri.parse(gifUrl);
                DraweeController controller = Fresco.newDraweeControllerBuilder().setUri(gifUri).setAutoPlayAnimations(true).build();
                cache.gifImage.setController(controller);

Please help. Thank you.

**Comment by plamenko** [comment] 2015-06-04 11:28
Duplicate of #159

**Closed** 2015-06-04 11:30 UTC
Labels: bug, duplicate
