### ISSUE TITLE
API report for Fresco

### ISSUE THREAD

**Issue by lvc** [facebook/fresco#1924] opened 2017-10-09 05:15 UTC
Hi,

Here is the report on API changes and backward binary compatibility for the Fresco library: https://abi-laboratory.pro/java/tracker/timeline/fresco/

The report is generated by the https://github.com/lvc/japi-compliance-checker tool for jars at http://central.maven.org/maven2/com/facebook/fresco/fresco/ according to https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Hope it will be helpful for users and maintainers of the library to be aware of past and future API changes.

The tool checks all public API methods and classes. Please let me know if it should not check some parts of the API.

I haven't found a better channel of communication for this (may be www.facebook.com/frescolib is better?). Please skip this message if you don't interested in backward compatibility.

Thank you.

![fresco-2](https://user-images.githubusercontent.com/1517837/31325727-f19e0fe8-acc8-11e7-85b8-a7a360476147.png)
![fresco-1](https://user-images.githubusercontent.com/1517837/31325726-f19d9586-acc8-11e7-92be-32ed8ee526e4.png)

**Comment by lambdapioneer** [comment] 2017-10-09 09:39
Thank you @lvc! This is really interesting and we had a good read :)

For Fresco we have a set of classes/files (e.g. ImageRequest, ImagePipelineConfig) that we consider to form the API of Fresco. Other public classes are only public for internal reasons (splitting up into multiple APKs and similar). Otherwise, we treat them as internal or only for heavy power users.

Is there a way to provide a set of files/classes as a whitelist for this API?

**Comment by lvc** [comment] 2017-10-11 07:24
Hi,

Yes, it's possible to check only specified list of classes. But usually it's better to specify a list of classes/packages/annotations to skip in order to not to skip analysis of newly added public classes in latest versions of the library.

This report is only for fresco.jar. Are you interested to see other Fresco modules in the tracker? Which modules are more important? I can easily run the checker against any of the remaining modules at https://mvnrepository.com/search?q=fresco if you are interested.

Thank you.

**Comment by lambdapioneer** [comment] 2017-10-11 09:56
@lvc, that makes sense. CC @kirwan and @oprisnik  who have a good understanding on which packages and modules are the most critical for end-users.

**Comment by foghina** [comment] 2018-01-17 19:51
This is really cool! I think it would make sense to add most modules to this report, except for `fbcore` probably and all of the `-test` ones.

I'll close this issue for now since it's not a bug or feature request, but we can still respond to any questions/comments.

**Closed by foghina** 2018-01-17 19:51 UTC
