### ISSUE TITLE
Local image with exif rotation and ResizeOptions display's wrong

### ISSUE THREAD

**Issue by dmitrychistyakov** [facebook/fresco#2119] opened 2018-05-25 13:03 UTC
### Description

I have image, token with samsung camera and placed on sd-card. File EXIF rotation is ORIENTATION_ROTATE_90 (6). If I add ResizeOptions to ImageRequestBuilder, the image looks compressed by vertical.

### Reproduction

Here is the sample file
https://www.dropbox.com/s/fsixt3lfbw6zqiv/Exif270.jpg?dl=0
Place it to sd-card root

And here is code

```
public class MainActivity extends AppCompatActivity {

    private static String[] PERMISSIONS_STORAGE = {
            Manifest.permission.READ_EXTERNAL_STORAGE,
            Manifest.permission.WRITE_EXTERNAL_STORAGE
    };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Fresco.initialize(this);

        verifyStoragePermissions(this);

        SimpleDraweeView simpleDraweeView = new SimpleDraweeView(this);
        simpleDraweeView.setLayoutParams(new ViewGroup.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
        File file = new File("/storage/emulated/0/Exif270.jpg");
        ImageRequestBuilder imageRequestBuilder = ImageRequestBuilder.newBuilderWithSource(
                Uri.fromFile(file)).setResizeOptions(ResizeOptions.forDimensions(100, 300));
        PipelineDraweeControllerBuilder controllerBuilder = Fresco.newDraweeControllerBuilder()
                .setImageRequest(imageRequestBuilder.build());
        simpleDraweeView.setController(controllerBuilder.build());
        setContentView(simpleDraweeView);
    }

public static void verifyStoragePermissions(Activity activity) {
        int permission = ActivityCompat.checkSelfPermission(activity, Manifest.permission.WRITE_EXTERNAL_STORAGE);
        if (permission != PackageManager.PERMISSION_GRANTED) {
            ActivityCompat.requestPermissions(activity, PERMISSIONS_STORAGE, 1);
        }
    }
}

```

Screenshot of result
![resize-bug](https://user-images.githubusercontent.com/2329931/40545518-cc1189f6-6034-11e8-8575-689f789a2c7a.png)

Without resizing everything works fine

### Additional Information

* Fresco version: 1.9.0
* Platform version: Android 8.0

**Comment by oprisnik** [comment] 2018-05-25 13:05
Thanks for the bug report. We'll take a look!

**Comment by hetovar** [comment] 2018-06-01 17:38
Hi I will like to contribute but unfortunately I was not able to reproduce the error.

**Comment by florianPOLARSTEPS** [comment] 2018-08-15 09:15
@dmitrychistyakov I have been noticing the same issue. I did some data gathering it issue and it seems like it is rather widespread. Most Samsung devices and a great amount of chinese brands are having these problems (Xiaomi, Huawei, etc ).

**Comment by BorislavKamenov** [comment] 2019-02-23 14:42
The issue still present on version 1.12.0
If ResizeOption is defined, no matter of the value, images taken with camera are shown with wrong orientation.

**Comment by ImportEffort** [comment] 2019-03-26 02:34
If ResizeOption is defined, no matter of the value, images taken with camera are shown with wrong orientation. its torturous。

**Comment by liangxiwei** [comment] 2019-04-11 12:12
I have the same problem

**Comment by oprisnik** [comment] 2021-03-10 10:45
This issue should be fixed. If it is still an issue, please let us know.

**Closed by oprisnik** 2021-03-10 10:45 UTC
Labels: bug, good first issue, help wanted
