### ISSUE TITLE
Load webp animation picture is success，but wait a minute，crash

### ISSUE THREAD

**Issue by wangrunxiang** [facebook/fresco#1950] opened 2017-10-24 07:05 UTC
Load webp animation picture is success，but wait a minute，crash

Android version is 4.4.4, device is Meitu M4

FATAL EXCEPTION: Thread-860
                                                                   Process: com.duowan.mobile, PID: 13315
                                                                   java.lang.RuntimeException: Failed to pin Bitmap
                                                                       at com.facebook.imagepipeline.nativecode.Bitmaps.nativePinBitmap(Native Method)
                                                                       at com.facebook.imagepipeline.nativecode.Bitmaps.pinBitmap(Bitmaps.java:41)
                                                                       at com.facebook.imagepipeline.platform.DalvikPurgeableDecoder.pinBitmap(DalvikPurgeableDecoder.java:156)
                                                                       at com.facebook.imagepipeline.platform.KitKatPurgeableDecoder.pinBitmap(KitKatPurgeableDecoder.java:30)
                                                                       at com.facebook.imagepipeline.platform.DalvikPurgeableDecoder.decodeJPEGFromEncodedImage(DalvikPurgeableDecoder.java:91)
                                                                       at com.facebook.imagepipeline.platform.KitKatPurgeableDecoder.decodeJPEGFromEncodedImage(KitKatPurgeableDecoder.java:30)
                                                                       at com.facebook.imagepipeline.bitmaps.HoneycombBitmapFactory.createBitmapInternal(HoneycombBitmapFactory.java:63)
                                                                       at com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.createBitmap(PlatformBitmapFactory.java:76)
                                                                       at com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.createBitmap(PlatformBitmapFactory.java:43)
                                                                       at com.facebook.fresco.animation.bitmap.preparation.DefaultBitmapFramePreparer$FrameDecodeRunnable.prepareFrameAndCache(DefaultBitmapFramePreparer.java:144)
                                                                       at com.facebook.fresco.animation.bitmap.preparation.DefaultBitmapFramePreparer$FrameDecodeRunnable.prepareFrameAndCache(DefaultBitmapFramePreparer.java:162)
                                                                       at com.facebook.fresco.animation.bitmap.preparation.DefaultBitmapFramePreparer$FrameDecodeRunnable.run(DefaultBitmapFramePreparer.java:112)
                                                                       at com.facebook.common.executors.ConstrainedExecutorService$Worker.run(ConstrainedExecutorService.java:177)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:42)
                                                                       at java.lang.Thread.run(Th

10-24 14:39:25.952 27469-27469/com.duowan.mobile E/ViewRootImpl: Could not lock surface
                                                                 java.lang.IllegalArgumentException
                                                                     at android.view.Surface.nativeLockCanvas(Native Method)
                                                                     at android.view.Surface.lockCanvas(Surface.java:243)
                                                                     at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:2973)
                                                                     at android.view.ViewRootImpl.draw(ViewRootImpl.java:2943)
                                                                     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2780)
                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2390)
                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1262)
                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6408)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:591)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:560)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
                                                                     at android.os.Handler.handleCallback(Handler.java:808)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                     at android.os.Looper.loop(Looper.java:193)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5509)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:835)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:651)
                                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by erikandre** [comment] 2017-10-25 09:31
Hi @wangrunxiang 

1. Does this happen for all webp animations?
2. What is the size of the image?
3. Is this specific to the Meitu M4?

**Comment by wangrunxiang** [comment] 2017-10-25 09:49
Hi @erikandre
     1.not always,it just happed sometimes
     2.image size is alaways less than 100kb
     3.not only Meitu M4， I found an other one  Coolpad dashen F2 ，it also Android version 4.4.4

**Comment by wangrunxiang** [comment] 2017-10-25 09:54
Do I need to not use webp animation picture in Android kitkat

**Comment by wangrunxiang** [comment] 2017-10-25 09:55
Do I need to not use webp animation picture in Android kitkat first？

**Comment by wangrunxiang** [comment] 2017-10-25 10:10
can you help me solve it？

**Comment by wangrunxiang** [comment] 2017-10-25 10:20
java.lang.IllegalStateException: Surface was already locked
	at android.view.Surface.lockCanvas(Surface.java:252)
	at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:2436)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2410)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2254)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1884)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1001)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5622)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
	at android.view.Choreographer.doFrame(Choreographer.java:544)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5217)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by xjy2061** [comment] 2017-10-25 11:54
I encountered same crash as I mentioned in #1929.

**Comment by wangrunxiang** [comment] 2017-10-26 07:33
@xjy2061 How did you solve this problem?

**Comment by disav1** [comment] 2017-10-26 11:50
http://crashes.to/s/afa02cf71db

Had the same problem after updating, had to revert back.
99% is android 4

**Comment by wangrunxiang** [comment] 2017-10-30 06:17
@disav1 which version to revert

**Comment by wangrunxiang** [comment] 2017-10-30 06:19
Hi @erikandre
which version revert to solve this problem

**Comment by disav1** [comment] 2017-10-30 06:22
@wangrunxiang  compile 'com.facebook.fresco:fresco:1.1.0'

**Comment by wangrunxiang** [comment] 2017-10-30 06:45
@disav1  can I use 1.4.0?

**Comment by wangrunxiang** [comment] 2017-10-30 08:55
@disav1 The version 1.1.0 do not has this problem？

**Comment by disav1** [comment] 2017-10-30 09:04
@wangrunxiang 1.1.0 didn't for sure. Above it I haven't tested.

**Comment by Luchangrun** [comment] 2017-10-31 05:49
@wangrunxiang have you solved this problem？I had the same problem in my project when use version 1.5.0

**Comment by wangrunxiang** [comment] 2017-10-31 09:32
@Luchangrun you can try the 1.1.0 version

**Comment by Luchangrun** [comment] 2017-11-01 08:47
@wangrunxiang thank you very much .

**Comment by xjy2061** [comment] 2017-11-02 06:09
https://github.com/xjy2061/NovaImageLoader/commit/272fc25c2dcf4e9180a2d7524689f0efa1c6fee6
https://github.com/xjy2061/NovaImageLoader/commit/3c6a8c67730475525042db0ad0dbe901c88e9ac1

I just catch the exception to avoid crash. @wangrunxiang

**Comment by lambdapioneer** [comment] 2017-11-02 10:44
@xjy2061 do you mind to create a pull-request for this? Ideally, we want to propagate the error to the listeners such that it does not fail too silently.

@oprisnik can probably help with the surrounding animation classes.

**Comment by wangrunxiang** [comment] 2018-01-09 07:15
@oprisnik Have you already repaired this problem in the 1.7.1 version？

**Comment by erikandre** [comment] 2018-01-16 15:54
Closing as duplicate of #1862 which will be fixed in the next release

**Closed by erikandre** 2018-01-16 15:54 UTC
Labels: duplicate
