### ISSUE TITLE
Error inflating class com.facebook.drawee.view.SimpleDraweeView

### ISSUE THREAD

**Issue by AraBisTiC** [facebook/fresco#395] opened 2015-06-20 12:42 UTC
I get the following error on around 2% of devices running my app (https://play.google.com/store/apps/details?id=com.tiikit.tiik) cant seem to sort it. Any thoughts?

My XML looks like this:

```xml
<com.facebook.drawee.view.SimpleDraweeView
                android:id="@+id/imageParseThumb"
                android:layout_width="fill_parent"
                android:layout_height="@dimen/dimImage"
                android:scaleType="centerCrop"
                app:placeholderImage="@drawable/thumbnail_image"
                android:layout_alignParentTop="true"
                android:layout_alignParentLeft="true"/>
```

Stack-trace:

```java
android.view.InflateException: Binary XML file line #24: Error inflating class com.facebook.drawee.view.SimpleDraweeView
       at android.view.LayoutInflater.createView(LayoutInflater.java:617)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:691)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:750)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:753)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
       at com.tiikit.tiik.posts.CardsAdapter.onCreateViewHolder(CardsAdapter.java:128)
       at com.tiikit.tiik.posts.CardsAdapter.onCreateViewHolder(CardsAdapter.java:37)
       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5062)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4368)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4278)
       at android.support.v7.widget.LayoutState.next(LayoutState.java:86)
       at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1415)
       at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:603)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2673)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2971)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:562)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1984)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1805)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1116)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4370)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
       at android.view.Choreographer.doCallbacks(Choreographer.java:555)
       at android.view.Choreographer.doFrame(Choreographer.java:525)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
       at android.os.Handler.handleCallback(Handler.java:667)
       at android.os.Handler.dispatchMessage(Handler.java:112)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4873)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:528)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor._logged_newInstance(Constructor.java:434)
       at android.view.LayoutInflater.createView(LayoutInflater.java:590)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:691)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:750)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:753)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
       at com.tiikit.tiik.posts.CardsAdapter.onCreateViewHolder(CardsAdapter.java:128)
       at com.tiikit.tiik.posts.CardsAdapter.onCreateViewHolder(CardsAdapter.java:37)
       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5062)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4368)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4278)
       at android.support.v7.widget.LayoutState.next(LayoutState.java:86)
       at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1415)
       at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:603)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2673)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2971)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:562)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1984)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1805)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1116)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4370)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
       at android.view.Choreographer.doCallbacks(Choreographer.java:555)
       at android.view.Choreographer.doFrame(Choreographer.java:525)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
       at android.os.Handler.handleCallback(Handler.java:667)
       at android.os.Handler.dispatchMessage(Handler.java:112)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4873)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:528)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NullPointerException
       at com.facebook.drawee.view.DraweeView.toString(DraweeView.java:179)
       at java.lang.StringBuilder.append(StringBuilder.java:202)
       at java.util.AbstractCollection.toString(AbstractCollection.java:383)
       at java.util.Formatter.transform(Formatter.java:1419)
       at java.util.Formatter.doFormat(Formatter.java:1079)
       at java.util.Formatter.format(Formatter.java:1040)
       at java.util.Formatter.format(Formatter.java:1009)
       at java.lang.String.format(String.java:2050)
       at java.lang.String.format(String.java:2024)
       at android.droidblaze.ViewPool.findViewsByIdPair(ViewPool.java:88)
       at android.droidblaze.ViewPool.updateView(ViewPool.java:75)
       at android.view.View.onIDChanged(View.java:11779)
       at android.view.View.<init>(View.java:3590)
       at android.widget.ImageView.<init>(ImageView.java:114)
       at android.widget.ImageView.<init>(ImageView.java:110)
       at com.facebook.drawee.view.DraweeView.<init>(DraweeView.java:51)
       at com.facebook.drawee.view.GenericDraweeView.<init>(GenericDraweeView.java:74)
       at com.facebook.drawee.view.SimpleDraweeView.<init>(SimpleDraweeView.java:58)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor._logged_newInstance(Constructor.java:434)
       at android.view.LayoutInflater.createView(LayoutInflater.java:590)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:691)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:750)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:753)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
       at com.tiikit.tiik.posts.CardsAdapter.onCreateViewHolder(CardsAdapter.java:128)
       at com.tiikit.tiik.posts.CardsAdapter.onCreateViewHolder(CardsAdapter.java:37)
       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5062)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4368)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4278)
       at android.support.v7.widget.LayoutState.next(LayoutState.java:86)
       at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1415)
       at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:603)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2673)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2971)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:562)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:14085)
       at android.view.ViewGroup.layout(ViewGroup.java:4395)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1984)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1805)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1116)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4370)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
       at android.view.Choreographer.doCallbacks(Choreographer.java:555)
       at android.view.Choreographer.doFrame(Choreographer.java:525)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
       at android.os.Handler.handleCallback(Handler.java:667)
       at android.os.Handler.dispatchMessage(Handler.java:112)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4873)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:528)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by BennyWang** [comment] 2015-08-12 03:49
I get this error when I use SimpleDraweeView in a ListView, and it just happen on my XiaoMi phone(android 4.4.4), after I remove placeholderImage attribute, this error gone, you can have a try!

**Comment by plamenko** [comment] 2015-08-18 15:46
Weird.

    Caused by: java.lang.NullPointerException
       at com.facebook.drawee.view.DraweeView.toString(DraweeView.java:179)

**Comment by plamenko** [comment] 2015-08-18 15:49
Looking at the [DraweeView] (https://github.com/facebook/fresco/blob/96d74f385b297f364db1f719dd6ee61fc380d0d4/drawee/src/main/java/com/facebook/drawee/view/DraweeView.java), this can only happen if super class calls `toString` from their constructor which seems odd.

**Comment by plamenko** [comment] 2015-08-18 15:51
We have a fix ready.

**Comment by abhikmitra** [comment] 2015-10-04 19:38
Any idea what is causing this issue ? Even I am getting this issue but have not been able to repro it.

**Comment by IanChilds** [comment] 2015-10-05 08:54
This was fixed in https://github.com/facebook/fresco/commit/80b9ed848582c331f1e00302c896d0be8d11d625

**Closed by IanChilds** 2015-10-05 08:54 UTC
Labels: bug

**Comment by PriyankaKamthe** [comment] 2016-01-05 11:38
I get this error when i run my application on genymotion emulator...please give proper solution to solve this problem.

My XML code : 

<com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/imageView_Splash"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        fresco:actualImageScaleType="fitXY" />

build.gradle : 

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.android.support:design:23.0.0'
    compile 'com.android.support:recyclerview-v7:23.0.0'
    compile 'com.android.support:cardview-v7:23.0.0'
    compile 'com.github.kanytu:android-parallax-recyclerview:v1.4'
    compile 'com.google.android.gms:play-services:7.8.0'
   __compile 'com.facebook.fresco:fresco:0.8.1'__
    compile 'com.github.siyamed:android-shape-imageview:0.9.+@aar'
    compile 'com.google.maps.android:android-maps-utils:0.4+'
}

Java code : 

protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Fresco.initialize(this);
        setContentView(R.layout.activity_splash_screen);
        mImageView =(SimpleDraweeView)findViewById(R.id.imageView_Splash);
        Uri uri = Uri.parse("asset://android_asset/splash.gif");
        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setUri(uri)
                .setAutoPlayAnimations(true)
                .build();
        mImageView.setController(controller);
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                setLogin();
                finish();
            }
        }, SPLASH_TIME_OUT);
    }

I'm not able to find out exactly where I'm going wrong.

**Comment by tyronen** [comment] 2016-01-05 17:35
@PriyankaKamthe please file a new issue.
