### ISSUE TITLE
fresco had lots of unused socket file in proc / pid / fd

### ISSUE THREAD

**Issue by SandyWangWei** [facebook/fresco#1840] opened 2017-07-26 02:11 UTC
when in the use of fresco,we  found that in the proc / pid / fd path there are a lot of socket file handle opened, but after the use of no recovery, resulting in accumulation in the proc / pid / fd socket more and more, ask you Have such a problem encountered?

**Comment by lambdapioneer** [comment] 2017-07-26 09:25
Hi @SandyWangWei, thank you for raising this issue!

Can you provide details on which Android version you have observed this? Ideally some listing of those filedescriptors you are referring to?

**Comment by SandyWangWei** [comment] 2017-07-27 02:22
I'm using Sumsung S4， the Android version is 5.1.1. The pic is the list of filedescriptors ,when I ban the logic about fresco image load, the num decrease obviously.

![image](https://user-images.githubusercontent.com/10043199/28651533-fa5c341e-72b4-11e7-9f8d-261a3e32b99d.png)

**Comment by lambdapioneer** [comment] 2017-07-27 09:34
Hi @SandyWangWei, can you also post the output of `lsof -p $YOUR_PID` here? That allows us to distinguish between unix sockets and TCP sockets.

Which network library are you using (OkHttp?) and does this also reproduce with our sample app?

**Comment by erikandre** [comment] 2018-01-16 11:36
Closing due to no updates from the submitter.

**Closed by erikandre** 2018-01-16 11:36 UTC
Labels: needs-details
