### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by xiaoyao27610** [facebook/fresco#1259] opened 2016-05-31 05:47 UTC
java.lang.OutOfMemoryError
	at android.graphics.Bitmap.nativeCreate(Bitmap.java)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:822)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:799)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:766)
	at com.facebook.imagepipeline.animated.impl.AnimatedDrawableCachingBackendImpl.createNewBitmap(AnimatedDrawableCachingBackendImpl.java:149)
	at com.facebook.imagepipeline.animated.impl.AnimatedDrawableCachingBackendImpl.obtainBitmapInternal(AnimatedDrawableCachingBackendImpl.java:342)
	at com.facebook.imagepipeline.animated.impl.AnimatedDrawableCachingBackendImpl.runPrefetch(AnimatedDrawableCachingBackendImpl.java:452)
	at com.facebook.imagepipeline.animated.impl.AnimatedDrawableCachingBackendImpl.access$200(AnimatedDrawableCachingBackendImpl.java:53)
	at com.facebook.imagepipeline.animated.impl.AnimatedDrawableCachingBackendImpl$3.call(AnimatedDrawableCachingBackendImpl.java:412)
	at bolts.Task$2.run(Task.java:195)
	at com.facebook.common.executors.ConstrainedExecutorService$Worker.run(ConstrainedExecutorService.java:178)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
	at java.lang.Thread.run(Thread.java:841)
----------------------------------------------------------------------------------------------------------------------------------------
the souce AnimatedDrawableCachingBackendImpl.java method createNewBitmap()
 private Bitmap createNewBitmap() {
    FLog.v(TAG, "Creating new bitmap");
    sTotalBitmaps.incrementAndGet();
    FLog.v(TAG, "Total bitmaps: %d", sTotalBitmaps.get());
    return Bitmap.createBitmap(
        mAnimatedDrawableBackend.getRenderedWidth(),
        mAnimatedDrawableBackend.getRenderedHeight(),
        Bitmap.Config.ARGB_8888);
  }
throws outofmemory error.

**Comment by michalgr** [comment] 2016-05-31 12:09
Duplicate of https://github.com/facebook/fresco/issues/159

**Closed by michalgr** 2016-05-31 12:09 UTC
Labels: duplicate
