### ISSUE TITLE
Fresco downSampleSize

### ISSUE THREAD

**Issue by AllenVork** [facebook/fresco#1276] opened 2016-06-06 06:13 UTC
I'm using fresco to load a lot of images and i have configured it with downSampleSize.But after using it, when i wanna show the original image of a thumb, it's muzzy.How could i use downSampleSize dynamically?

**Comment by aagnes** [comment] 2016-06-10 10:11
What do you mean by downSampleSize?

**Comment by hss01248** [comment] 2016-06-21 02:02
do you mean ResizeOptions + Downsampling  ?
if you want the original image and the downsampled bitmap to be different ,give them two different key: append the url with "?xx=yy" or "&xx=yy"

**Comment by erikandre** [comment] 2017-07-11 16:00
Closing as it's not clear what the problem is, and no further information was provided

**Closed by erikandre** 2017-07-11 16:00 UTC
Labels: needs-details
