### ISSUE TITLE
After joining Fresco, other dynamic library error

### ISSUE THREAD

**Issue by caopeng000** [facebook/fresco#716] opened 2015-10-30 09:12 UTC
After joining Fresco, other dynamic library error！other dynamic library will  tell me android UnsatisfiedLinkError错误

**Comment by massimocarli** [comment] 2015-10-30 13:58
Where are you getting that error? Could you provide more information please?
Thanks

**Comment by aagnes** [comment] 2015-10-30 23:27
please check if you have the right NDK path

**Comment by jbaginski** [comment] 2015-11-02 17:02
```
Fatal Exception: java.lang.UnsatisfiedLinkError: Couldn't load memchunk from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.example.app-1.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib, /system/lib/arm]]]: findLibrary returned null
       at java.lang.Runtime.loadLibrary(Runtime.java)
       at java.lang.System.loadLibrary(System.java)
       at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java)
       at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java)
       at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java)
       at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java)
       at com.facebook.imagepipeline.producers.LocalFetchProducer.getByteBufferBackedEncodedImage(LocalFetchProducer.java)
       at com.facebook.imagepipeline.producers.LocalResourceFetchProducer.getEncodedImage(LocalResourceFetchProducer.java)
       at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java)
       at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java)
       at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
       at java.lang.Thread.run(Thread.java)
```

**Comment by jbaginski** [comment] 2015-11-02 17:04
btw. it looks like a duplicate of #410

**Closed** 2015-11-03 17:30 UTC
Labels: duplicate
