### ISSUE TITLE
Delete image given its Uri.

### ISSUE THREAD

**Issue by sdouglas5107** [facebook/fresco#135] opened 2015-04-12 17:39 UTC
My app can change the content it shows periodically, so I delete the data from database, however I could not figure out how to delete the image form disk cache (in order to avoid unnecessary disk storage). Is there any way to do it using Fresco? Thanks in advance.

**Comment by tyronen** [comment] 2015-04-12 19:04
We don't yet support deletion of an individual image.

The cache has a size limit which it does not exceed, and when it comes up against this, old entries will be evicted.

If you are having an actual issue with low disk space, you can use a DiskTrimmableRegistry. See the [instructions](http://frescolib.org/docs/caching.html#trimming-the-caches).

**Comment by sdouglas5107** [comment] 2015-04-12 20:55
Thanks for the answer @tyronen, however I think you should not close this issue, I won't be able to use Fresco if don't find a way to work this around. Regarda

**Comment by sdouglas5107** [comment] 2015-04-12 20:56
Regards*

**Comment by plamenko** [comment] 2015-04-17 00:31
Duplicate of https://github.com/facebook/fresco/issues/124

**Closed by plamenko** 2015-04-17 00:31 UTC
Labels: enhancement
