### ISSUE TITLE
java.lang.NoClassDefFoundError: com/facebook/imagepipeline/memory/NativeMemoryChunk

### ISSUE THREAD

**Issue by LIHAIYI** [facebook/fresco#1847] opened 2017-07-29 08:31 UTC
### Description

 java.lang.NoClassDefFoundError: com/facebook/imagepipeline/memory/NativeMemoryChunk
07-29 16:24:53.811 3688-4266/com.allfootball.news W/System.err:     at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
07-29 16:24:53.811 3688-4266/com.allfootball.news W/System.err:     at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
07-29 16:24:53.811 3688-4266/com.allfootball.news W/System.err:     at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
07-29 16:24:53.811 3688-4266/com.allfootball.news W/System.err:     at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
07-29 16:24:53.811 3688-4266/com.allfootball.news W/System.err:     at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(NativePooledByteBufferFactory.java:141)
07-29 16:24:53.811 3688-4266/com.allfootball.news W/System.err:     at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(NativePooledByteBufferFactory.java:26)
07-29 16:24:53.811 3688-4266/com.allfootball.news W/System.err:     at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:94)
07-29 16:24:53.811 3688-4266/com.allfootball.news W/System.err:     at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(NetworkFetchProducer.java:37)
07-29 16:24:53.811 3688-4266/com.allfootball.news W/System.err:     at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:72)
07-29 16:24:53.811 3688-4266/com.allfootball.news W/System.err:     at com.allfootball.news.fresco.OkHttpNetworkFetcher$2.onResponse(OkHttpNetworkFetcher.java:149)
07-29 16:24:53.811 3688-4266/com.allfootball.news W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
07-29 16:24:53.821 3688-4266/com.allfootball.news W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
07-29 16:24:53.821 3688-4266/com.allfootball.news W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
07-29 16:24:53.821 3688-4266/com.allfootball.news W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
07-29 16:24:53.821 3688-4266/com.allfootball.news W/System.err:     at java.lang.Thread.run(Thread.java:856)

my gradle:

 ndk {
          abiFilters "armeabi"
 }

and i use ReLinker try to solute it,but not success. someone help me.thanks 

### Additional Information

* Fresco version:1.1.0
* Platform version: x86 device and android version 16

**Comment by kirwan** [comment] 2017-07-31 06:30
Have you added our Proguard config? That class is marked as `@DoNotStrip` but unless you include our Proguard rules that will be ignored.

More details on the [Shipping Your App](http://frescolib.org/docs/shipping.html#proguard) page in our docs.

**Comment by kirwan** [comment] 2017-08-02 13:03
This has been asked many times.

See https://github.com/facebook/fresco/search?utf8=%E2%9C%93&q=NoClassDefFoundError+NativeMemoryChunk&type=Issues

**Comment by LIHAIYI** [comment] 2017-08-03 03:08
i had add Proguard config.but The issue is still

**Comment by LIHAIYI** [comment] 2017-08-03 06:35
I have seen many similar issues that you have linked, but there is no solution for this issue!. any solution for this issues？

**Comment by wj495175289** [comment] 2017-08-07 02:20
i also had add Proguard config.but The issue is still

**Comment by kirwan** [comment] 2017-08-07 14:38
OK, let's see if we can find another cause...

Can you answer these questions:

1. What other dependencies do you have?
2. Do you enable multidex?
3. What device(s) and Android version(s) is this on? You said x86 but is it a real device or emulator?
4. Debug or release builds?

**Comment by kirwan** [comment] 2017-08-07 14:45
If you are using Multidex, I suggest following the steps [here](https://developer.android.com/studio/build/multidex.html#mdex-gradle) to ensure you're doing everything correctly.

**Comment by LIHAIYI** [comment] 2017-08-08 03:45
thank you you reply
1. other dependencies is so much
2. yes ,my app is using multidex  and  have right configuration
3. i saw this issue on fabric  and i use emulator  that i can see this issue again.(android version is 16)
4. all of debug and release.

**Comment by LIHAIYI** [comment] 2017-08-08 04:18
Is there any dependencies that conflicts with fresco?

**Comment by kirwan** [comment] 2017-08-08 08:31
I'm not aware of any dependencies that should clash but we saw reports at one time with a particular version of the Google Mobile Services plugin.

With multidex, does your Application class extend `android.support.multidex.MultiDexApplication` or just `Application`?

**Comment by LIHAIYI** [comment] 2017-08-08 08:34
is extend MultiDexApplication

**Comment by efrohnhoefer** [comment] 2017-10-05 17:05
The Gradle config only includes ARM binaries. If you want to run on x86 you need to include x86 binaries. Note: You don't need to include `armeabi` unless you want to support Gingerbread.

Gradle config should read:
```
  ndk {
    abiFilters 'x86', 'x86_64', 'arm64-v8a', 'armeabi-v7a'
  }
```

**Comment by kirwan** [comment] 2017-10-09 08:25
Thanks @efrohnhoefer for noticing the error which I'd missed.

@LIHAIYI I hope that helps you.

**Closed by kirwan** 2017-10-09 08:25 UTC
Labels: duplicate, needs-details
