### ISSUE TITLE
Unknown Image Format for LowLight, HDR, DOF images captured using Samsung S8 Camera.

### ISSUE THREAD

**Issue by MustafaHalimehHH** [facebook/fresco#2070] opened 2018-03-16 16:43 UTC
### Description

I captured Images using the Samsung Camera with different processors (LowLight, HDR, DOF), and then I wanted to display the preview of each image using Fresco, but the there was nothing in the display and the log showed (Unknown Image Forma /image file path/).

### Additional Information

* Fresco version: 1.8.0
* Platform version: CompileSdkVersion 26, Samsung Galaxy S8

**Comment by oprisnik** [comment] 2018-03-16 18:03
Thanks for reporting the issue. Can you add some sample images where this happens so that we can try to reproduce the issue? Thanks!

**Comment by MustafaHalimehHH** [comment] 2018-03-20 16:35
![dof](https://user-images.githubusercontent.com/35146689/37668561-1bea6c1c-2c65-11e8-80ff-ced563795f7a.jpg)
![hdr](https://user-images.githubusercontent.com/35146689/37668563-1c16693e-2c65-11e8-8e71-da0c39302869.jpg)
![lowlight](https://user-images.githubusercontent.com/35146689/37668564-1c359dae-2c65-11e8-88d4-8923adea4f58.jpg)

**Comment by angelkjos** [comment] 2018-06-05 12:49
Hello @MustafaHalimehHH 
Could you please give us more details about the issue you're experiencing. During our tests Fresco loaded your images without any problems from the network and also locally form the sdcard. Please try to reproduce it in the Showcase application or provide code sample/logs. Thanks!

**Comment by oprisnik** [comment] 2018-06-11 15:10
I'm closing this since we cannot reproduce the issue.

**Closed by oprisnik** 2018-06-11 15:10 UTC
Labels: needs-details
