### ISSUE TITLE
No intermediate views are shown for progressive jpeg

### ISSUE THREAD

**Issue by apolatynski** [facebook/fresco#174] opened 2015-04-21 08:51 UTC
When using progressive encoded jpegs, the view doesn't update until the entire image is downloaded.

I'm using fresco 0.3.0 and the code as below.

```java
ImageRequest request = ImageRequestBuilder.newBuilderWithSource(Uri.parse(imageSource))
        .setProgressiveRenderingEnabled(true)
        .build();

DraweeController draweeController = Fresco.newDraweeControllerBuilder()
       .setImageRequest(request)
       .setOldController(draweeView.getController())
       .build();

 draweeView.setMaxWidth(mGalleryWidth);
 draweeView.setMaxHeight(mGalleryHeight);
 draweeView.setController(draweeController);
```

 Info about the tested file:
```
JPEG image is 800w * 600h, 3 color components, 8 bits per sample
JPEG process: Progressive
```

**Comment by tyronen** [comment] 2015-04-21 09:17
Duplicate of #138

**Closed by tyronen** 2015-04-21 09:17 UTC
Labels: duplicate
