### ISSUE TITLE
 java.lang.NoClassDefFoundError: com.facebook.imagepipeline.producers.DiskCacheProducer

### ISSUE THREAD

**Issue by leadersm** [facebook/fresco#1251] opened 2016-05-28 07:56 UTC
05-28 15:54:49.545 19520-19597/? I/art: Explicit concurrent mark sweep GC freed 7880(409KB) AllocSpace objects, 0(0B) LOS objects, 19% free, 16MB/20MB, paused 646us total 15.835ms
05-28 15:54:49.558 19520-19520/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.facebook.imagepipeline.producers.DiskCacheProducer$1>
05-28 15:54:49.576 19520-19598/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.facebook.imagepipeline.producers.DiskCacheProducer$1>
05-28 15:54:49.578 19520-19599/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.facebook.imagepipeline.producers.DiskCacheProducer$1>
05-28 15:54:49.609 19520-19598/? E/AndroidRuntime: FATAL EXCEPTION: Thread-383
                                                   Process: com.yty.minerva, PID: 19520
                                                   java.lang.NoClassDefFoundError: com.facebook.imagepipeline.producers.DiskCacheProducer$1
                                                       at com.facebook.imagepipeline.producers.DiskCacheProducer.produceResults(DiskCacheProducer.java:75)
                                                       at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer.produceResults(EncodedMemoryCacheProducer.java:125)
                                                       at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.startInputProducerIfHasAttachedConsumers(MultiplexProducer.java:336)
                                                       at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.access$000(MultiplexProducer.java:125)
                                                       at com.facebook.imagepipeline.producers.MultiplexProducer.produceResults(MultiplexProducer.java:87)
                                                       at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer.produceResults(AddImageTransformMetaDataProducer.java:29)
                                                       at com.facebook.imagepipeline.producers.ResizeAndRotateProducer.produceResults(ResizeAndRotateProducer.java:69)
                                                       at com.facebook.imagepipeline.producers.DecodeProducer.produceResults(DecodeProducer.java:94)
                                                       at com.facebook.imagepipeline.producers.BitmapMemoryCacheProducer.produceResults(BitmapMemoryCacheProducer.java:87)
                                                       at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.startInputProducerIfHasAttachedConsumers(MultiplexProducer.java:336)
                                                       at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.access$000(MultiplexProducer.java:125)
                                                       at com.facebook.imagepipeline.producers.MultiplexProducer.produceResults(MultiplexProducer.java:87)
                                                       at com.facebook.imagepipeline.producers.ThreadHandoffProducer$1.onSuccess(ThreadHandoffProducer.java:46)
                                                       at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:54)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                       at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by oprisnik** [comment] 2016-05-28 14:56
Do you build Fresco from source or include the .AARs?
Did you set up Fresco correctly (calling `Fresco.initialize(...)` exactly one time, see #1234)?
Does this only happen for specific images and can you reproduce the error all the time or just sporadic?

**Comment by oprisnik** [comment] 2017-11-07 11:40
I'm closing this issue since it's more than a year old. Feel free to comment if this is still an issue.

**Closed by oprisnik** 2017-11-07 11:40 UTC
Labels: needs-details
