### ISSUE TITLE
Placeholder transparency doesn't work properly with background.

### ISSUE THREAD

**Issue by krottv** [facebook/fresco#1939] opened 2017-10-18 12:56 UTC
### Description

I want to set placeholder and background to the image. The issue is that my placeholder is an icon on transparent background. And regions of the icon crops background. It is very vague in words, but please look at the attached picture and everything will become clear.
https://yadi.sk/i/xUFRLHlv3Nrsss
Compare with expected result - https://yadi.sk/i/RJ-tRu9l3Nrtw4

### Code

`
                  
                 final SimpleDraweeView imageView = new SimpleDraweeView(getActivity(), 
                 GenericDraweeHierarchyBuilder.newInstance(getResources())
                .setFadeDuration(400)
                .setRoundingParams(RoundingParams.fromCornersRadius(RUtils.convertDpToPixels(5)))
                .setPlaceholderImage(RUtils.getDrFromAttr(R.attr.dialog_cover_image_loading, getActivity()))
                .setBackground(RUtils.getDrFromAttr(R.attr.dialog_cover_image_background, getActivity()))
                .build());
        imageView.setId(id);

        ImageRequest request = ImageRequestBuilder
                .newBuilderWithSource(Uri.parse(url))
                .disableDiskCache()
                .build();

        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setImageRequest(request)
                .build();

        imageView.setController(controller);`

### Additional Information

* Fresco version: 1.5.0
* Platform version:  Tested on Android 6.0 and Android 8.0

**Comment by oprisnik** [comment] 2017-10-18 13:22
Thanks for reporting this issue. It seems to be related to #1905 where we also have wrong alpha values with overlays. We do not properly propagate these values right now.

**Comment by oprisnik** [comment] 2018-01-16 17:29
The images don't load any more, so I'm assuming this is a duplicate of #1905

**Closed by oprisnik** 2018-01-16 17:29 UTC
Labels: bug, starter-task
