### ISSUE TITLE
Updating Fresco sources from master seems to make animated-webp needed (API 10 - download webp pictures)

### ISSUE THREAD

**Issue by eldk** [facebook/fresco#1462] opened 2016-09-07 15:17 UTC
Hello,

I've updated my repo (https://github.com/eldk/fresco - up to this commit https://github.com/facebook/fresco/commit/93d5a4c81c8b4b1bb9e5a1f874851969d06a3a0f ) from Fresco master sources.

Building my app is ok.

But, on run, when webp transcode is done (to a non animated webp), app crash with this error message : 

>FATAL EXCEPTION: Thread-17
                                                                               java.lang.NoClassDefFoundError: com.facebook.animated.webp.WebPImage
                                                                                   at java.lang.Runtime.nativeLoad(Native Method)
                                                                                   at java.lang.Runtime.loadLibrary(Runtime.java:432)
                                                                                   at java.lang.System.loadLibrary(System.java:554)
                                                                                   at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:32)
                                                                                   at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
                                                                                   at com.facebook.imagepipeline.nativecode.StaticWebpNativeLoader.ensure(StaticWebpNativeLoader.java:35)
                                                                                   at com.facebook.imagepipeline.nativecode.WebpTranscoderImpl.transcodeWebpToJpeg(WebpTranscoderImpl.java:57)
                                                                                   at com.facebook.imagepipeline.producers.WebpTranscodeProducer.doTranscode(WebpTranscodeProducer.java:185)
                                                                                   at com.facebook.imagepipeline.producers.WebpTranscodeProducer.access$300(WebpTranscodeProducer.java:38)
                                                                                   at com.facebook.imagepipeline.producers.WebpTranscodeProducer$1.getResult(WebpTranscodeProducer.java:111)
                                                                                   at com.facebook.imagepipeline.producers.WebpTranscodeProducer$1.getResult(WebpTranscodeProducer.java:106)
                                                                                   at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:45)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
                                                                                   at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
                                                                                   at java.lang.Thread.run(Thread.java:1019)
                                                                                Caused by: java.lang.ClassNotFoundException: com.facebook.animated.webp.WebPImage in loader dalvik.system.PathClassLoader[/data/app/net.opalesurfcasting.lamaille-2.apk]
                                                                                   at dalvik.system.PathClassLoader.findClass(PathClassLoader.java:240)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:551)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:511

Thanks,

Eric

PS : I try now to add module animated-webp to my project as a workaround

**Comment by kirwan** [comment] 2016-09-08 15:27
Thanks for raising this issue @eldk. We've found the cause and it will be fixed shortly.

**Comment by massimocarli** [comment] 2016-09-08 15:47
Hi @eldk,
the error is [here](https://github.com/facebook/fresco/blob/master/static-webp/src/main/jni/static-webp/webp_bitmapfactory.cpp#L356):

```
  // We do this only if a class in animated-webp is present in the classpath
  jclass animatedWebpClass = env->FindClass("com/facebook/animated/webp/WebPImage");
  if (animatedWebpClass) {
    if (initWebPImage(env) != JNI_OK) {
      return -1;
    }
  }
```

If the class is not present we have to clear the exception and so doing this:

```
  // We do this only if a class in animated-webp is present in the classpath
  jclass animatedWebpClass = env->FindClass("com/facebook/animated/webp/WebPImage");
  if (animatedWebpClass) {
    if (initWebPImage(env) != JNI_OK) {
      return -1;
    }
  } else {
     jboolean flag = env->ExceptionCheck();
     if (flag) {
        env->ExceptionClear();
     }
  }
```
We'll release a patch soon
Thanks

**Comment by eldk** [comment] 2016-09-08 17:13
Thanks @kirwan and @massimocarli

**Closed** 2016-09-15 15:30 UTC
Labels: bug
