### ISSUE TITLE
com.facebook.imagepipeline.nativecode.Bitmaps.nativePinBitmap (Bitmaps.java)

### ISSUE THREAD

**Issue by ShushanManandyan** [facebook/fresco#1962] opened 2017-11-06 07:15 UTC
com.facebook.imagepipeline.nativecode.Bitmaps.nativePinBitmap (Bitmaps.java)

  | com.facebook.imagepipeline.nativecode.Bitmaps.pinBitmap (Bitmaps.java:41)
  | com.facebook.imagepipeline.platform.DalvikPurgeableDecoder.pinBitmap (DalvikPurgeableDecoder.java:156)
  | com.facebook.imagepipeline.platform.KitKatPurgeableDecoder.pinBitmap (KitKatPurgeableDecoder.java:30)
  | com.facebook.imagepipeline.platform.DalvikPurgeableDecoder.decodeJPEGFromEncodedImage (DalvikPurgeableDecoder.java:91)
  | com.facebook.imagepipeline.platform.KitKatPurgeableDecoder.decodeJPEGFromEncodedImage (KitKatPurgeableDecoder.java:30)
  | com.facebook.imagepipeline.bitmaps.HoneycombBitmapFactory.createBitmapInternal (HoneycombBitmapFactory.java:63)
  | com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.createBitmap (PlatformBitmapFactory.java:76)
  | com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.createBitmap (PlatformBitmapFactory.java:43)
  | com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrameOrFallback (BitmapAnimationBackend.java:207)
  | com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrameOrFallback (BitmapAnimationBackend.java:229)
  | com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrameOrFallback (BitmapAnimationBackend.java:229)
  | com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrame (BitmapAnimationBackend.java:164)
  | com.facebook.fresco.animation.backend.AnimationBackendDelegate.drawFrame (AnimationBackendDelegate.java:61)
  | com.facebook.fresco.animation.backend.AnimationBackendDelegateWithInactivityCheck.drawFrame (AnimationBackendDelegateWithInactivityCheck.java:111)
  | com.facebook.fresco.animation.drawable.AnimatedDrawable2.draw (AnimatedDrawable2.java:204)
  | com.facebook.drawee.drawable.ForwardingDrawable.draw (ForwardingDrawable.java:147)
  | com.facebook.drawee.drawable.ForwardingDrawable.draw (ForwardingDrawable.java:147)
  | com.facebook.drawee.drawable.ScaleTypeDrawable.draw (ScaleTypeDrawable.java:125)
  | com.facebook.drawee.drawable.FadeDrawable.drawDrawableWithAlpha (FadeDrawable.java:304)
  | com.facebook.drawee.drawable.FadeDrawable.draw (FadeDrawable.java:291)
  | com.facebook.drawee.drawable.ForwardingDrawable.draw (ForwardingDrawable.java:147)
  | com.facebook.drawee.generic.RootDrawable.draw (RootDrawable.java:83)
  | android.widget.ImageView.onDraw (ImageView.java:1019)
  | dalvik.system.NativeStart.main (NativeStart.java)

[FILL THIS OUT: Explain what you did, what you expected to happen, and what actually happens.]
[com.sticker_market_gboard_issue_5_crash_5A005E590309000146A63E31F04DE8F3_749d0bdbc2f311e7a85356847afe9799_0_v2.txt](https://github.com/facebook/fresco/files/1447356/com.sticker_market_gboard_issue_5_crash_5A005E590309000146A63E31F04DE8F3_749d0bdbc2f311e7a85356847afe9799_0_v2.txt)

### Reproduction

[https://play.google.com/store/apps/details?id=com.sticker_market&hl=en.]

### Solution

[OPTIONAL: Do you know what needs to be done to address this issue? Ideally, provide a pull request which fixes this issue.]

### Additional Information

* Fresco version: [1.5.0]
* Platform version: [HTC
HTC Desire EYE   OS 4.2.2/4.4.4

Motorolla
Moto X (1st Gen) OS 4.2.2/4.4.4
Droid Ultra OS .4.2.2/4.4.4

Huawei
Honor3 OS 4.2.2/4.4.4
Che2-L11 OS 4.2.2/4.4.4

TCT
ONE_TOUCH_P310X OS 4.2.2/4.4.4]

**Comment by oprisnik** [comment] 2017-11-06 17:46
Please fill out the template.

**Comment by ShushanManandyan** [comment] 2017-11-06 18:07
How can I edit template?

Additional Information

 version 
    compile "com.facebook.fresco:imagepipeline-okhttp3:1.5.0"
    compile 'com.facebook.fresco:animated-gif:1.5.0'
    compile('com.facebook.fresco:fresco:1.5.0') {
        exclude group: 'com.parse.bolts', module: 'bolts-tasks'
    }

devices
HTC
   HTC Desire EYE  op.sys. 4.2.2/4.4.4

Motorolla
Moto X (1st Gen) op.sys.4.2.2/4.4.4
Droid Ultra op.sys.4.2.2/4.4.4

Huawei
Honor3 op.sys.4.2.2/4.4.4
Che2-L11 op.sys.4.2.2/4.4.4

TCT
ONE_TOUCH_P310X op.sys.4.2.2/4.4.4

[com.sticker_market_gboard_issue_5_crash_5A005E590309000146A63E31F04DE8F3_749d0bdbc2f311e7a85356847afe9799_0_v2.txt](https://github.com/facebook/fresco/files/1447297/com.sticker_market_gboard_issue_5_crash_5A005E590309000146A63E31F04DE8F3_749d0bdbc2f311e7a85356847afe9799_0_v2.txt)
Reproduction
application https://play.google.com/store/apps/details?id=com.sticker_market&hl=en

**Comment by oprisnik** [comment] 2017-11-06 18:10
There is an "edit post icon" at the top right of the post.

Does this happen when you are displaying animated GIFs / WebPs? How are you using Fresco?

**Comment by ShushanManandyan** [comment] 2017-11-06 18:23
Yes this happens when displaying animated GIFs (we are not using webP).We are using Fresco to display animated GIFs and static images (png, jpg).

**Comment by oprisnik** [comment] 2017-11-06 18:59
In that case, this looks like a duplicate of #1950. Please check the discussion there.

**Closed by oprisnik** 2017-11-06 18:59 UTC
Labels: needs-details
