### ISSUE TITLE
SharedElement issue in API 24+

### ISSUE THREAD

**Issue by yuyashuai** [facebook/fresco#1780] opened 2017-05-25 07:08 UTC
### Description
I follow the example of  [transition](https://github.com/facebook/fresco/tree/master/samples/transition) to set `Shared Transition` . it works fine in API 21-24，but have some problems in API 24+ . when i exit an Activity the source `SimpleDraweeView` will turn white.
### Reproduction
[IssueImage](http://makeagif.com/i/61dl8O)
### Additional Information

* Fresco version: [1.3.0]
* Platform version: [ API24 HUAWEI M3]

**Comment by oprisnik** [comment] 2017-05-25 09:23
Duplicate of #1445

**Closed by oprisnik** 2017-05-25 09:23 UTC

**Comment by yuyashuai** [comment] 2017-05-25 10:12
never `setVisibility` `GONE` in API 24+，it make the  transition invalid ，even you set it 'VISIBLE' when exit an activity。
