### ISSUE TITLE
finished with non-zero exit value 2

### ISSUE THREAD

**Issue by chenyusheng** [facebook/fresco#1146] opened 2016-04-22 09:36 UTC
when i using fresco ,then there is a error:
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.7.0_79\bin\java.exe'' finished with non-zero exit value 2

i do know it is maybe cause by i have include two same jar.but i do not know what jar fresco have include,so i cant fix the error well.those is my include:can you help me?

 compile project(':Android-PullToRefreshLibrary')
    compile project(':ViewPagerIndicatorLibrary')
    compile 'com.github.lzyzsd:jsbridge:1.0.2'
    compile 'de.greenrobot:eventbus:2.4.0'
    apt "org.androidannotations:androidannotations:$AAVersion"
    compile "org.androidannotations:androidannotations-api:$AAVersion"
    //    compile 'com.loopj.android:android-async-http:1.4.9'
    //    compile(name:'MagicWindowSDK', ext:'aar')
    compile files('libs/okhttp-2.6.0-leancloud.jar')
    compile files('libs/okio-1.6.0-leancloud.jar')
    compile files('libs/okio-1.6.0.jar')
    compile files('libs/okhttp-2.7.0.jar')
    //    compile 'com.newrelic.agent.android:android-agent:5.+'
    compile 'com.facebook.fresco:fresco:0.5.0+'
    compile 'com.facebook.fresco:drawee:0.5.0+'
    compile 'com.facebook.fresco:fbcore:0.5.0+'
    compile 'com.facebook.fresco:imagepipeline:0.5.0+'
    compile 'com.facebook.fresco:imagepipeline-okhttp:0.5.0'

**Comment by kirwan** [comment] 2016-04-22 09:47
You have quite a few libraries there so I wonder if the 65k method limit is the cause.

A quick search showed this StackOverflow answer which I think will help you. http://stackoverflow.com/a/30692005

**Comment by chenyusheng** [comment] 2016-04-22 09:52
ok，i will try it again.thank you very much!

**Comment by kirwan** [comment] 2016-04-22 12:18
No problem. I'll close the issue but feel free to re-open if the problem continues.

**Closed by kirwan** 2016-04-22 12:18 UTC
