### ISSUE TITLE
setProgressBarImage is not supports anim_list pictures collection,

### ISSUE THREAD

**Issue by yuehongwei** [facebook/fresco#1794] opened 2017-06-08 11:16 UTC
GenericDraweeHierarchy hierarchy =builder.setProgressBarImage(ContextCompat.getDrawable(context, R.drawable.loading_animation)).setActualImageScaleType(ScalingUtils.ScaleType.FIT_CENTER).build(); 
... .setUri(url) 
 simpleDraweeView.setHierarchy(hierarchy);

this animation is not working .
this  loading_animation.xml

<?xml version="1.0" encoding="utf-8"?>
<animation-list xmlns:android="http://schemas.android.com/apk/res/android"
    android:oneshot="false">
    <item
        android:drawable="@mipmap/chat_detail_input_box_play5"
        android:duration="200" />
    <item
        android:drawable="@mipmap/chat_detail_input_box_play1"
        android:duration="400" />
</animation-list>

**Comment by erikandre** [comment] 2017-06-08 13:38
Hi @yuehongwei !

What is the content of loading_animation.xml?

**Comment by yuehongwei** [comment] 2017-06-09 00:46
<?xml version="1.0" encoding="utf-8"?>
<animation-list xmlns:android="http://schemas.android.com/apk/res/android"
    android:oneshot="false">
    <item
        android:drawable="@mipmap/chat_detail_input_box_play5"
        android:duration="200" />
    <item
        android:drawable="@mipmap/chat_detail_input_box_play1"
        android:duration="400" />
    <items
        android:drawable="@mipmap/chat_detail_input_box_play2"
        android:duration="400" />
    <item
        android:drawable="@mipmap/chat_detail_input_box_play3"
        android:duration="400" />
    <item
        android:drawable="@mipmap/chat_detail_input_box_play4"
        android:duration="400" />
    <item
        android:drawable="@mipmap/chat_detail_input_box_play5"
        android:duration="400" />
</animation-list>

**Comment by yuehongwei** [comment] 2017-06-09 00:46
## <?xml version="1.0" encoding="utf-8"?>
<animation-list xmlns:android="http://schemas.android.com/apk/res/android"
    android:oneshot="false">
    <item
        android:drawable="@mipmap/chat_detail_input_box_play5"
        android:duration="200" />
    <item
        android:drawable="@mipmap/chat_detail_input_box_play1"
        android:duration="400" />
    <items
        android:drawable="@mipmap/chat_detail_input_box_play2"
        android:duration="400" />
    <item
        android:drawable="@mipmap/chat_detail_input_box_play3"
        android:duration="400" />
    <item
        android:drawable="@mipmap/chat_detail_input_box_play4"
        android:duration="400" />
    <item
        android:drawable="@mipmap/chat_detail_input_box_play5"
        android:duration="400" />
</animation-list>

**Comment by yuehongwei** [comment] 2017-06-09 00:46
`<?xml version="1.0" encoding="utf-8"?>
<animation-list xmlns:android="http://schemas.android.com/apk/res/android"
    android:oneshot="false">
    <item
        android:drawable="@mipmap/chat_detail_input_box_play5"
        android:duration="200" />
    <item
        android:drawable="@mipmap/chat_detail_input_box_play1"
        android:duration="400" />
    <items
        android:drawable="@mipmap/chat_detail_input_box_play2"
        android:duration="400" />
    <item
        android:drawable="@mipmap/chat_detail_input_box_play3"
        android:duration="400" />
    <item
        android:drawable="@mipmap/chat_detail_input_box_play4"
        android:duration="400" />
    <item
        android:drawable="@mipmap/chat_detail_input_box_play5"
        android:duration="400" />
</animation-list>
`

**Comment by yuehongwei** [comment] 2017-06-09 00:53
i have a queastion,setProgressBarImage  Whether it is supported .gif picture.

**Comment by erikandre** [comment] 2017-06-09 14:27
Thanks @yuehongwei ! I can reproduce the problem in the sample app using the animated drawable.

No, gifs are not supported as drawables

**Comment by erikandre** [comment] 2017-06-09 14:39
@yuehongwei , please try the following to start the animation:

```
GenericDraweeHierarchyBuilder builder = new GenericDraweeHierarchyBuilder(getResources());
    AnimationDrawable drawable =
        (AnimationDrawable) getResources().getDrawable(R.drawable.placholder);
    builder.setPlaceholderImage(drawable);
    simpleDraweeView.setHierarchy(builder.build());
    drawable.start();
    simpleDraweeView.setImageURI(URI);
```

**Comment by yuehongwei** [comment] 2017-06-12 01:34
thank you very much！

**Comment by erikandre** [comment] 2017-07-10 16:52
Closing this since the workaround should be enough to cover this use case.

**Closed by erikandre** 2017-07-10 16:52 UTC
