### ISSUE TITLE
How can I only use its function of getting and recycling images in my app?Thanks.

### ISSUE THREAD

**Issue by aiuuyoyo** [facebook/fresco#485] opened 2015-07-23 11:56 UTC

**Comment by IanChilds** [comment] 2015-07-23 16:14
Duplicate of #484

**Closed by IanChilds** 2015-07-23 16:14 UTC

**Comment by aiuuyoyo** [comment] 2015-07-24 13:19
I found that to use ImagePipeline can realise it.Now I want to if I can rule how to decode images
