### ISSUE TITLE
Android Dex error in Intellij

### ISSUE THREAD

**Issue by wy353208214** [facebook/fresco#359] opened 2015-06-09 09:23 UTC
Hi,
    when i import the four Moudle( drawee, fbcore, fresco, imagepipeline ) in my project with Intellij idea, it always cause Android Dex error, and i delete the support_v4 which is a mulit jar,  but the issue remains the same. And the error log is : 

![qq 20150609172233](https://cloud.githubusercontent.com/assets/3038374/8054560/42ae3f36-0ecc-11e5-88fd-773362a80f3f.png)

**Comment by wy353208214** [comment] 2015-06-09 09:25
when i use eclipse it's OK, i don't know which jar is mulit.

**Comment by oprisnik** [comment] 2016-12-12 13:47
I'm closing this issue since this has been opened a while ago and there are newer IntelliJ versions and we cannot reproduce the issue. Feel free to comment here if this is still a problem for you.

**Closed by oprisnik** 2016-12-12 13:47 UTC
Labels: build
