### ISSUE TITLE
Fresco + Realm.io library error

### ISSUE THREAD

**Issue by chonamdoo** [facebook/fresco#279] opened 2015-05-16 03:16 UTC
i use     compile 'com.facebook.fresco:fresco:0.5.0+' 

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/multiwindow.jar", zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.couchgram.privacycall-1/base.apk"],nativeLibraryDirectories=[/data/app/com.couchgram.privacycall-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libmemchunk.so"
            at java.lang.Runtime.loadLibrary(Runtime.java:366)
            at java.lang.System.loadLibrary(System.java:989)
            at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:34)
            at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
            at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:36)
            at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
            at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
            at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:260)
            at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
            at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:36)
            at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:59)
            at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:26)
            at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:58)
            at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:49)
            at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:45)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by IanChilds** [comment] 2015-05-18 09:28
Did you follow all the instructions in here: http://frescolib.org/docs/building-from-source.html#configuring-gradle

**Comment by michalgr** [comment] 2015-05-18 11:03
duplicate of https://github.com/facebook/fresco/issues/237

**Closed by michalgr** 2015-05-18 11:03 UTC
Labels: build, duplicate, needs-details
