### ISSUE TITLE
GIF 如何设置 缓存图中的占位图

### ISSUE THREAD

**Issue by z8806c** [facebook/fresco#1705] opened 2017-03-20 08:24 UTC
GIF 如何设置 缓存图中的占位图

**Comment by oprisnik** [comment] 2017-03-21 10:21
Can you please aks the question in English? Google translate doesn't really translate your issue well. Something related to placeholders?

**Comment by nirack** [comment] 2017-03-22 03:25
he probably want's to know how to set placeholders for GIFs in memory cache

**Comment by oprisnik** [comment] 2017-03-22 10:33
I guess this is a duplicate of #480 then. Let me know if that's not the case and I'll re-open this issue.

**Closed by oprisnik** 2017-03-22 10:33 UTC
Labels: needs-details
