### ISSUE TITLE
Use gridview  load so many pictures. about over 30 pictures. OOM

### ISSUE THREAD

**Issue by johnzheng00** [facebook/fresco#304] opened 2015-05-23 17:58 UTC
Use gridview or RecyclerView load so many pictures. about over 30 pictures. the 30 pics all in the Screen.  and scroll the gridview or RecyclerView Frequently. (Nexus 5   5.1)
'I/Choreographer﹕ Skipped 32 frames!  The application may be doing too much work on its main thread.'

**Comment by johnzheng00** [comment] 2015-05-23 18:56
Please quickly fix it.

**Comment by johnzheng00** [comment] 2015-05-24 04:39
ok-http and pipe is same bad for load more pics!  Use volley is okay. universal  image loader is good.

**Comment by IanChilds** [comment] 2015-05-25 07:14
Looks like a duplicate of #84

**Closed by IanChilds** 2015-05-25 07:14 UTC
Labels: duplicate
