### ISSUE TITLE
W/unknown:CloseableReference﹕Finalized without closing in logcat

### ISSUE THREAD

**Issue by coderlin** [facebook/fresco#314] opened 2015-05-26 08:12 UTC
hi fresco,
I have got logcat like this

W/unknown:CloseableReference﹕ Finalized without closing: 263cc769 30d915ee (type = NativePooledByteBuffer)
W/unknown:CloseableReference﹕ Finalized without closing: 30c57b20 a595cd9 (type = NativePooledByteBuffer)
W/unknown:CloseableReference﹕ Finalized without closing: b2cd69e 7afb57f (type = NativePooledByteBuffer)
W/unknown:CloseableReference﹕ Finalized without closing: 2e57294c 679ed95 (type = NativePooledByteBuffer)

am I forget to do something?

**Comment by TarangS** [comment] 2015-05-26 15:50
You are probably not using closing the CloseableReference properly. Please refer to http://frescolib.org/docs/closeable-references.html#_ for the proper usage.

**Closed** 2015-05-26 15:56 UTC

**Comment by coderlin** [comment] 2015-05-27 06:59
I edit my code like this, but still show me that logical, can anybody tell me how to fix it?

ImageRequest imageRequest = ImageRequestBuilder.newBuilderWithSource(uri)
                .setResizeOptions(new ResizeOptions(width, height))
                .build();
        ImagePipeline imagePipeline = Fresco.getImagePipeline();
        final DataSource<CloseableReference<CloseableImage>> dataSource = imagePipeline.fetchImageFromBitmapCache(imageRequest, simpleDraweeView);
        PipelineDraweeController controller = (PipelineDraweeController) Fresco.newDraweeControllerBuilder()
                .setImageRequest(imageRequest)
                .setAutoPlayAnimations(true)
                .setOldController(simpleDraweeView.getController())
                .setControllerListener(new BaseControllerListener<ImageInfo>() {
                    @Override
                    public void onFinalImageSet(String id, ImageInfo imageInfo, Animatable animatable) {
                        CloseableReference<CloseableImage> imageReference = dataSource.getResult();
                        try {
                            if (imageReference != null) {
                                CloseableImage image = imageReference.get();
                                if (image != null && image instanceof CloseableStaticBitmap) {
                                    CloseableStaticBitmap closeableStaticBitmap = (CloseableStaticBitmap) image;
                                    Bitmap bitmap = closeableStaticBitmap.getUnderlyingBitmap();
                                    if (bitmap != null) {
                                        simpleDraweeView.setImageBitmap(bitmap);
                                    }
                                }
                            }
                        } finally {
                            dataSource.close();
                            CloseableReference.closeSafely(imageReference);
                        }
                    }
                })
                .build();
        simpleDraweeView.setController(controller);

**Comment by TarangS** [comment] 2015-05-27 09:11
You dont need to use the Imagepipeline explicitly. SimpleDraweeView does it for you. Also if you use the SimpleDraweeView then you dont have to worry about closing the references as DraweeHierarchy in the SimpleDraweeView handles that. 

In your code snippet, a ControllerListener is not required
So effectively you only need to do:
________________________________________________
Uri uri;
DraweeController controller = Fresco.newDraweeControllerBuilder()
    .setUri(uri)
    .setAutoPlayAnimations(true)
    . // other setters
    .build();
mSimpleDraweeView.setController(controller);
___________________________________________

For Understanding Drawee better read these, however you only need anything other than the above snippet for ur purpose.
http://frescolib.org/docs/using-drawees-xml.html#_
http://frescolib.org/docs/using-drawees-code.html#_
http://frescolib.org/docs/animations.html#_
http://frescolib.org/docs/using-controllerbuilder.html#_

**Comment by Zhuinden** [comment] 2015-11-15 13:59
I am using `SimpleDraweeView` and if the code calls `draweeView.setImageUri(Uri)` multiple times, I get errors like this one

    11-15 14:57:10.304  24258-24267/my.application W/unknown:CloseableReference﹕ Finalized without closing: 41fa4a40 420fa518 (type = CloseableStaticBitmap)

I'm reusing the drawee view in a recycler view, so this should be normal usage.

**Comment by radheshyamsingh24** [comment] 2015-12-07 19:17
I am also getting same issue as Zhuinden. Can you please help us to overcome this issue. i am using lib to show gif images in grid view. Thanks in advance.

**Comment by vad-zuev** [comment] 2015-12-28 10:10
@Zhuinden confirmed, same thing on a Galaxy Tab A (SM-T550), 5.0.2 and Nexus 5 2013 (6.0.1). Would be nice to know the reason.

**Comment by QiuSean** [comment] 2016-02-19 03:32
I am code :
Uri uri = Uri.fromFile(new File(path));
        ImageRequestBuilder imageRequestBuilder = ImageRequestBuilder.newBuilderWithSource(uri)
                .setAutoRotateEnabled(true)
                .setResizeOptions(new ResizeOptions(mItemWidth, mItemWidth));
        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setImageRequest(imageRequestBuilder.build())
                .setOldController(holder.mImageView.getController())
                .build();
        holder.mImageView.setController(controller);
has the same bug

**Comment by leeyc09** [comment] 2016-08-03 02:01
is it fix?

**Comment by oprisnik** [comment] 2016-08-03 11:07
The original cause here should be fixed. However, this also happens if you re-initialize Fresco (call `Fresco.initialize(...)`) more than once. I guess you're doing that according to your other issue (#1397).
