### ISSUE TITLE
Autorotation not working with small Resizeoptions dimensions

### ISSUE THREAD

**Issue by florianPOLARSTEPS** [facebook/fresco#1866] opened 2017-08-14 08:11 UTC
### Description

I am trying to load a lot of small images in a grid and in order to do so, I was trying to load them really small... 60x60 px using the ResizeOptions. I am also using AutoRotate options to load those images to display them correctly. 

What I have noticed is that, only above a certain pixel amount the RotateOptions start working correctly. That pixel ratio is about 200x200 px. I have tried both, downsampling enabled and disabled, since I have seen there was a bug related to downsampling in the past.

Is there a reason for that requirement, or is this a bug?

### Reproduction

Load any local image using the "content://" scheme, which requires to be rotated when displaying using the following parameters:

ResizeOptions(60,60)
RotateOptions.autoRotate()

### Additional Information

* Fresco version: 1.4.0
* Platform version: Tested on 6.0, 7.1 various devices.

**Comment by kirwan** [comment] 2017-08-14 12:54
Almost certainly this is because the smaller images are being loaded from a thumbnail and that misses the `ResizeAndRotateProducer` on the way back.

We'd probably have to review the producer chain to ensure this works correctly.

**Comment by florianPOLARSTEPS** [comment] 2017-08-14 15:25
thanks for the quick response: @kirwan. Seems reasonable. I am guessing the reason not to include that producer in the first place is performance related?

Now that i think of it, I have seen another issue, which probably has the same cause. I am seeing stretched thumbnails for stereoscopic images only. Above 200px, they are rendered correctly.

**Comment by oshamahue** [comment] 2020-12-18 10:54
I couldn't reproduce the problem. With
```
ResizeOptions(60,60)
RotateOptions.autoRotate()
```
auto rotation works well. I also reduced view size to 60x60 to check if it has an affect. With this config I verified `ResizeAndRotateProducer.doTransform` is executed successfully.

**Comment by oprisnik** [comment] 2020-12-18 11:29
Thank you for checking @oshamahue . I'll go ahead and close this issue then. If this is still a problem, please comment and we can revisit.

**Closed by oprisnik** 2020-12-18 11:29 UTC
Labels: bug
