### ISSUE TITLE
centerCrop does not work

### ISSUE THREAD

**Issue by eddieberklee** [facebook/fresco#1435] opened 2016-08-27 09:12 UTC
I am setting a local Uri for the image for the Drawee and once the image loads, it doesn't centerCrop. 

When the image is not square, there is always one side that is smaller than the respective width/height as if no scaling type was being applied and the default fitCenter was being used. 

I'm also using fresco's scaleType as opposed to android:scaleType since I read the Android property is just ignores by Fresco.

**Comment by eddieberklee** [comment] 2016-08-27 09:12
I can add my code and screenshot but I don't do anything fancy, so it seems like a legitimate issue with the library's handling of scaleType

**Comment by oprisnik** [comment] 2016-08-27 10:28
It works for me as expected. Example:

XML:
```
<com.facebook.drawee.view.SimpleDraweeView
  android:id="@+id/sdv"
  android:layout_width="64dp"
  android:layout_height="128dp"
  />
```
```
SimpleDraweeView sdv = (SimpleDraweeView) findViewById(R.id.sdv);
sdv.getHierarchy().setActualImageScaleType(ScalingUtils.ScaleType.CENTER_CROP);
sdv.setController(Fresco.newDraweeControllerBuilder().setUri(uri).build());
```

**Comment by eddieberklee** [comment] 2016-08-27 17:38
Hmm I set the scaleType via XML; does that make a difference? Maybe it's an edge case - I'll work through my own code and deconstruct what the core issue may be

**Comment by eddieberklee** [comment] 2016-08-28 17:47
Yep - verified that setting the xml property does not center crop. Setting is programmatically as you have shown works, however.

**Comment by oprisnik** [comment] 2016-08-28 20:51
Keep in mind that in order for this to work in XML, you have to use

    <com.facebook.drawee.view.SimpleDraweeView
        android:id="..."
        android:layout_width="..."
        android:layout_height="..."
        app:actualImageScaleType="centerCrop"
        />

where `xmlns:app="http://schemas.android.com/apk/res-auto"`, see http://frescolib.org/docs/using-drawees-xml.html

Then it should also work in XML.

**Comment by eddieberklee** [comment] 2016-08-28 21:16
I believe that's exactly what I've done here with `@+id/background_image`

<img width="595" alt="screenshot 2016-08-28 14 16 01" src="https://cloud.githubusercontent.com/assets/1836653/18036824/0059699a-6d2a-11e6-94e2-01a9770ec928.png">

**Comment by oprisnik** [comment] 2016-08-28 21:42
Changing the scale type in XML works for me as expected. Maybe you set a custom DraweeHierachy (which overwrites the XML values)?

**Comment by eddieberklee** [comment] 2016-08-28 21:46
I don't see anything I'm doing that would suggest that?
<img width="1205" alt="screenshot 2016-08-28 14 45 48" src="https://cloud.githubusercontent.com/assets/1836653/18036986/2eff0210-6d2e-11e6-99c0-776f2a2c04dc.png">
these are the only lines in which I'm interacting with the `SimpleDraweeView`

**Comment by oprisnik** [comment] 2016-08-28 21:51
Also, the default scale type used is CENTER_CROP, so not specifying anything should also give the correct results.

`setImageBitmap` should not be used with Fresco. Another reason why this is not working could be your custom layout params.

**Comment by oprisnik** [comment] 2016-09-30 22:56
How do you use Fresco? Could you provide a minimal example where we can reproduce the problem?

**Comment by am2222** [comment] 2016-10-01 08:44
I have updated the refrenced question..

**Comment by ffelini** [comment] 2017-01-20 15:33
I also faced this issue. CenterCrop has no effect for the same image if it is loaded from a local file path. After changing to an web url it worked fine. Looks like the issue is reproducible only for local images.

**Comment by oprisnik** [comment] 2017-01-20 20:19
We'll look into it.

**Comment by yervantk** [comment] 2017-02-16 15:19
Also had the same issue: 
```
    <com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/nav_header_background"
        tools:background="@color/accent_color"
        android:contentDescription="@null"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:minHeight="@dimen/nav_drawer_banner_height"
        app:backgroundImage="@drawable/splash_image"
        app:actualImageScaleType="centerCrop"
        app:viewAspectRatio="1.5"/>
```

It's inside a RelativeLayout, and it is not modified in code.

Emulator - Nexus One API 19

Original:
![splash_image](https://cloud.githubusercontent.com/assets/18272031/23027052/2dab807a-f431-11e6-919a-5a5000ccdad8.png)

InView:
<img width="308" alt="screen shot 2017-02-16 at 10 16 03 am" src="https://cloud.githubusercontent.com/assets/18272031/23027046/28fa614a-f431-11e6-9883-7ffc2601a57d.png">

Thanks for looking into it

**Comment by bpappin** [comment] 2017-09-21 18:51
Where release is this fixed in? 
It still happening in fresco:1.5.0 a year after being reported.

**Comment by zmroczek** [comment] 2018-01-19 17:05
@bpappin could you reproduce this in the showcase app? I tested with Media Provider example to use a local image (`DraweeMediaPickerFragment.java`) but I cannot reproduce it, also tried with RelativeLayout and it is also working fine.

**Closed** 2018-01-19 17:09 UTC
Labels: bug, needs-details

**Comment by Aeiric** [comment] 2018-02-28 06:44
i have the same problem ,is there any solution?
