### ISSUE TITLE
NPE on disk cache miss

### ISSUE THREAD

**Issue by lushan1314** [facebook/fresco#179] opened 2015-04-22 06:40 UTC
when i try to request a bitmap  from diskcache ,i got this exception:

```
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): java.lang.NullPointerException
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer$AddImageTransformMetaDataConsumer.onNewResultImpl(AddImageTransformMetaDataProducer.java:58)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer$AddImageTransformMetaDataConsumer.onNewResultImpl(AddImageTransformMetaDataProducer.java:44)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onNextResult(MultiplexProducer.java:443)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:490)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:487)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.MemoryCacheProducer$1.onNewResultImpl(MemoryCacheProducer.java:101)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.MemoryCacheProducer$1.onNewResultImpl(MemoryCacheProducer.java:89)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.DiskCacheProducer.maybeStartNextProducer(DiskCacheProducer.java:129)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.DiskCacheProducer.produceResults(DiskCacheProducer.java:63)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.MemoryCacheProducer.produceResults(MemoryCacheProducer.java:114)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.startNextProducerIfHasAttachedConsumers(MultiplexProducer.java:362)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.access$000(MultiplexProducer.java:121)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.MultiplexProducer.produceResults(MultiplexProducer.java:85)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer.produceResults(AddImageTransformMetaDataProducer.java:41)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.ImageTransformProducer.produceResults(ImageTransformProducer.java:53)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.ThrottlingProducer.produceResultsInternal(ThrottlingProducer.java:68)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.ThrottlingProducer.produceResults(ThrottlingProducer.java:61)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.BranchOnSeparateImagesProducer$OnFirstImageConsumer.onNewResultImpl(BranchOnSeparateImagesProducer.java:70)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.BranchOnSeparateImagesProducer$OnFirstImageConsumer.onNewResultImpl(BranchOnSeparateImagesProducer.java:47)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.ImageTransformProducer$TransformingConsumer.onNewResultImpl(ImageTransformProducer.java:85)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.imagepipeline.producers.StatefulProducerRunnable.onSuccess(StatefulProducerRunnable.java:49)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:54)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-22 14:19:01.601: E/unknown:AddImageTransformMetaDataConsumer(29493): 	at java.lang.Thread.run(Thread.java:841)
```
here is my code : 

 ```

        	Uri uri = Uri.parse("file:///storage/emulated/0/DCIM/camera/cache/1429681400334.jpg");
		
		ImageRequest request = ImageRequestBuilder
				                    .newBuilderWithSource(uri)
				                    .setAutoRotateEnabled(true)
				                    .setLowestPermittedRequestLevel(RequestLevel.DISK_CACHE)
				                    .setResizeOptions(new ResizeOptions(width, height))
				                    .build();
      
	DataSource<CloseableReference<CloseableImage>> dataSource = imagePipeline.fetchDecodedImage(request, context);
		DataSubscriber dataSubscriber = new BaseDataSubscriber<CloseableReference<CloseableImage>>() {

			@Override
			public void onNewResultImpl(DataSource<CloseableReference<CloseableImage>> dataSource) {

				if (!dataSource.isFinished()) {
					return;
				}
				if (listener != null) {
					if (!listener.onFullResult(context, uri, dataSource)) {
						CloseableReference<CloseableImage> closeableImageRef = dataSource.getResult();
						Bitmap bitmap = null;
						if (closeableImageRef != null && closeableImageRef.get() instanceof CloseableBitmap) {
							bitmap = ((CloseableBitmap) closeableImageRef.get()).getUnderlyingBitmap();
						}

						try {
							listener.onResult(context, uri, bitmap);
						} finally {
							CloseableReference.closeSafely(closeableImageRef);
						}
					}
				}
			}

			@Override
			public void onFailureImpl(DataSource dataSource) {
				Throwable throwable = dataSource.getFailureCause();
				if (listener != null)
					listener.onFailure(context, uri, throwable);
			}
		};

		dataSource.subscribe(dataSubscriber, mExecutorService);

```

what's wrong with my code? thank you

**Comment by lushan1314** [comment] 2015-04-22 07:24
i  have just changed the param, 
__RequestLevel.DISK_CACHE__   ->  __RequestLevel.FULL_FETCH__,like this :
```
ImageRequest request = ImageRequestBuilder
                                    .newBuilderWithSource(uri)
                                    .setAutoRotateEnabled(true)
                                    .setLowestPermittedRequestLevel(RequestLevel.FULL_FETCH)
                                    .setResizeOptions(new ResizeOptions(width, height))
                                    .build();
```
it's worked. ...

why? the image just cache in the file system.

**Comment by IanChilds** [comment] 2015-04-22 08:46
It works because `RequestLevel.DISK_CACHE` means that we just look in Fresco's disk cache, whereas `RequestLevel.FULL_FETCH` means that we actually look in the file that you have specified. 

It does look like you have uncovered a bug though - we should fix that but you can proceed using `FULL_FETCH`.

**Comment by lushan1314** [comment] 2015-04-22 08:55
ok, this is a bug!
 look forward to your next version...
Before this fix , i using FULL_FETCH is ok!

thank you .

**Comment by IanChilds** [comment] 2015-04-22 08:59
Sorry, my answer was not clear. It is not a bug that we just look in Fresco's disk cache when using `RequestLevel.DISK_CACHE`. But it is a bug that if we don't find anything in the disk cache, then we get the NullPointerException you pasted above. That's what we will fix.

**Comment by lushan1314** [comment] 2015-04-22 09:07
what  mean  __Fresco's disk__?

you mean __ImagePipelineConfig.setMainDiskCacheConfig(DiskCacheConfig)__?

if the image cache other place of the SD card,  then get the __NullPointerException__?

**Comment by lushan1314** [comment] 2015-04-22 09:19
ok , i was understand , in my case , the config must  use __FULL_FETCH__,beacuse  it isn't  in the __Fresco's disk__,   it just saved in the filesystem.

but ,when you not find , can you call the Subscriber's  method : __onFailureImpl__

thank you

**Comment by tyronen** [comment] 2015-05-14 22:25
Fixed in source.

**Closed by tyronen** 2015-05-14 22:25 UTC
Labels: bug
