### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by wangmeng1989** [facebook/fresco#934] opened 2016-01-19 02:59 UTC
device : samsung note2;dev tool: eclipse; android4.1.2

01-19 10:47:56.855: E/AndroidRuntime(30977): java.lang.ExceptionInInitializerError
01-19 10:47:56.855: E/AndroidRuntime(30977): 	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.doTransform(ResizeAndRotateProducer.java:154)
01-19 10:47:56.855: E/AndroidRuntime(30977): 	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.access$000(ResizeAndRotateProducer.java:72)
01-19 10:47:56.855: E/AndroidRuntime(30977): 	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer$1.run(ResizeAndRotateProducer.java:89)
01-19 10:47:56.855: E/AndroidRuntime(30977): 	at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
01-19 10:47:56.855: E/AndroidRuntime(30977): 	at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
01-19 10:47:56.855: E/AndroidRuntime(30977): 	at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
01-19 10:47:56.855: E/AndroidRuntime(30977): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
01-19 10:47:56.855: E/AndroidRuntime(30977): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
01-19 10:47:56.855: E/AndroidRuntime(30977): 	at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
01-19 10:47:56.855: E/AndroidRuntime(30977): 	at java.lang.Thread.run(Thread.java:856)
01-19 10:47:56.855: E/AndroidRuntime(30977): Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: link_image[1892]:  1946 could not load needed library 'libwebp.so' for 'libimagepipeline.so' (load_library[1094]: Library 'libwebp.so' not found)
01-19 10:47:56.855: E/AndroidRuntime(30977): 	at java.lang.Runtime.loadLibrary(Runtime.java:370)
01-19 10:47:56.855: E/AndroidRuntime(30977): 	at java.lang.System.loadLibrary(System.java:535)
01-19 10:47:56.855: E/AndroidRuntime(30977): 	at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:32)
01-19 10:47:56.855: E/AndroidRuntime(30977): 	at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
01-19 10:47:56.855: E/AndroidRuntime(30977): 	at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:43)
01-19 10:47:56.855: E/AndroidRuntime(30977): 	at com.facebook.imagepipeline.nativecode.JpegTranscoder.<clinit>(JpegTranscoder.java:26)
01-19 10:47:56.855: E/AndroidRuntime(30977): 	... 10 more

**Comment by balazsbalazs** [comment] 2016-01-20 16:05
Duplicate of #933

**Closed by balazsbalazs** 2016-01-20 16:05 UTC
