### ISSUE TITLE
Mac os How to build？

### ISSUE THREAD

**Issue by kongnanlive** [facebook/fresco#5] opened 2015-03-27 03:22 UTC
:imagepipeline:ndk_build_gifimage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':imagepipeline:ndk_build_gifimage'.
> A problem occurred starting process 'command 'ndk-build''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.279 secs
kongnandembp:fresco kongnan$ echo $PATH
/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/Users/kongnan/Documents/AndroidSDK/android-ndk-r10d
kongnandembp:fresco kongnan$ ndk-build
Android NDK: Could not find application project directory !    
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.    
/Users/kongnan/Documents/AndroidSDK/android-ndk-r10d/build/core/build-local.mk:148: *** Android NDK: Aborting    .  Stop.
kongnandembp:fresco kongnan$

**Comment by kongnanlive** [comment] 2015-03-27 03:56
commandLine 'ndk-build' replace commandLine ndk.dir.PATH + 'ndk-build' problem solving

**Comment by dp-singh** [comment] 2015-03-27 13:44
@kongnanlive Are you able to make it work?

**Comment by michalgr** [comment] 2015-03-28 04:08
Please make sure to have ndk-build in your $PATH. Our build.gradle depends on this.

**Comment by dp-singh** [comment] 2015-03-28 07:17
I already have it in my $PATH variable, but it is still showing the error

   Error:Execution failed for task ':imagepipeline:ndk_build_gifimage'.
> A problem occurred starting process 'command 'ndk-build''

**Comment by blackiedm** [comment] 2015-03-28 11:18
@dp-singh I have the same problem. Can you solve it?

**Comment by blackiedm** [comment] 2015-03-28 11:43
@kongnanlive thanks! I solved the problem.

**Comment by plamenko** [comment] 2015-03-28 22:48
@dp-singh, are you using AndroidStudio or are you building from command line? We will support building from AndroidStudio soon, but for now the console should do. 
Can you try clearing Gradle cache by removing `.gradle` directory and try again ?

**Comment by ikkyu0319** [comment] 2015-03-29 09:09
@dp-singh @blackiedm How do you make it work? SOS-~~~

**Comment by blackiedm** [comment] 2015-03-29 14:01
@ikkyu0319 find the commandline 'ndk-build' in imagepipeline/build.gradle and replace 
commandLine 'your local ndk dir/ndk-build'

**Comment by MarkMjw** [comment] 2015-03-30 09:18
@blackiedm i has replaced <commandLine 'ndk-build'> with <commandLine 'D:/Android/android-ndk-r10d/ndk-build'> , but it's also failed.

Starting process 'command 'D:/Android/android-ndk-r10d/ndk-build''. Working directory: E:\workspace\studio\fresco\imagep
ipeline Command: D:/Android/android-ndk-r10d/ndk-build NDK_APPLICATION_MK=../Application.mk NDK_OUT=E:\workspace\studio\
fresco\imagepipeline\build\tmp\ndk_build_gifimage NDK_LIBS_OUT=E:\workspace\studio\fresco\imagepipeline\build/gifimage -
C E:\workspace\studio\fresco\imagepipeline\src\main\jni\gifimage --jobs 8
:imagepipeline:ndk_build_gifimage FAILED
:imagepipeline:ndk_build_gifimage (Thread[main,5,main]) completed. Took 0.035 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':imagepipeline:ndk_build_gifimage'.
> A problem occurred starting process 'command 'D:/Android/android-ndk-r10d/ndk-build''

**Comment by dp-singh** [comment] 2015-03-30 12:36
@blackiedm @plamenko  @ikkyu0319  I have tried everything but was not able to make it. My main motive was to look at the sample so I have added gradle support repo 

Replace sample build file  dependencies with the below give dependencies

dependencies {
    compile "com.android.support:appcompat-v7:${APPCOMPAT_V7_VERSION}"
    compile "com.github.bumptech.glide:glide:${GLIDE_VERSION}"
    compile "com.mcxiaoke.volley:library:${VOLLEY_VERSION}"
    compile "com.nostra13.universalimageloader:universal-image-loader:${UIL_VERSION}"
    compile "com.squareup.picasso:picasso:${PICASSO_VERSION}"

    compile 'com.facebook.fresco:drawee-volley:0.1.0+'
    compile 'com.facebook.fresco:fresco:0.1.0+'
    compile 'com.facebook.fresco:imagepipeline-okhttp:0.1.0+'
}

**Comment by michalgr** [comment] 2015-03-30 12:53
@dp-singh I would like to fix whatever build issue you are facing. Would you mind letting us know what os (mac / linux / window) you use ? And also, could you try to run ndk-build from imagepipeline directory on its own, so that we can see what is the actual error, provided that it comes from ndk build:
path_to_your_ndk-build NDK_APPLICATION_MK=../Application.mk NDK_OUT=build NDK_LIBS_OUT=build -C src/main/jni/gifimage

**Comment by MarkMjw** [comment] 2015-03-30 13:41
@michalgr the message:(mac)
 in ~/Documents/studio/fresco/imagepipeline/src/main/jni on master*
$ ndk-build NDK_APPLICATION_MK=../Application.mk NDK_OUT=build NDK_LIBS_OUT=build -C gifimage
Android NDK: Android.mk: Cannot find module with tag 'giflib' in import path
Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?
Android NDK: The following directories were searched:
Android NDK:
make: Entering directory `/Documents/studio/fresco/imagepipeline/src/main/jni/gifimage'
Android.mk:25: *** Android NDK: Aborting.    .  Stop.
make: Leaving directory `/Documents/studio/fresco/imagepipeline/src/main/jni/gifimage'

**Comment by michalgr** [comment] 2015-03-30 14:05
giflib is supposed to be downloaded by imagepipeline/build.gradle. Can you try first running gradlew :assembleDebug (it will fail after downloading dependencies) and then repeating the same once again ? And one more question, what is your ndk version ?

Thanks for helping.

**Comment by MarkMjw** [comment] 2015-03-30 14:36
@michalgr thanks, i resolved this problem,  the problem is unable to access 'http://chromium.googlesource.com/webm/libwebp/'.

**Comment by KennethYo** [comment] 2015-03-31 03:06
i solved this problem,in ‘imagepipeline’ file replace like this.
step 1, find `commandLine 'ndk-build'`;
step 2, change 'ndk-build' to you ndk path.
```
 commandLine '/Users/kenneth/Desktop/develop/android-ndk-r10d/ndk-build',
```

**Comment by appledong** [comment] 2015-03-31 03:29
windows os replace ndk-build new problem：
  Android NDK: Could not find application project directory !    
E:\android-ndk-r10d\build\core\build-local.mk
Error:(148) *** Android NDK: Aborting    .  Stop.
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.    
make.exe: Entering directory `F:/fresco-master/fresco-master/imagepipeline/src/main/jni/gifimage'
make.exe: Leaving directory `F:/fresco-master/fresco-master/imagepipeline/src/main/jni/gifimage'
:imagepipeline:ndk_build_gifimage FAILED
Error:Execution failed for task ':imagepipeline:ndk_build_gifimage'.
> Process 'command 'E:\android-ndk-r10d\ndk-build.cmd'' finished with non-zero exit value 2

**Comment by ikkyu0319** [comment] 2015-03-31 03:54
@dp-singh @blackiedm @KennethYo 

hi,i m tryd，but not ok~~


eg code:
      def makeNdkTasks(String name) {
       task "ndk_build_$name"(type: Exec) {
        inputs.file("src/main/jni/$name")
        outputs.dir("$buildDir/$name")
        commandLine '/Users/Tom/Documents/AndroidTools/android-ndk-r10c/ndk-build'

      //        commandLine 'ndk-build',
      //            'NDK_APPLICATION_MK=../Application.mk',
      //            'NDK_OUT=' + temporaryDir,
      //            "NDK_LIBS_OUT=$buildDir/$name",
      //            '-C', file("src/main/jni/$name").absolutePath,
      //            '--jobs', '8'
          }
      
          task "ndk_clean_$name"(type: Exec) {
      
              commandLine '/Users/Tom/Documents/AndroidTools/android-ndk-r10c/ndk-build'
      //        commandLine 'ndk-build',
      //            'NDK_APPLICATION_MK=../Application.mk',
      //            'NDK_OUT=' + temporaryDir,
      //            "NDK_LIBS_OUT=$buildDir/$name",
      //            '-C', file("src/main/jni/$name").absolutePath,
      //            'clean'
          }

**Comment by BaronZ** [comment] 2015-03-31 05:37
@appledong  +1
E:\android-ndk-r10d\build\core\build-local.mk
Error:(148) *** Android NDK: Aborting . Stop.
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.

**Comment by littletanker** [comment] 2015-03-31 06:52
@michalgr in windows, i run the command in  imagepipeline directory as you say, 
ndk-build NDK_APPLICATION_MK=../Ap
plication.mk NDK_OUT=build NDK_LIBS_OUT=build -C src/main/jni/gifimage

but failed and this is the output
Android NDK: Could not find application project directory !
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.
make.exe: Entering directory `F:/AndroidStudioProjects/fresco/imagepipeline/src/
main/jni/gifimage'
D:\android-ndk-r9d_x86_64\build/core/build-local.mk:148: *** Android NDK: Aborti
ng    .  Stop.
make.exe: Leaving directory `F:/AndroidStudioProjects/fresco/imagepipeline/src/m
ain/jni/gifimage'

**Comment by KennethYo** [comment] 2015-03-31 07:35
@ikkyu0319 哥们，首先把ndk配置环境变量，然后看下面我的代码，把我的ndk路径`'/Users/kenneth/Desktop/develop/android-ndk-r10d/ndk-build'`替换成你的就可以了。
```
 task "ndk_build_$name"(type: Exec) {
        inputs.file("src/main/jni/$name")
        outputs.dir("$buildDir/$name")
        commandLine '/Users/kenneth/Desktop/develop/android-ndk-r10d/ndk-build',
            'NDK_APPLICATION_MK=../Application.mk',
            'NDK_OUT=' + temporaryDir,
            "NDK_LIBS_OUT=$buildDir/$name",
            '-C', file("src/main/jni/$name").absolutePath,
            '--jobs', '8'
    }

    task "ndk_clean_$name"(type: Exec) {
        commandLine '/Users/kenneth/Desktop/develop/android-ndk-r10d/ndk-build',
            'NDK_APPLICATION_MK=../Application.mk',
            'NDK_OUT=' + temporaryDir,
            "NDK_LIBS_OUT=$buildDir/$name",
            '-C', file("src/main/jni/$name").absolutePath,
            'clean'
    }
```

**Comment by michalgr** [comment] 2015-03-31 15:32
@KennethYo did you add ndk-build to $PATH variable ? If so, then gradle should be able to find ndk-build without specifying full path, unless you run it from Android Studio - we don't support it yet, but this is about to be fixed.

@appledong , @BaronZ, @littletanker - lets keep this issue mac only - as title states. There is similar issue for windows: https://github.com/facebook/fresco/issues/24 lets continue windows related discussion there.

**Comment by AU3904** [comment] 2015-04-01 15:24
@kongnanlive  thinks

**Comment by tyronen** [comment] 2015-04-01 15:51
Too many issues are being reported in this thread. Closing it.
- For Windows build issues, please see #24
- For duplicate-giflib issue, see #50 
- For WebP quota issue, see #52

**Closed by tyronen** 2015-04-01 15:51 UTC

**Comment by yushilong** [comment] 2015-04-09 06:31
@blackiedm thanks,that solved my problem.

**Comment by lovely3x** [comment] 2015-04-12 16:42
i solved the problem.
find the commandline 'ndk-build' in imagepipeline/build.gradle and replace 
commandLine 'your local ndk dir/ndk-build.cmd',

**Comment by shenzhimeng** [comment] 2015-04-21 10:15
@kongnanlive   @blackiedm  thanks! I solved the problem.

**Comment by colarking** [comment] 2015-08-29 16:58
just add one line in file build.gradle task getNdkBuildFullPath;
return your local full ndk-build path.then all done;

def getNdkBuildFullPath() {
    return "/Users/{your_mac_name}/Android/android-ndk-r10e/ndk-build"
    // we allow to provide full path to ndk-build tool
    if (hasProperty('ndk.command')) {
        return property('ndk.command')
    }
    // or just a path to the containing directiry
    if (hasProperty('ndk.path')) {
        def path = property('ndk.path')
        if (!path.endsWith(File.separator)) {
            path += File.separator
        }
        return path + getNdkBuildName()
    }
    // if none of above is provided, we assume ndk-build is already in $PATH
    return getNdkBuildName()
}
