### ISSUE TITLE
How to stop loading when i scrolling listview very fast!

### ISSUE THREAD

**Issue by longmh** [facebook/fresco#356] opened 2015-06-09 02:49 UTC
just like the imageloader:
mListview.setOnScrollListener(new PauseOnScrollListener(
				ImageLoader.getInstance(), false, true));
if fresco can do this ,it will be wonderful！

**Comment by tyronen** [comment] 2015-06-09 10:36
Why would it be wonderful? Your users would just see grey boxes as they scroll. 

Are you suffering performance issues?

**Comment by vsahu1986** [comment] 2015-06-10 05:53
@tyronen 
1 it might be necessary multiple network and then upon view detached , the request are cancel . so again CPU computation and wastage of Bandwidth .

2 Question :- When Target view is detached from Any Scrolling Widget , the Request is canceled or Completed , Or Fresco check the percentage of Image is downloaded then take decision to cancel or continue

**Comment by vsahu1986** [comment] 2015-06-11 06:56
Thanks @tyronen , 
For adding this as enhancement also please have a look at 

http://stackoverflow.com/questions/27146850/cancelling-the-image-request-android-on-the-basis-of-progress-image-loader-vol

**Comment by tyronen** [comment] 2015-10-16 13:09
Duplicate of #512. Closing this one as the other has more discussion.

**Closed by tyronen** 2015-10-16 13:09 UTC
Labels: duplicate

**Comment by TyrionCN** [comment] 2016-03-22 11:49
Fresco.getImagePipeline().resume() and Fresco.getImagePipeline().pause()
