### ISSUE TITLE
Fresco init fail

### ISSUE THREAD

**Issue by fengruyi** [facebook/fresco#2342] opened 2019-05-24 09:40 UTC
fresco version 1.11.0
java.io.IOException
android.app.ActivityThread.handleBindApplication(ActivityThread.java:6024)
android.app.ActivityThread.-wrap2(ActivityThread.java)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1805)
android.os.Handler.dispatchMessage(Handler.java:110)
android.os.Looper.loop(Looper.java:232)
android.app.ActivityThread.main(ActivityThread.java:6910)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)Caused by: java.lang.RuntimeException: Could not initialize SoLoader
com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:76)
com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:45)
com.oppo.community.app.CommunityAppInit.b(CommunityAppInit.java:64)
com.oppo.community.app.CommunityAppInit.a(CommunityAppInit.java:55)
com.oppo.community.app.CommunityApplication.onCreate(CommunityApplication.java:37)
android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
android.app.ActivityThread.handleBindApplication(ActivityThread.java:6021) ... 8 moreCaused by: java.io.IOException: cannot mkdir: /data/user/0/com.oppo.community/lib-main
com.facebook.soloader.SysUtil.mkdirOrThrow(SysUtil.java:146)
com.facebook.soloader.UnpackingSoSource.prepare(UnpackingSoSource.java:415)
com.facebook.soloader.SoLoader.initSoSources(SoLoader.java:266)
com.facebook.soloader.SoLoader.init(SoLoader.java:170)
com.facebook.soloader.SoLoader.init(SoLoader.java:153)
com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:68) ... 14 more

**Comment by oprisnik** [comment] 2019-05-24 10:42
Duplicate of #2111

**Closed by oprisnik** 2019-05-24 10:42 UTC
