### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by lushan1314** [facebook/fresco#409] opened 2015-06-29 02:42 UTC
```
java.lang.NoClassDefFoundError: com/facebook/imagepipeline/memory/NativeMemoryChunk
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
	at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:264)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.&lt;init&gt;(NativePooledByteBufferOutputStream.java:53)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:98)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:26)
	at com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(BufferedDiskCache.java:198)
	at com.facebook.imagepipeline.cache.BufferedDiskCache.access$300(BufferedDiskCache.java:38)
	at com.facebook.imagepipeline.cache.BufferedDiskCache$1.call(BufferedDiskCache.java:104)
	at com.facebook.imagepipeline.cache.BufferedDiskCache$1.call(BufferedDiskCache.java:88)
	at bolts.Task$2.run(Task.java:195)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:838)
```

**Comment by lushan1314** [comment] 2015-06-29 09:47
···
java.lang.OutOfMemoryError
	at com.facebook.imagepipeline.memory.SharedByteArray.allocateByteArray(SharedByteArray.java:139)
	at com.facebook.imagepipeline.memory.SharedByteArray.getByteArray(SharedByteArray.java:107)
	at com.facebook.imagepipeline.memory.SharedByteArray.get(SharedByteArray.java:95)
	at com.facebook.imagepipeline.bitmaps.DalvikBitmapFactory.decodeJPEGFromPooledByteBuffer(DalvikBitmapFactory.java:116)
	at com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.decodeJPEGFromPooledByteBuffer(PlatformBitmapFactory.java:108)
	at com.facebook.imagepipeline.decoder.ImageDecoder.decodeJpeg(ImageDecoder.java:135)
	at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:83)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:231)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:92)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$3.run(DecodeProducer.java:202)
	at com.facebook.common.executors.SerialDelegatingExecutor.executeSingleCommand(SerialDelegatingExecutor.java:76)
	at com.facebook.common.executors.SerialDelegatingExecutor.access$000(SerialDelegatingExecutor.java:24)
	at com.facebook.common.executors.SerialDelegatingExecutor$1.run(SerialDelegatingExecutor.java:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
···


The two bugs are linked?

**Comment by michalgr** [comment] 2015-06-30 22:10
Bugs are unrelated, please open separate issue for OutOfMemoryError.

Do you use proguard ? What device do you reproduce this on ?

**Comment by tyronen** [comment] 2015-12-11 13:27
Reaping; this is probably a duplicate of #410 anyway.

**Closed by tyronen** 2015-12-11 13:27 UTC
Labels: needs-details
