### ISSUE TITLE
java.lang.UnsatisfiedLinkError : Nexus One

### ISSUE THREAD

**Issue by pinkred** [facebook/fresco#939] opened 2016-01-21 06:39 UTC
Fresco 0.9.0
Used Gradle

 I was resolved to call "System.loadLibrary("webp");" upon starting the app.

Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: link_image[1962]:    33 could not load needed library 'libwebp.so' for 'libimagepipeline.so' (load_library[1104]: Library 'libwebp.so' not found)
                                                                    at java.lang.Runtime.loadLibrary(Runtime.java:434)
                                                                    at java.lang.System.loadLibrary(System.java:554)
                                                                    at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:32)
                                                                    at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
                                                                    at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:43)
                                                                    at com.facebook.imagepipeline.nativecode.JpegTranscoder.<clinit>(JpegTranscoder.java:26)
                                                                    at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.doTransform(ResizeAndRotateProducer.java:154) 
                                                                    at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.access$000(ResizeAndRotateProducer.java:72) 
                                                                    at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer$1.run(ResizeAndRotateProducer.java:89) 
                                                                    at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207) 
                                                                    at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27) 
                                                                    at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78) 
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088) 
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581) 
                                                                    at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43) 
                                                                    at java.lang.Thread.run(Thread.java:1019)

**Comment by plamenko** [comment] 2016-01-27 14:48
Duplicate of #410

**Closed by plamenko** 2016-01-27 14:48 UTC
