### ISSUE TITLE
java.lang.UnsatisfiedLinkError: com.facebook.imagepipeline.memory.NativeMemoryChunk

### ISSUE THREAD

**Issue by Anler2015** [facebook/fresco#1102] opened 2016-04-01 05:46 UTC
when i call  Uri uri = Uri.parse("res://com.gejiahui.fesrcodemo/" + R.mipmap.ic_launcher);
simpleDraweeView.setImageURI(uri);     

```
  java.lang.UnsatisfiedLinkError: com.facebook.imagepipeline.memory.NativeMemoryChunk
                                                                             at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
                                                                             at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
                                                                             at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
                                                                             at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
                                                                             at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:98)
                                                                             at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:26)
                                                                             at com.facebook.imagepipeline.producers.LocalFetchProducer.getByteBufferBackedEncodedImage(LocalFetchProducer.java:99)
                                                                             at com.facebook.imagepipeline.producers.LocalFetchProducer.getEncodedImage(LocalFetchProducer.java:119)
                                                                             at com.facebook.imagepipeline.producers.LocalResourceFetchProducer.getEncodedImage(LocalResourceFetchProducer.java:42)
                                                                             at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:66)
                                                                             at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:62)
                                                                             at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:45)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                             at java.lang.Thread.run(Thread.java:833)
```

**Comment by aagnes** [comment] 2016-04-01 16:42
duplicate of #410

**Closed by aagnes** 2016-04-01 16:42 UTC
