### ISSUE TITLE
The application may be doing too much work on its main thread.

### ISSUE THREAD

**Issue by ultimaters** [facebook/fresco#84] opened 2015-04-03 12:46 UTC
I used SimpleDraweeView in adapter, but my app runs slowly, and I saw the log below:

`I/Choreographer(1378): Skipped 55 frames!  The application may be doing too much work on its main thread. `

so I comment the code `mSimpleDraw.setImageUri`, the app runs fluently. I think the SimpleDraw blocks the main thread when fetching image from network.

**Comment by plamenko** [comment] 2015-04-03 17:30
Are you using OkHttp networking stack? 
There is an issue with OkHttp networking stack that it cancels requests on the calling thread (which is going to be the main thread). We have a fix ready for that.
Other than that, SimpleDraweeView should not be doing anything heavy on the main thread. If you give us more context on how you use Fresco, we may be able to isolate the issue more easily.

**Comment by ultimaters** [comment] 2015-04-04 17:15
@plamenko I just used in a CircleView Adapter and load image, very simple like the tutorial.
in Application: `Fresco.initialize(mContext);`
in adapter: `mImageView.setImageURI(Uri.parse(data.getImage()));`
that's it.

**Comment by plamenko** [comment] 2015-04-04 19:33
What's `CircleView Adapter`?

**Comment by mikeknoop** [comment] 2015-04-06 02:30
> The application may be doing too much work on its main thread.

Hitting the same problem here. Pretty basic usage of `SimpleDraweeView` in a `GridView` through an adapter:

```java
// MainActivity.java
Fresco.initialize(this);
GridView gv = findViewById(R.id.grid_view);
ImageAdapter ia = new ImageAdapter(this);
gv.setAdapter(ia);
```

```java
// ImageAdapter.java
public class ImageAdapter extends BaseAdapter {
   ...
   public View getView(int position, View convertView, final ViewGroup parent) {
        if (convertView == null) {
            convertView = LayoutInflater.from(mContext).inflate(R.layout.grid_item, null);
            convertView.setTag(convertView.findViewById(R.id.grid_item_image_view));
        }
        SquareDraweeView view = (SquareDraweeView) convertView.getTag();
        
        // with the following line: major UI slowdown, "the application may be doing too much work on its main thread."
        // without the following line: performant as expected
        view.setImageURI(mCameraImages.getUris().get(position));
        
        return view;
   }
   ...
}
```

```xml
<!-- grid_item.xml -->
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:fresco="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent">

    <com.otterroll.app.SquareDraweeView
        android:id="@+id/grid_item_image_view"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        />

</LinearLayout>
```

It seems that any parallel calls to `setImageURI` result in the slowdown.

**Comment by ultimaters** [comment] 2015-04-06 04:48
@plamenko My code just the same as above, in an adapter

**Comment by plamenko** [comment] 2015-04-06 15:43
I'll investigate

**Comment by mikeknoop** [comment] 2015-04-09 04:42
Replacing

```
view.setImageURI(Uri.parse("content://...");
```

with

```java
        ImageRequest imageRequest =
                ImageRequestBuilder.newBuilderWithSource(Uri.parse("content://...")
                        .setResizeOptions(
                                new ResizeOptions(150, 150))
                        .build();
        DraweeController draweeController = Fresco.newDraweeControllerBuilder()
                .setImageRequest(imageRequest)
                .setOldController(view.getController())
                .setAutoPlayAnimations(true)
                .build();
        view.setController(draweeController);
```

in my code above fixes the performance problem. If I comment out the `setResizeOptions` line the performance problem comes back. Perhaps something to do with rescaling on the main thread?

**Comment by mikeknoop** [comment] 2015-04-09 04:51
FWIW I can also hack the Fresco Sample app to `Skipped 129 frames!` by taking the opposite approach to my last comment:

Replace [these lines](https://github.com/facebook/fresco/blob/master/sample/src/main/java/com/facebook/fresco/sample/adapters/FrescoAdapter.java#L60-L71) with

```
Uri uri = getRandomLocalContentURI();
view.setImageURI(uri);
```

I've found it *only* hits performance problems dealing with local `content://` URIs. `http://` do just fine.

**Comment by plamenko** [comment] 2015-04-09 20:07
That's really helpful information, thanks!

**Comment by fuwaneko** [comment] 2015-04-09 22:18
I can confirm with OkHttp simple setImageUri for Grid item results in performance problem and eventually a crash due to ```android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork```. So I think it's network on main thread. Full stack trace:

```
android.os.NetworkOnMainThreadException
            at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1154)
            at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1009)
            at com.squareup.okhttp.Connection.closeIfOwnedBy(Connection.java:142)
            at com.squareup.okhttp.OkHttpClient$1.closeIfOwnedBy(OkHttpClient.java:71)
            at com.squareup.okhttp.internal.http.HttpConnection.closeIfOwnedBy(HttpConnection.java:136)
            at com.squareup.okhttp.internal.http.HttpTransport.disconnect(HttpTransport.java:135)
            at com.squareup.okhttp.internal.http.HttpEngine.disconnect(HttpEngine.java:507)
            at com.squareup.okhttp.Call.cancel(Call.java:122)
            at com.facebook.imagepipeline.backends.okhttp.OkHttpNetworkFetcher$1.onCancellationRequested(OkHttpNetworkFetcher.java:68)
            at com.facebook.imagepipeline.producers.SettableProducerContext.cancel(SettableProducerContext.java:135)
            at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$1.onCancellationRequested(MultiplexProducer.java:277)
            at com.facebook.imagepipeline.producers.SettableProducerContext.cancel(SettableProducerContext.java:135)
            at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$1.onCancellationRequested(MultiplexProducer.java:277)
            at com.facebook.imagepipeline.producers.SettableProducerContext.cancel(SettableProducerContext.java:135)
            at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter.close(AbstractProducerToDataSourceAdapter.java:104)
            at com.facebook.drawee.controller.AbstractDraweeController.releaseFetch(AbstractDraweeController.java:173)
            at com.facebook.drawee.controller.AbstractDraweeController.release(AbstractDraweeController.java:165)
            at com.facebook.drawee.controller.AbstractDraweeController.setHierarchy(AbstractDraweeController.java:289)
            at com.facebook.drawee.view.DraweeHolder.setController(DraweeHolder.java:211)
            at com.facebook.drawee.view.DraweeView.setController(DraweeView.java:87)
            at my.app.ImageAdapter.getView(ImageAdapter.java:77)
            at android.widget.AbsListView.obtainView(AbsListView.java:2255)
            at android.widget.GridView.makeAndAddView(GridView.java:1349)
            at android.widget.GridView.makeRow(GridView.java:349)
            at android.widget.GridView.fillDown(GridView.java:291)
            at android.widget.GridView.fillGap(GridView.java:251)
            at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5143)
            at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4254)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
            at android.view.Choreographer.doCallbacks(Choreographer.java:574)
            at android.view.Choreographer.doFrame(Choreographer.java:543)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:212)
            at android.app.ActivityThread.main(ActivityThread.java:5135)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by plamenko** [comment] 2015-04-10 12:46
@fuwaneko , yeah OkHttp cancellation is a known issue and we have a fix for that. However, local content uri is something we yet need to figure.

**Comment by mikeknoop** [comment] 2015-04-12 02:05
One other potential/related clue. Even when using my workaround above (which fixed the performance problem), I still see one error line for every `content://...` image that is loaded:

```
04-11 22:00:25.677  29554-29592/com.example.app E/JHEAD﹕ can't open '/external/images/media/172693'
04-11 22:00:25.677  29554-29592/com.example.app E/JHEAD﹕ can't open '/external/images/media/172692'
04-11 22:00:25.677  29554-29592/com.example.app E/JHEAD﹕ can't open '/external/images/media/172691'
```

The image still successfully loads but an error is generated for each.

The fix from [this Picasso thread](https://github.com/square/picasso/issues/332#issuecomment-30635004) is to include `file://` in front, presumably something that Fresco needs to do internally or an upstream lib needs to be doing.

**Comment by leofirespotter** [comment] 2015-04-15 19:08
Seeing the same thing, I am using OkHttp. Basically everything works, but after scrolling down a list of pictures it crashes with:

    04-15 12:04:49.431  17021-17021/co.switchapp E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: co.switchapp, PID: 17021
    android.os.NetworkOnMainThreadException
            at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
            at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:749)
            at okio.Okio$1.write(Okio.java:78)
            at okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
            at okio.RealBufferedSink.flush(RealBufferedSink.java:201)
            at com.squareup.okhttp.internal.spdy.Spdy3$Writer.rstStream(Spdy3.java:382)
            at com.squareup.okhttp.internal.spdy.SpdyConnection.writeSynReset(SpdyConnection.java:351)
            at com.squareup.okhttp.internal.spdy.SpdyStream.close(SpdyStream.java:221)
            at com.squareup.okhttp.internal.http.SpdyTransport.disconnect(SpdyTransport.java:215)
            at com.squareup.okhttp.internal.http.HttpEngine.disconnect(HttpEngine.java:507)
            at com.squareup.okhttp.Call.cancel(Call.java:122)
            at com.facebook.imagepipeline.backends.okhttp.OkHttpNetworkFetcher$1.onCancellationRequested(OkHttpNetworkFetcher.java:68)
            at com.facebook.imagepipeline.producers.SettableProducerContext.cancel(SettableProducerContext.java:135)
            at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$1.onCancellationRequested(MultiplexProducer.java:277)
            at com.facebook.imagepipeline.producers.SettableProducerContext.cancel(SettableProducerContext.java:135)
            at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$1.onCancellationRequested(MultiplexProducer.java:277)
            at com.facebook.imagepipeline.producers.SettableProducerContext.cancel(SettableProducerContext.java:135)
            at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter.close(AbstractProducerToDataSourceAdapter.java:104)
            at com.facebook.drawee.controller.AbstractDraweeController.releaseFetch(AbstractDraweeController.java:173)
            at com.facebook.drawee.controller.AbstractDraweeController.release(AbstractDraweeController.java:165)
            at com.facebook.drawee.components.DeferredReleaser$1.run(DeferredReleaser.java:64)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

In order to load the image, I am calling:
```
DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setUri(uri)
                .setOldController(image.getController())
                .setAutoPlayAnimations(true)
                .build();

        image.setController(controller);
```

**Comment by tyronen** [comment] 2015-04-15 20:02
Recently merged pull request #21 should take care of this. This is in head and we should have a release with it out shortly.

**Comment by plamenko** [comment] 2015-04-17 00:43
I deleted the two comments related to OkHttp cancellation as they are not related to this issue and has already been fixed.

**Comment by plamenko** [comment] 2015-04-17 00:46
@mikeknoop , I missed part of your commend earlier, where you said "If I comment out the setResizeOptions line the performance problem comes back."
Can you please check what are the dimensions of those local images? If the image is much bigger than the view than there is going to be a noticeable overhead unless we resize the image first. Resize has to be explicitly specified as calling `setImageURI` won't do that.

**Comment by mikeknoop** [comment] 2015-04-17 02:11
@plamenko my local images are indeed bigger than the view. They are camera images so likely ~3000x3000px getting scaled to ~150dpi views.

Can Fresco handle this use case?

**Comment by plamenko** [comment] 2015-04-18 00:47
@mikeknoop, yes, please see http://frescolib.org/docs/resizing-rotating.html#_

**Comment by mikeknoop** [comment] 2015-04-18 03:08
Thanks for the info. I imagine Camera images are the 80% use case for `content://` URIs, maybe it'd make sense to do resizing in `setImageURI`.

I feel like I'm really hacking things to get Fresco to work:

```
                ImageRequestBuilder.newBuilderWithSource(mCameraImages.getUris().get(position))
                        .setLocalThumbnailPreviewsEnabled(false)
                        .setResizeOptions(new ResizeOptions(1, 1))
                        .build();
```

Resizing to 1x1 seems to pick some minimum size that is suitable. I should add that I haven't been able to beat Picasso w.r.t. loading performance for `content://` images yet (and Picasso is pretty slow itself which is why I was checking out Fresco).

**Comment by plamenko** [comment] 2015-04-18 12:57
You should definitely specify resizing, but`ResizeOptions(1, 1)` doesn't seem right, why don't you pass the view's dimensions?
Btw, if you do `.setLocalThumbnailPreviewsEnabled(true)` with `.setResizeOptions(new ResizeOptions(1, 1))`, and also do `setControllerListener` with the following listener, what do you get in the adb logcat?

    ControllerListener listener = new BaseControllerListener<ImageInfo>() {
      @Override
      public void onIntermediateImageSet(String id, ImageInfo imageInfo) {
        android.util.Log.w(TAG, "intermediate: width " + imageInfo.getWidth() + ", " + "height " + imageInfo.getHeight());
      }
      @Override
      public void onFinalImageSet(String id, ImageInfo imageInfo, Animatable a) {
        android.util.Log.w(TAG, "final: width " + imageInfo.getWidth() + ", " + "height " + imageInfo.getHeight());
      }
    };

**Comment by avenwu** [comment] 2015-07-14 06:58
Same issue, after using SimpleDraweeView:

    The application may be doing too much work on its main thread;

In my case I have init the Fresco in Application, in the adapter use setImageUrl, then the app is closing to ANR with few response;
The issue can be fixed setting ResizeOptions to SimpleDraweeView mentioned by @mikeknoop  

```
ImageRequest request = ImageRequestBuilder.newBuilderWithSource(Uri.parse(data.image))
                .setResizeOptions(new ResizeOptions(width, height))
                .build();
        holder.pic.setController(Fresco.newDraweeControllerBuilder()
                .setOldController(holder.pic.getController())
                .setImageRequest(request)
                .build());

**Comment by johnzheng00** [comment] 2015-07-23 04:18
I just get the width and height when setImageUri()

public void setImageURI(Uri uri, @Nullable Object callerContext) {
        if (!hasHierarchy()) {
            inflateHierarchy(getContext());
        }
        DraweeController controller;
        int width = getLayoutWidth() ,  height = getLayoutHeight();
        if (this.mSimpleDraweeControllerBuilder instanceof PipelineDraweeControllerBuilder
                && width>0 && height >0) {
            ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
                    .setResizeOptions(new ResizeOptions(width, height))
                    .setAutoRotateEnabled(true)
                    .build();
            PipelineDraweeControllerBuilder builder =
                    (PipelineDraweeControllerBuilder) mSimpleDraweeControllerBuilder;
            controller = builder
                    .setAutoPlayAnimations(true)
                    .setCallerContext(callerContext)
                    .setOldController(this.getController())
                    .setImageRequest(request)
                    .build();

        } else
            controller = this.mSimpleDraweeControllerBuilder
                    .setCallerContext(callerContext)
                    .setUri(uri)
                    .setOldController(this.getController())
                    .build();

        this.setController(controller);

 /**
     * {@inheritDoc}
     * <p/>
     * Width is defined by target {@link android.view.View view} parameters, configuration
     * parameters or device display dimensions.<br />
     * Size computing algorithm (go by steps until get non-zero value):<br />
     * 1) Get the actual drawn <b>getWidth()</b> of the View<br />
     * 2) Get <b>layout_width</b>
     */
    public int getLayoutWidth() {
        final ViewGroup.LayoutParams params = getLayoutParams();
        int width = 0;
        if (params != null && params.width != ViewGroup.LayoutParams.WRAP_CONTENT) {
            width = getWidth(); // Get actual image width
        }
        if (width <= 0 && params != null) width = params.width; // Get layout width parameter
        if (width <= 0) {
            width = getImageViewFieldValue(this, "mMaxWidth"); // Check maxWidth parameter
        }
        return width;
    }

    /**
     * {@inheritDoc}
     * <p/>
     * Height is defined by target {@link android.view.View view} parameters, configuration
     * parameters or device display dimensions.<br />
     * Size computing algorithm (go by steps until get non-zero value):<br />
     * 1) Get the actual drawn <b>getHeight()</b> of the View<br />
     * 2) Get <b>layout_height</b>
     */
    public int getLayoutHeight() {
        final ViewGroup.LayoutParams params = getLayoutParams();
        int height = 0;
        if (params != null && params.height != ViewGroup.LayoutParams.WRAP_CONTENT) {
            height = getHeight(); // Get actual image height
        }
        if (height <= 0 && params != null) height = params.height; // Get layout height parameter
        if (height <= 0) {
            height = getImageViewFieldValue(this, "mMaxHeight"); // Check maxHeight parameter
        }
        return height;
    }

    private static int getImageViewFieldValue(Object object, String fieldName) {
        int value = 0;
        try {
            Field field = ImageView.class.getDeclaredField(fieldName);
            field.setAccessible(true);
            int fieldValue = (Integer) field.get(object);
            if (fieldValue > 0 && fieldValue < Integer.MAX_VALUE) {
                value = fieldValue;
            }
        } catch (Exception e) {
        }
        return value;
    }

**Comment by facebook-github-bot-0** [comment] 2015-08-05 18:02
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by tyronen** [comment] 2015-10-14 16:21
Setting ResizeOptions is indeed the correct solution. The reason frames were skipped is that Android was struggling to scale such a large image in a small view.

At most we could make this automatic some of the time - when the view is specified with an explicit size - but that won't work for match_parent type layouts.

**Closed by tyronen** 2015-10-14 16:21 UTC
Labels: bug

**Comment by mrdevilbynature** [comment] 2015-10-27 13:34
Hello, 

I got entangled in a similar problem where i was using SimpleDraweeView as a GridView row, to parse some http uri's. All images were > 5mb and were being loaded in memory without getting resized automatically (which was causing Out of Memory Error).

 @mikeknoop 's solution works but writing such code in getView() seems an inefficient approach.

So, i created my version of SimpleDraweeView, following are the steps i used:

1)  Copy/Paste SimpleDraweeView in your package and rename it to something else (I renamed it to TweakedDraweeView)

2) Change the following method as follows:
```
public void setImageURI(Uri uri, Object callerContext)
{
    ImageRequest imageRequest = ImageRequestBuilder.newBuilderWithSource(uri).setResizeOptions(new ResizeOptions(getLayoutParams().width, getLayoutParams().height)).build();
    DraweeController draweeController = Fresco.newDraweeControllerBuilder().setImageRequest(imageRequest).setOldController(getController()).setAutoPlayAnimations(true).build();
    setController(draweeController);
// exactly same as mikeknoop's
}
```

3) Step 2 alone won't work because it would throw an exception saying that the SimpleDraweeView has not been initialized, although you have renamed it, but Fresco still seems to look for SimpleDraweeView.
The solution for this problem is to add an extra line where you initialized Fresco(probably in Application class)
```
 TweakedDraweeView.initialize(new PipelineDraweeControllerBuilderSupplier(this));      //since i named my SimpleDraweeView version to TweakedDraweeView
```

**Comment by saantiaguilera** [comment] 2016-08-02 14:28
Hi ! I had the same problem and what fixed it was to
setLocalThumbnailPreview(FALSE).

Regarding this issue, can someone from fresco answer me these questions:
- How does resizing work in case the image is a .png ? Ive seen the docs that it currently only supports jpg, but how does it handle other types (I hope theres no runtime exceptions)
- Same goes for resizing but when an image is tiny and the resizing is large (eg. img of 50x50 resized to 200x200) does my app crash or it just ignores this?
- Resizing works in a separate thread right ? (I really, really, really hope so :P )

**Comment by adkhamjonDev** [comment] 2021-06-13 06:35
need help 
<< The application may be doing too much work on its main thread >>
And here is my code 
ViewModel->
class YoutubeViewModel(apiService: ApiService):ViewModel() {
    val youtubeLiveData=MutableLiveData<Resource<MyYoutubeData>>()
    private val youtubeRepository=YoutubeRepository(apiService)
    init {
        getVideos()
    }
    private fun getVideos() {
        viewModelScope.launch {
            youtubeLiveData.postValue(Resource.loading(null))
                youtubeRepository.getYoutubeData()
                    .catch {e->
                        youtubeLiveData.postValue(Resource.error(e.message?:"Error",null))
                    }.collect {
                        youtubeLiveData.postValue(Resource.success(it))
                    }
        }
    }
    @JvmName("getYoutubeLiveData1")
    fun getYoutubeLiveData():MutableLiveData<Resource<MyYoutubeData>>{
        return youtubeLiveData
    }
}
And in MainFragment
youtubeViewModel=ViewModelProviders.of(this,ViewModelFactory(ApiClient.apiService))[YoutubeViewModel::class.java]

        youtubeViewModel.getYoutubeLiveData().observe(viewLifecycleOwner,{
            when(it.status){
                Status.ERROR->{
                    binding.progress.visibility=View.INVISIBLE
                    Toast.makeText(requireContext(), it.message, Toast.LENGTH_SHORT).show()
                }
                Status.LOADING->{
                    binding.progress.visibility=View.VISIBLE
                }
                Status.SUCCESS->{
                    binding.progress.visibility=View.INVISIBLE
                    videoAdapter.submitList(it.data?.items)
                    Log.d(TAG, "onCreateView: ${it.data?.items}")
                }
            }
        })
