### ISSUE TITLE
placeholderImage not in center on Google Pixel XL

### ISSUE THREAD

**Issue by iztou** [facebook/fresco#2542] opened 2020-09-28 02:07 UTC
### Description

```XML
        <com.facebook.drawee.view.SimpleDraweeView
            android:id="@+id/circle_click"
            android:layout_width="100dp"
            android:layout_height="100dp"
            app:placeholderImage="@mipmap/icon_default_head"
            app:roundAsCircle="true"
            app:placeholderImageScaleType="centerInside"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

        <com.facebook.drawee.view.SimpleDraweeView
            android:id="@+id/square_click"
            android:layout_width="100dp"
            android:layout_height="100dp"
            app:placeholderImage="@mipmap/icon_default_head"
            app:placeholderImageScaleType="centerInside"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />
```
![20200928_093458](https://user-images.githubusercontent.com/4177989/94382915-13336680-0171-11eb-9b61-b97fa39bd82e.gif)
the gif show two images switch visibile to gone and you can see the placeholderimage of the image is not in center
### Reproduction

i found it only show on Google Pixel XL , it not reproduce on ONEPLUS 6T .
### Additional Information

* Fresco version: 2.3.0
* Platform version: Device : Google Pixel XL 
                                Android version: 10

**Comment by iztou** [comment] 2020-10-13 01:35
it still require to fix

**Comment by oprisnik** [comment] 2020-10-16 12:02
Hey! This looks like a duplicate of #2277. That should fix your issue.

**Closed by oprisnik** 2020-10-16 12:02 UTC
