### ISSUE TITLE
Performance issue on long list and full width images

### ISSUE THREAD

**Issue by henrytao-me** [facebook/fresco#428] opened 2015-07-06 09:04 UTC
I am experiencing fresco `SimpleDraweeView` on RecyclerView: long list and full width images. It's quite laggy. I turned on GPU rendering in developer options and it jumped to the top of the screen at some points. 
I also tried `ImageView` with simple `AsyncTask Image Loader` which doesn't have cache, it's pretty fast and smooth. 

Here are full testing specs: 
- Nexus 5
- Enless recyclerView list
- Full width images (image size is quite small)
- Flexible list (some items have text only, some other items have images and text)

Do you have any idea on how to fix this issue?

**Comment by plamenko** [comment] 2015-07-06 20:34
I am not sure what might be the cause, but we are investigating it.

**Comment by mrlongtt** [comment] 2015-07-07 10:08
I've got same issue, I think there are 2 reasons to make it lag
* Big DraweeView (full-width as @henrytao-me said)
* The visibility of DraweeView is changed when rendering in adapter (GONE to VISIBLE)

**Comment by AcidicSkittles** [comment] 2015-07-16 06:06
If you're targeting a version of android before api 14, you can add ```android:hardwareAccelerated="true"``` to your application tag in the manifest. I think if you're targeting a version >=14 then it's enabled by default. Something to check at least. My app displays a lot images side by side in a pager and it doesn't lag

**Comment by erikandre** [comment] 2017-07-11 16:08
Closing as there has been no updates for 2 years, and this seems to mostly concern (by now) obsolete Android versions

**Closed by erikandre** 2017-07-11 16:08 UTC
Labels: bug
