### ISSUE TITLE
Process 'command 'ndk-build.cmd'' finished with non-zero exit value 2

### ISSUE THREAD

**Issue by BaronZ** [facebook/fresco#47] opened 2015-03-31 03:34 UTC
hi, i replace commandLine ndk-build imagepipeline.gradle to ndk-build.cmd and encoutered blow problem
build-local.mk
:imagepipeline:ndk_build_gifimage FAILED
Error:Execution failed for task ':imagepipeline:ndk_build_gifimage'.
> Process 'command 'ndk-build.cmd'' finished with non-zero exit value 2

**Comment by BaronZ** [comment] 2015-03-31 03:37
my environment is windows 7 with android studio 1.1.0, nkd version is r10d

**Comment by BaronZ** [comment] 2015-03-31 04:02
F:\dev_tools\android-ndk-r10d\build\core\build-local.mk
Error:(148) *** Android NDK: Aborting    .  Stop.
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.    
make.exe: Entering directory `F:/1/fresco-master/imagepipeline/src/main/jni/gifimage'
make.exe: Leaving directory `F:/1/fresco-master/imagepipeline/src/main/jni/gifimage'
:imagepipeline:ndk_build_gifimage FAILED
Error:Execution failed for task ':imagepipeline:ndk_build_gifimage'.
> Process 'command 'ndk-build.cmd'' finished with non-zero exit value 2

**Comment by hiphonezhu** [comment] 2015-03-31 06:20
@BaronZ did you solve it?

**Comment by wenjianxue** [comment] 2015-03-31 06:25
The same problem!
I tried to add commandLine param 'NDK_PROJECT_PATH=.'   , but other problems :

Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?    
Android NDK: The following directories were searched:    
Android NDK:         
make.exe: Entering directory `D:/github/fresco/imagepipeline/src/main/jni/gifimage'
make.exe: Leaving directory `D:/github/fresco/imagepipeline/src/main/jni/gifimage'
:imagepipeline:ndk_build_gifimage FAILED

**Comment by wanglg** [comment] 2015-03-31 09:17
The same problem!
Error:Execution failed for task ':imagepipeline:ndk_build_gifimage'.
> A problem occurred starting process 'command 'ndk-build''

**Comment by xuwt** [comment] 2015-03-31 09:52
Me too! I try to change ndk-build to ndk-build.cmd and add path to local.properties, all failed! How to do?

**Comment by arlong** [comment] 2015-03-31 10:25
I have same problem!

Error:(148) *** Android NDK: Aborting    .  Stop.
:imagepipeline:ndk_build_gifimage FAILED
Error:Execution failed for task ':imagepipeline:ndk_build_gifimage'.
> Process 'command 'C:\android\android-ndk-r10d\ndk-build.cmd'' finished with non-zero exit value 2

Information:BUILD FAILED

Everyone,who solve it? share solution,thanks

**Comment by tyronen** [comment] 2015-03-31 12:14
Duplicate of issue #24

**Closed by tyronen** 2015-03-31 12:14 UTC
Labels: duplicate

**Comment by yyloveruancaipu** [comment] 2015-04-14 08:10
I have same problem.How to solve？

**Comment by lkw103037** [comment] 2015-04-30 03:08
I fix it!  check your dependencies,  fresco use some three-part package like "nineoldandroids"  I used "nineoldandroids" make this problem,  delete it , it's work fine.

**Comment by Rakeshincluso** [comment] 2016-06-27 06:35
I have the same problem 
please help to solve it

**Comment by chenzhu005774** [comment] 2016-12-20 00:55
I have the same problem
please help to solve it.thank very much

**Comment by chenzhu005774** [comment] 2016-12-20 00:57
creact a  empty.c or  sourceSets.main {
        jni.srcDirs = []
    }             have no use...........................

**Comment by Rakeshincluso** [comment] 2016-12-20 04:46
send ur email id













Thanks & Regards,

Rakesh kushwaha
(Android Developer)
8510069810

**Comment by impasoftware** [comment] 2017-04-03 04:22
Error:Execution failed for task ':scanlibrary:ndkBuild'.
> A problem occurred starting process 'command 'ndk-build.cmd''

**Comment by MM-Furkan** [comment] 2017-08-28 15:44
I still having the same problem can any one plz hlp me out

**Comment by sachinrkeche** [comment] 2017-11-30 12:16
I am  having issue of ,
Error:Execution failed for task ':ReactAndroid:buildReactNdkLib'.
> Process 'command 'D:\soft\android-ndk-r10e-windows-x86_64\android-ndk-r10e\ndk-build.cmd'' finished with non-zero exit value 2
 I am working in Win 07 environment using r10e NDK.

**Comment by oprisnik** [comment] 2018-05-23 15:47
Make sure that you have the NDK set up in your `local.properties` file: `ndk.dir=/path/to/ndk/android-ndk-r15c` or similar.

**Comment by buixuanthe2212** [comment] 2018-11-09 07:31
I don't know if that's good. I went to

C:\Users\Dev\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd

directory and for the ndk-build.cmd i press

Right-Click> Edit and change the cmd file from:

@echo off
%~dp0\build\ndk-build.cmd %*
to

@echo off
THAT works for me

**Comment by FitApps7** [comment] 2019-01-12 05:40
> I don't know if that's good. I went to
> 
> C:\Users\Dev\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd
> 
> directory and for the ndk-build.cmd i press
> 
> Right-Click> Edit and change the cmd file from:
> 
> @echo off
> %~dp0\build\ndk-build.cmd %*
> to
> 
> @echo off
> THAT works for me

I also solved by this!

**Comment by DreamAndLife** [comment] 2019-03-07 12:54
> I don't know if that's good. I went to
> 
> C:\Users\Dev\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd
> 
> directory and for the ndk-build.cmd i press
> 
> Right-Click> Edit and change the cmd file from:
> 
> @echo off
> %~dp0\build\ndk-build.cmd %*
> to
> 
> @echo off
> THAT works for me

OMG!,THANKS

**Comment by fjz97** [comment] 2019-04-01 12:06
> I don't know if that's good. I went to
> 
> C:\Users\Dev\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd
> 
> directory and for the ndk-build.cmd i press
> 
> Right-Click> Edit and change the cmd file from:
> 
> @echo off
> %~dp0\build\ndk-build.cmd %*
> to
> 
> @echo off
> THAT works for me

thanks!

**Comment by kanglyh** [comment] 2019-05-24 14:25
> 我不知道这是否好。我去了
> 
> C：\ Users \用户开发\应用程序数据\本地\的Android \ SDK \ NDK束\ NDK-build.cmd
> 
> 目录和ndk-build.cmd我按
> 
> 右键单击>编辑并从以下位置更改cmd文件：
> 
> @echo off 
> ％~dp0 \ build \ ndk-build.cmd％* 
> to
> 
> @echo off 
> 对我有用

谢谢！
