### ISSUE TITLE
Import Fresco library to project find speed of gradle compiling slow down a lot

### ISSUE THREAD

**Issue by alexli0707** [facebook/fresco#519] opened 2015-08-06 09:08 UTC
First of all,it is an awesome library.But when I import it into my project I find gradle compile speed slow down alot ,here is the question I asked in [stackoverflow](http://stackoverflow.com/questions/31850990/import-fresco-library-to-project-find-speed-of-gradle-compiling-slow-down-a-lot).I need some help,thank you !!!

**Comment by michalgr** [comment] 2015-08-15 01:48
Thanks for reporting the issue, I'll try to help. There are few question that might help us find out what is going on:
1. How did you import Fresco ? Do you include Fresco as aar or do you compile it from source ?
2. Which task do you run to compile your app ? Is it release build or debug build ?
3. Is proguard run as a step in the compilation process ?
4. Can you share gradle's output ? It might help us identify build steps that take the most of time.

**Comment by vipulasri** [comment] 2015-08-15 14:57
Yeah it does slow down. I imported fresco as aar

**Comment by alexli0707** [comment] 2015-08-20 03:23
1. I imported Fresco this way:

    compile ('com.facebook.fresco:fresco:0.6.0'){
          exclude module: 'bolts-android'
          exclude module: 'support-v4'
    }

2. User installDebug to run project
3. proguard  does not run as a step in compliation process.
4. compileDebugJava  take the most of time.

**Comment by massimocarli** [comment] 2016-02-16 15:58
@alexli0707, @vipulasri Do you still have this problem with the 0.9.0?

Thanks

**Comment by alphamu** [comment] 2016-02-22 21:20
I can confirm this is still an issue in 0.9.0 I've included 0.9.0 specifically, no + notation. I've even turned on offline builds but it still added almost a minute to my compile time. If I limit the min SDK of dev builds to 21, the situation improves, I'm assuming because of the predexing. 
The gradle build is slow every time I change the code, change XML resources doesn't have the same effect.

**Comment by erikandre** [comment] 2018-01-16 18:16
Closing due to lack of progress and or updates during the last 2 years.

**Closed by erikandre** 2018-01-16 18:16 UTC
Labels: build
