### ISSUE TITLE
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.

### ISSUE THREAD

**Issue by avibhamare** [facebook/fresco#582] opened 2015-08-28 15:55 UTC
08-28 13:04:25.102: E/StrictMode(9428): A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
08-28 13:04:25.102: E/StrictMode(9428): java.lang.Throwable: Explicit termination method 'end' not called
08-28 13:04:25.102: E/StrictMode(9428):     at dalvik.system.CloseGuard.open(CloseGuard.java:184)
08-28 13:04:25.102: E/StrictMode(9428):     at java.util.zip.Inflater.<init>(Inflater.java:82)
08-28 13:04:25.102: E/StrictMode(9428):     at com.android.okio.GzipSource.<init>(GzipSource.java:57)
08-28 13:04:25.102: E/StrictMode(9428):     at com.android.okhttp.internal.http.HttpEngine.initContentStream(HttpEngine.java:490)
08-28 13:04:25.102: E/StrictMode(9428):     at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:680)
08-28 13:04:25.102: E/StrictMode(9428):     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:388)
08-28 13:04:25.102: E/StrictMode(9428):     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
08-28 13:04:25.102: E/StrictMode(9428):     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:199)
08-28 13:04:25.102: E/StrictMode(9428):     at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher$1.run(HttpUrlConnectionNetworkFetcher.java:58)
08-28 13:04:25.102: E/StrictMode(9428):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
08-28 13:04:25.102: E/StrictMode(9428):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-28 13:04:25.102: E/StrictMode(9428):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-28 13:04:25.102: E/StrictMode(9428):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-28 13:04:25.102: E/StrictMode(9428):     at java.lang.Thread.run(Thread.java:818)

**Comment by BadrinathKulkarni** [comment] 2015-09-15 18:26
Same error!

**Comment by rdietrichberlin** [comment] 2016-08-02 12:12
Same here:

A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                              java.lang.Throwable: Explicit termination method 'end' not called
                                                                  at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                  at java.util.zip.Inflater.<init>(Inflater.java:82)
                                                                  at com.android.okhttp.okio.GzipSource.<init>(GzipSource.java:62)
                                                                  at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:645)
                                                                  at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:827)
                                                                  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443)
                                                                  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
                                                                  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:150)
                                                                  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:194)
                                                                  at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getHeaderField(DelegatingHttpsURLConnection.java:190)
                                                                  at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getHeaderField(HttpsURLConnectionImpl.java)
                                                                  at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher$1.run(HttpUrlConnectionNetworkFetcher.java:61)
                                                                  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                  at java.lang.Thread.run(Thread.java:818)

**Comment by caojianfeng** [comment] 2017-02-24 00:41
2017 now，still here！
It BLOCK us，who want use strictMode to detect resource leaks ！！！

And this is the same error：https://github.com/facebook/fresco/issues/823

**Comment by caojianfeng** [comment] 2017-02-24 00:41
02-24 08:22:44.467 22640-22649/top.ovo.gundam E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                            java.lang.Throwable: Explicit termination method 'end' not called
                                                                at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                                at java.util.zip.Inflater.<init>(Inflater.java:82)
                                                                at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:96)
                                                                at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:81)
                                                                at libcore.net.http.HttpEngine.initContentStream(HttpEngine.java:528)
                                                                at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:836)
                                                                at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:274)
                                                                at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:486)
                                                                at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher.downloadFrom(HttpUrlConnectionNetworkFetcher.java:97)
                                                                at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher.fetchSync(HttpUrlConnectionNetworkFetcher.java:80)
                                                                at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher$1.run(HttpUrlConnectionNetworkFetcher.java:61)
                                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
                                                                at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:137)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                                                                at java.lang.Thread.run(Thread.java:856)

**Comment by caojianfeng** [comment] 2017-02-24 00:42
compile 'com.facebook.fresco:fresco:1.1.0'
    compile 'com.facebook.fresco:animated-base-support:1.1.0'

**Comment by caojianfeng** [comment] 2017-02-26 07:09
The problem is from here com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher#fetchSync

`
  @VisibleForTesting
  void fetchSync(FetchState fetchState, Callback callback) {
    HttpURLConnection connection = null;

    try {
      connection = downloadFrom(fetchState.getUri(), MAX_REDIRECTS);

      if (connection != null) {
        callback.onResponse(connection.getInputStream(), -1);
      }
    } catch (IOException e) {
      callback.onFailure(e);
    } finally {
      if (connection != null) {
        connection.disconnect();
      }
    }

  }

`

The stream(connection.getInputStream()) shoud be closed.

Like this:
`
  @VisibleForTesting
  void fetchSync(FetchState fetchState, Callback callback) {
    HttpURLConnection connection = null;
    InputStream is = null;
    try {
      connection = downloadFrom(fetchState.getUri(), MAX_REDIRECTS);

      if (connection != null) {
        is = connection.getInputStream();
        callback.onResponse(is, -1);
      }
    } catch (IOException e) {
      callback.onFailure(e);
    } finally {
      if (is != null) {
        try {
          is.close();
        } catch (IOException e) {
        }
      }
      if (connection != null) {
        connection.disconnect();
      }
    }

  }
`

**Comment by oprisnik** [comment] 2018-01-16 10:30
This has been fixed in f1e1f24de3d65aa06d51f7dde92651a3cb29ed76

**Closed by oprisnik** 2018-01-16 10:30 UTC
Labels: bug
