### ISSUE TITLE
After updating from version 1.3.0 to 1.4.0, the load image appears an exception

### ISSUE THREAD

**Issue by e-hai** [facebook/fresco#1828] opened 2017-07-18 03:49 UTC
### Description

After updating from version 1.3 to 1.4, the load image appears an exception

### Reproduction

```
com.facebook.imagepipeline.memory.BasePool$PoolSizeViolationException: Pool hard cap violation? Hard cap = 4194304 Used size = 4194304 Free size = 0 Request size = 131072
                                                                   at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:241)
                                                                   at com.facebook.imagepipeline.memory.FlexByteArrayPool.get(FlexByteArrayPool.java:51)
                                                                   at com.facebook.imagepipeline.platform.KitKatPurgeableDecoder.decodeJPEGByteArrayAsPurgeable(KitKatPurgeableDecoder.java:85)
                                                                   at com.facebook.imagepipeline.platform.DalvikPurgeableDecoder.decodeJPEGFromEncodedImage(DalvikPurgeableDecoder.java:89)
                                                                   at com.facebook.imagepipeline.platform.KitKatPurgeableDecoder.decodeJPEGFromEncodedImage(KitKatPurgeableDecoder.java:32)
                                                                   at com.facebook.imagepipeline.bitmaps.HoneycombBitmapFactory.createBitmapInternal(HoneycombBitmapFactory.java:65)
                                                                   at com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.createBitmap(PlatformBitmapFactory.java:79)
                                                                   at com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.createBitmap(PlatformBitmapFactory.java:46)
                                                                   at com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrameOrFallback(BitmapAnimationBackend.java:210)
                                                                   at com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrameOrFallback(BitmapAnimationBackend.java:232)
                                                                   at com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrameOrFallback(BitmapAnimationBackend.java:232)
                                                                   at com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrame(BitmapAnimationBackend.java:167)
                                                                   at com.facebook.fresco.animation.backend.AnimationBackendDelegate.drawFrame(AnimationBackendDelegate.java:62)
                                                                   at com.facebook.fresco.animation.backend.AnimationBackendDelegateWithInactivityCheck.drawFrame(AnimationBackendDelegateWithInactivityCheck.java:114)
                                                                   at com.facebook.fresco.animation.drawable.AnimatedDrawable2.draw(AnimatedDrawable2.java:206)
                                                                   at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:147)
                                                                   at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:147)
                                                                   at com.facebook.drawee.drawable.ScaleTypeDrawable.draw(ScaleTypeDrawable.java:126)
                                                                   at com.facebook.drawee.drawable.FadeDrawable.drawDrawableWithAlpha(FadeDrawable.java:306)
                                                                   at com.facebook.drawee.drawable.FadeDrawable.draw(FadeDrawable.java:293)
                                                                   at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:147)
                                                                   at com.facebook.drawee.generic.RootDrawable.draw(RootDrawable.java:85)
                                                                   at android.widget.ImageView.onDraw(ImageView.java:1019)
                                                                   at android.view.View.draw(View.java:14465)
                                                                   at android.view.View.getDisplayList(View.java:13362)
                                                                   at android.view.View.getDisplayList(View.java:13404)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                                                                   at android.view.View.getDisplayList(View.java:13300)
                                                                   at android.view.View.getDisplayList(View.java:13404)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                                                                   at android.view.View.getDisplayList(View.java:13300)
                                                                   at android.view.View.getDisplayList(View.java:13404)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                                                                   at android.view.View.getDisplayList(View.java:13300)
                                                                   at android.view.View.getDisplayList(View.java:13404)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                                                                   at android.view.View.getDisplayList(View.java:13300)
                                                                   at android.view.View.getDisplayList(View.java:13404)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                                                                   at android.view.View.getDisplayList(View.java:13300)
                                                                   at android.view.View.getDisplayList(View.java:13404)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                                                                   at android.view.View.getDisplayList(View.java:13300)
                                                                   at android.view.View.getDisplayList(View.java:13404)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                                                                   at android.view.View.getDisplayList(View.java:13300)
                                                                   at android.view.View.getDisplayList(View.java:13404)
                                                                   at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
                                                               	at android.view.HardwareRenderer$G
```

### Additional Information

* Fresco version: 1.4.0
* Platform version: 4.4.2

**Comment by oprisnik** [comment] 2017-07-18 08:29
What image are you trying to decode? A huge animated GIF / WebP? Can you reproduce the issue in the Showcase sample app (which has a URI override)?

**Comment by e-hai** [comment] 2017-07-19 01:45
A lot of 5MB of GIF

**Comment by e-hai** [comment] 2017-07-19 01:50
@oprisnik A lot of 5MB of GIF

**Comment by oprisnik** [comment] 2017-07-19 10:51
1.4.0 includes a new implementation for animated images that shares the caches for frames with the rest of fresco to adhere to the set memory limits. Previously, frames were handled completely separately, which means that there were no real limits. It seems that you're running into this issue now since you're displaying many big GIFs. You can increase Fresco's memory limits, see http://frescolib.org/docs/configure-image-pipeline.html

**Comment by e-hai** [comment] 2017-07-19 12:54
@oprisnik Of course, I can increase fresco memory. But I don't think this solves the problem because I can't predict how big a GIF is on the user's device. So I wonder if there's any way to compress the GIF size.

**Comment by oprisnik** [comment] 2017-07-19 16:38
Yeah, in general you should not serve huge GIFs to the client. However, we do not support client-side resizing / downsampling for GIFs. You can however implement a custom decoder that creates smaller GIFs.

**Comment by e-hai** [comment] 2017-07-20 01:30
@oprisnik Thank you for your patience.Because the user's picture is on their own phone, not on our server.If you want, I want to know why Fresco doesn't provide this functionality.If I want to add this feature to Fresco, how do I do that?

**Comment by lambdapioneer** [comment] 2017-07-24 08:53
Hi @e-hai, we don't support this feature yet because there was no need for us yet (in many cases videos are the better format for this kind of large animations).

If you want to improve our GIF handling, we gladly accept pull-requests :) This section of our documentation http://frescolib.org/docs/building-from-source.html is a good place to start.

Know that for updating the GIF code, you'll need work on the native side (this here is a good entry point: https://github.com/facebook/fresco/blob/4404a6c88b17fabb3d431653124c64657518b16e/animated-gif/src/main/jni/gifimage/gif.cpp)

**Comment by e-hai** [comment] 2017-07-24 09:02
@lambdapioneer Thank you very much for your reply. I will try to modify the code.

**Comment by erikandre** [comment] 2018-01-16 11:59
Closing due to lack of updates.

**Closed by erikandre** 2018-01-16 11:59 UTC
Labels: enhancement
