### ISSUE TITLE
Android P Fresco initialize

### ISSUE THREAD

**Issue by dbeqiraj** [facebook/fresco#2115] opened 2018-05-16 09:00 UTC
Fresco version: 1.8.1

When I try to initialize it I get this error:

```
W/SoLoader: Cannot get nativeLoad method
            java.lang.NoSuchMethodException: nativeLoad [class java.lang.String, class java.lang.ClassLoader, class java.lang.String]
                at java.lang.Class.getMethod(Class.java:2068)
                at java.lang.Class.getDeclaredMethod(Class.java:2047)
                at com.facebook.soloader.SoLoader.getNativeLoadRuntimeMethod(SoLoader.java:281)
                at com.facebook.soloader.SoLoader.initSoLoader(SoLoader.java:233)
                at com.facebook.soloader.SoLoader.initImpl(SoLoader.java:141)
                at com.facebook.soloader.SoLoader.init(SoLoader.java:120)
                at com.facebook.soloader.SoLoader.init(SoLoader.java:104)
                at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:63)
                at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:46)
```

**Comment by zmroczek** [comment] 2018-05-21 10:46
Hi @dbeqiraj 

Thanks for reporting this issue. Could you provide more details so that we can reproduce it? Which device are you using and which Android P version?

**Comment by dbeqiraj** [comment] 2018-05-21 10:53
This is the code in my class@onCreate() which extends Application:

```
ImagePipelineConfig config = ImagePipelineConfig.newBuilder(this)
                .setDownsampleEnabled(true)
                .build();
Fresco.initialize(this, config); // This throws the exception
```
This happens in the emulator which runs Android API P x86. I have not tested it in a real device.

**Comment by Vatreni** [comment] 2018-05-21 13:49
Same issue on the Google Pixel (real device) with P(beta) Android. Fresco version 1.9.0. Initialization the same as above
`java.lang.NoSuchMethodException: nativeLoad [class java.lang.String, class java.lang.ClassLoader, class java.lang.String]
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getDeclaredMethod(Class.java:2047)
        at com.facebook.soloader.SoLoader.getNativeLoadRuntimeMethod(SoLoader.java:281)
        at com.facebook.soloader.SoLoader.initSoLoader(SoLoader.java:233)
        at com.facebook.soloader.SoLoader.initImpl(SoLoader.java:141)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:120)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:104)
        at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:61)
        at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:44)`

**Comment by zmroczek** [comment] 2018-05-21 15:05
I was able to reproduce it and it's an issue with SoLoader call which I'm going to fix, I'll keep you updated on that.

Just to double check, does this error cause any side effects for you @Vatreni and @dbeqiraj? It doesn't seem to cause any crash for me, I can only see the error in logs.

**Comment by dbeqiraj** [comment] 2018-05-21 15:25
I use Fresco only to play a gif. This error doesn't look to affect that, looks fine.

**Comment by Vatreni** [comment] 2018-05-21 15:53
I didn't notice any side effects, only this error message, I use Fresco for simple image loading

**Comment by Iamrookie** [comment] 2018-06-05 11:37
He means  on extends Application class init

**Comment by dementia2029** [comment] 2018-06-08 08:47
Same hear. I have Google Pixel gen1 with Android P. My project targets sdk28 and i use support libraries from AndroidX.

**Comment by zmroczek** [comment] 2018-06-08 09:02
I fixed this error in soLoader [here](https://github.com/facebook/SoLoader/commit/3d691395dd353d7ebf633db445bcc7460232aa7a), so we should have it in place after the next soLoader release. 

The error will be gone, however, only after Android P is officially released, since right now in beta there is still 27 returned for `Build.VERSION.SDK_INT`, which will be increased in the official release.

**Comment by dementia2029** [comment] 2018-06-08 09:05
@zmroczek You are wrong. We have final API from yesterday and Android **9** beta 2 which returns Build.VERSION.SDK_INT = 28 and targetSdkVersion is unblocked to 28.

**Comment by zmroczek** [comment] 2018-06-08 09:07
Ok, thanks for updating @dementia2029 in that case the soLoader fix I mentioned should help with that with beta 2. We'll update the version after the next soLoader release.

**Comment by zmroczek** [comment] 2018-06-12 10:54
We've updated the SoLoader version in https://github.com/facebook/fresco/commit/8e9243e94fc9f8117b09b1fb6c4594feda7411c8, so the nativeLoad error shouldn't occur on Android P anymore.

**Closed by zmroczek** 2018-06-12 10:54 UTC
Labels: bug

**Comment by AlexRU18** [comment] 2018-10-29 05:48
This problm also have emulator Nexus 5X API28
` java.lang.NoSuchMethodException: nativeLoad [class java.lang.String, class java.lang.ClassLoader, class java.lang.String]
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getDeclaredMethod(Class.java:2047)
        at com.facebook.soloader.SoLoader.getNativeLoadRuntimeMethod(SoLoader.java:281)
        at com.facebook.soloader.SoLoader.initSoLoader(SoLoader.java:233)
        at com.facebook.soloader.SoLoader.initImpl(SoLoader.java:141)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:120)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:104)
        at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:61)
        at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:37)
        at com.gootax.worker.App.onCreate(App.java:39)`

**Comment by anilthummar** [comment] 2018-12-07 10:40
> This problm also have emulator Nexus 5X API28
> ` java.lang.NoSuchMethodException: nativeLoad [class java.lang.String, class java.lang.ClassLoader, class java.lang.String] at java.lang.Class.getMethod(Class.java:2068) at java.lang.Class.getDeclaredMethod(Class.java:2047) at com.facebook.soloader.SoLoader.getNativeLoadRuntimeMethod(SoLoader.java:281) at com.facebook.soloader.SoLoader.initSoLoader(SoLoader.java:233) at com.facebook.soloader.SoLoader.initImpl(SoLoader.java:141) at com.facebook.soloader.SoLoader.init(SoLoader.java:120) at com.facebook.soloader.SoLoader.init(SoLoader.java:104) at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:61) at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:37) at com.gootax.worker.App.onCreate(App.java:39)`

use below dependencies in your app gradle file :
implementation 'com.facebook.fresco:fresco:**1.11.0'** and its worked for me.

**Comment by liusgh** [comment] 2019-01-28 12:16
@zmroczek 
Shìshí shàng, wǒmen jǐnjǐn yīlàile yīgè zǐ mókuài animated-webp(1.9.0), Ér bùshì zhíjiē yīlàile zhěnggè Fresco. Yīnwèi wǒmen zhǐ shǐyòng Fresco lái jiāzài dòngtài Webp. Suǒyǐ zhège bàocuò duīzhàn huì yǐngxiǎng wǒmen xiànzài de shǐyòng chǎngjǐng ma? Wǒmen xūyào shēngjí duì animated-webp huòzhě so-loader de yīlài ma
展开
134/5000
In fact, we only rely on a submodule, animated-webp (1.9.0), rather than relying directly on the entire Fresco. Because we only use Fresco to load dynamic Webp. So this error stack will affect our current usage scenarios? Do we need to upgrade the dependency on animated-webp or so-loader?
