### ISSUE TITLE
.setDownsampleEnabled(true) then resize don't work for webp

### ISSUE THREAD

**Issue by shixiangyu** [facebook/fresco#1533] opened 2016-11-08 07:00 UTC

**Comment by eldk** [comment] 2016-11-08 12:47
Hello,

I think @massimocarli solve it here : https://github.com/facebook/fresco/commit/474f62af906341026943efeabf64a32516d1b2fe.

Will it be in the next release ?

Eric

**Comment by shixiangyu** [comment] 2016-11-09 02:10
@eldk,

Thanks,hope it be in the next release!

**Comment by shixiangyu** [comment] 2016-11-09 08:37
@eldk 
  My problem is that my app are mostly webp format pictures, but also the big picture, cause the memory cache is full, and I should be how to solve?

**Comment by shixiangyu** [comment] 2016-11-09 08:39
@eldk ,
Hi,
My problem is that my app are mostly webp format pictures, but also the big picture, cause the memory cache is full, and I should be how to solve?

**Comment by eldk** [comment] 2016-11-09 15:27
Hello,

Are you speaking of diskCache (3. Disk cache http://frescolib.org/docs/caching.html) or (1. Bitmap cache) ?

Eric

**Comment by shixiangyu** [comment] 2016-11-10 02:00
Hello,
it's bitmap cache,thanks

**Comment by eldk** [comment] 2016-11-10 17:03
Hello,

If it's bitmap cache, you should : 
- reduce the size of WebP downloaded files (downsample before download them)
- use only jpg files
or
- use the master Fresco repository to build library yourself

If none is convenient, the best is to wait the next release.

Thanks,

Eric

**Comment by erikandre** [comment] 2017-07-11 16:30
Closing as this is a duplicate of #743

**Closed by erikandre** 2017-07-11 16:30 UTC
