### ISSUE TITLE
SimpleDraweeView always load image fialure

### ISSUE THREAD

**Issue by maplesnow-zsm** [facebook/fresco#1528] opened 2016-11-03 12:44 UTC
when we user simpledraweeview, we allow load image failure, here is zhe log:

com.facebook.imagepipeline.platform.DalvikPurgeableDecoder.android.graphics.Bitmap decodeByteArrayAsPurgeable(com.facebook.common.references.CloseableReference,android.graphics.BitmapFactory$Options)(DalvikPurgeableDecoder.java:162)
##_parent_##2##_parent_##
##_child_## android.graphics.Bitmap decodeJPEGByteArrayAsPurgeable(com.facebook.common.references.CloseableReference,int,android.graphics.BitmapFactory$Options)##_child_##
##_child_## com.facebook.common.references.CloseableReference pinBitmap(android.graphics.Bitmap)##_child_##
com.facebook.imagepipeline.platform.KitKatPurgeableDecoder.com.facebook.common.references.CloseableReference pinBitmap(android.graphics.Bitmap)(KitKatPurgeableDecoder.java:32)
##_parent_##2##_parent_##
##_child_## com.facebook.common.references.CloseableReference decodeJPEGFromEncodedImage(com.facebook.imagepipeline.image.EncodedImage,android.graphics.Bitmap$Config,int)##_child_##
##_child_## com.facebook.common.references.CloseableReference decodeFromEncodedImage(com.facebook.imagepipeline.image.EncodedImage,android.graphics.Bitmap$Config)##_child_##
com.facebook.imagepipeline.platform.DalvikPurgeableDecoder.com.facebook.common.references.CloseableReference decodeJPEGFromEncodedImage(com.facebook.imagepipeline.image.EncodedImage,android.graphics.Bitmap$Config,int)(DalvikPurgeableDecoder.java:90)
##_parent_##2##_parent_##
##_child_## android.graphics.Bitmap decodeByteArrayAsPurgeable(com.facebook.common.references.CloseableReference,android.graphics.BitmapFactory$Options)##_child_##
##_child_## android.graphics.Bitmap decodeJPEGByteArrayAsPurgeable(com.facebook.common.references.CloseableReference,int,android.graphics.BitmapFactory$Options)##_child_##
com.facebook.imagepipeline.platform.KitKatPurgeableDecoder.com.facebook.common.references.CloseableReference pinBitmap(android.graphics.Bitmap)(KitKatPurgeableDecoder.java:32)
##_parent_##2##_parent_##
##_child_## com.facebook.common.references.CloseableReference decodeJPEGFromEncodedImage(com.facebook.imagepipeline.image.EncodedImage,android.graphics.Bitmap$Config,int)##_child_##
##_child_## com.facebook.common.references.CloseableReference decodeFromEncodedImage(com.facebook.imagepipeline.image.EncodedImage,android.graphics.Bitmap$Config)##_child_##
com.facebook.imagepipeline.decoder.ImageDecoder.com.facebook.imagepipeline.image.CloseableStaticBitmap decodeJpeg(com.facebook.imagepipeline.image.EncodedImage,int,com.facebook.imagepipeline.image.QualityInfo)(ImageDecoder.java:152)
com.facebook.imagepipeline.decoder.ImageDecoder.com.facebook.imagepipeline.image.CloseableImage decodeImage(com.facebook.imagepipeline.image.EncodedImage,int,com.facebook.imagepipeline.image.QualityInfo,com.facebook.imagepipeline.common.ImageDecodeOptions)(ImageDecoder.java:85)
com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.void doDecode(com.facebook.imagepipeline.image.EncodedImage,boolean)(DecodeProducer.java:189)
##_parent_##1##_parent_##
##_child_## com.facebook.imagepipeline.image.QualityInfo getQualityInfo()##_child_##
com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.int getIntermediateImageEndOffset(com.facebook.imagepipeline.image.EncodedImage)(DecodeProducer.java:97)
##_parent_##3##_parent_##
##_child_## void onNewResultImpl(java.lang.Object,boolean)##_child_##
##_child_## void access$200(com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder,com.facebook.imagepipeline.image.EncodedImage,boolean)##_child_##
##_child_## com.facebook.imagepipeline.producers.ProducerContext access$400(com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder)##_child_##
com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.void run(com.facebook.imagepipeline.image.EncodedImage,boolean)(DecodeProducer.java:129)
com.facebook.imagepipeline.producers.JobScheduler.void doJob()(JobScheduler.java:207)
com.facebook.imagepipeline.producers.JobScheduler.void access$000(com.facebook.imagepipeline.producers.JobScheduler)(JobScheduler.java:27)
com.facebook.imagepipeline.producers.JobScheduler$1.void run()(JobScheduler.java:78)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
com.facebook.imagepipeline.core.PriorityThreadFactory$1.void run()(PriorityThreadFactory.java:43)
java.lang.Thread.run(Thread.java:841)

thank you for the code again

**Comment by massimocarli** [comment] 2016-11-04 20:59
Hi @maplesnow-zsm 
can you provide more info please? What's the problem?

Thanks

**Comment by maplesnow-zsm** [comment] 2016-11-07 02:51
@massimocarli here's the problem, we get lots of customs load image failure with the simpledraweeview, but it not  happens 100 percent ,all of they are useing android below 4.4.4, the log above is all info we catch, what else do you need? we try to get it

thank you

**Comment by oprisnik** [comment] 2018-01-19 14:53
It's still not clear to me what the issue is here. Please provide us with a minimal example how to reproduce the issue. I'm closing this for now but can re-open once we know what the issue is and how to reproduce it.

**Closed by oprisnik** 2018-01-19 14:53 UTC
Labels: needs-details
